#!/usr/bin/env python3
"""Generate every derived file from the ISA definitions (<arch>/isa.py).

  isatool/gen.py                 regenerate for every <arch>/isa.py
  isatool/gen.py --arch cpu5     one ISA (isatool/arches.h is always rewritten)
  isatool/gen.py --check         exit 1 if any generated file is stale

Per ISA:  <arch>/isa_table_c.h   sim_c's assembler/disassembler table
          <arch>/exec_gen.h      sim_c's executor
          <arch>/exec_gen.py     the Python simulator's executor
          docs/isa/<arch>-encoding.md
Shared:   isatool/arches.h       the ISAs sim_c is built with (-arch NAME): every
                                 <arch>/isa.py present, so it is a build output
                                 (gitignored) rather than a checked-in file
"""
import os, sys
here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(here))
from isatool import model, sem

ROOT = model.ROOT
KIND_C = {'reg': 'ISA_REG', 'simm': 'ISA_SIMM', 'uimm': 'ISA_UIMM', 'index': 'ISA_INDEX', 'bytes': 'ISA_BYTES',
          'raw': 'ISA_RAW', 'abs': 'ISA_ABS', 'pcrel': 'ISA_PCREL'}


def gen_table_c(isa):
    L = [f"/* {sem.HDR.format(arch=isa.name)} */",
         f"static const IsaInstr {isa.name}_instrs[] = {{"]
    cur = None
    for i in isa.instrs:
        if i.fmt.name != cur:
            cur = i.fmt.name; L.append(f"    /* {cur}  {i.fmt.tpl} */")
        ops = []
        for o in i.ops:
            runs = o.runs(i.fmt.len)
            sh = ", ".join(str(r[0]) for r in runs); wd = ", ".join(str(r[1]) for r in runs)
            ops.append(f"{{{KIND_C[o.kind]}, {o.bits}, {o.scale}, {len(runs)}, {{{sh}}}, {{{wd}}}}}")
        body = ", ".join(ops) if ops else "{0}"
        L.append(f'    {{"{i.name}", {i.len}, {len(i.ops)}, 0x{i.match:0{i.len * 2}x}u, 0x{i.mask:0{i.len * 2}x}u, {{{body}}}}},')
    L += ["    {0}", "};", f"static const IsaPseudo {isa.name}_pseudos[] = {{"]
    for n, (real, perm) in isa.pseudos.items():
        L.append(f'    {{"{n}", "{real}", {len(perm)}, {{{", ".join(str(x) for x in perm)}}}}},')
    L += ["    {0}", "};", ""]
    return "\n".join(L)


def gen_arches_h(isas):
    L = [f"/* Generated by isatool/gen.py -- do not edit. The ISAs sim_c is built with:",
         "   every <arch>/isa.py in this checkout (a build output, not checked in). */",
         "#ifndef ISATOOL_ARCHES_H", "#define ISATOOL_ARCHES_H"]
    for isa in isas:
        L += [f'#include "../{isa.name}/isa_table_c.h"', f'#include "../{isa.name}/exec_gen.h"']
    L += ["typedef struct {",
          "    const char *name;",
          "    int ngpr;",
          "    const IsaInstr *instrs;",
          "    const IsaPseudo *pseudos;",
          "    int (*step)(Core *);",
          "} IsaArch;",
          "static const IsaArch isa_arches[] = {"]
    for isa in isas:
        L.append(f'    {{"{isa.name}", {isa.ngpr}, {isa.name}_instrs, {isa.name}_pseudos, {isa.name}_gen_step}},')
    L += ["    {0}", "};", "#endif", ""]
    return "\n".join(L)


def pattern_text(i):
    out = []
    for p, c in enumerate(i.fmt.tpl):
        out.append(str(i.pattern[p]) if p in i.pattern else c)
        if p % 8 == 7 and p + 1 < i.fmt.len:
            out.append(' ')
    return "".join(out)


def gen_md(isa):
    L = [f"# {isa.name.upper()} encoding and semantics", "",
         f"<!-- {sem.HDR.format(arch=isa.name)} -->", "",
         f"Generated from `{isa.name}/isa.py`, the definition. Each row gives the instruction's",
         "bit pattern (fixed bits filled in, operand fields as letters), its operands in",
         "assembly order with the immediate kinds and the source range they accept, and its",
         "semantics. Immediate kinds: `simm`/`uimm` signed/unsigned value, `index` element",
         "index (the semantics scale it), `bytes` byte offset encoded divided by its scale,",
         "`raw` bit pattern (signed or unsigned range, or a label), `abs` absolute address,",
         "`pcrel` PC-relative target (a label).", "",
         f"Machine state: {isa.ngpr} general registers of {isa.gpr_bits} bits (`r0`..`r{isa.ngpr - 1}`); "
         + ", ".join(f"{k} {v} bits" for k, v in isa.special.items()) + ".", ""]
    cur = None
    for i in isa.instrs:
        if i.fmt.name != cur:
            cur = i.fmt.name
            spaced = " ".join(i.fmt.tpl[k:k + 8] for k in range(0, i.fmt.len, 8))
            L += ["", f"## {cur} — {i.fmt.bytes} byte{'s' if i.fmt.bytes > 1 else ''}, `{spaced}`", "",
                  "| Mnemonic | Pattern | Operands | Immediates | Semantics |", "|---|---|---|---|---|"]
        imms = []
        for o in i.ops:
            if o.reg:
                continue
            if o.kind in ('pcrel', 'abs'):
                imms.append(f"{o.name}: {o.kind}{o.bits}, label")
            else:
                lo, hi = o.source_range()
                imms.append(f"{o.name}: {o.kind}{o.bits}{' ×' + str(o.scale) if o.scale != 1 else ''}, {lo}..{hi}")
        s = isa.semantics.get(i.name)
        st = f"`{s.replace('|', chr(92) + '|')}`" if s else "*(not yet specified)*"
        L.append(f"| `{i.name}` | `{pattern_text(i)}` | `{i.syntax()}` | {'; '.join(imms) or '—'} | {st} |")
    if isa.pseudos:
        L += ["", "## Pseudo-ops (assembler only)", "", "| Pseudo | Expands to | Operand order |", "|---|---|---|"]
        for n, (real, perm) in isa.pseudos.items():
            L.append(f"| `{n}` | `{real}` | source operands {perm} |")
    if isa.invariants:
        L += ["", "## Invariants", "", "After every instruction each expression must be 0, or the machine stops.", ""]
        for e, m in isa.invariants:
            L.append(f"- `{e}` — {m}")
    L += ["", "## Semantics notation", "", "```"] + isa.preamble.strip().splitlines() + ["```"]
    missing = isa.missing_semantics
    if missing:
        L += ["", f"**{len(missing)} instructions have no semantics yet:** " + ", ".join(f"`{n}`" for n in missing) + "."]
    return "\n".join(L) + "\n"


def outputs(isas):
    out = {}
    for isa in isas:
        out[os.path.join(isa.dir, 'isa_table_c.h')] = gen_table_c(isa)
        out[os.path.join(isa.dir, 'exec_gen.h')] = sem.gen_c(isa)
        out[os.path.join(isa.dir, 'exec_gen.py')] = sem.gen_py(isa)
        out[os.path.join(ROOT, 'docs', 'isa', f'{isa.name}-encoding.md')] = gen_md(isa)
    out[os.path.join(ROOT, 'isatool', 'arches.h')] = gen_arches_h(isas)
    return out


def main():
    args = sys.argv[1:]
    all_isas = []
    for a in model.arches():
        isa = model.load(a)
        sem.check_all(isa)
        all_isas.append(isa)
    chosen = all_isas
    if '--arch' in args:
        name = args[args.index('--arch') + 1]
        chosen = [i for i in all_isas if i.name == name]
        if not chosen:
            sys.exit(f"no ISA named {name}; have {[i.name for i in all_isas]}")
    outs = outputs(chosen)
    outs.update({k: v for k, v in outputs(all_isas).items() if k.endswith('arches.h')})
    if '--check' in args:
        stale = [p for p, t in outs.items() if not os.path.exists(p) or open(p).read() != t]
        for p in stale:
            print("stale:", os.path.relpath(p, ROOT))
        if stale:
            print("run `make isa` (isatool/gen.py) and commit the result"); sys.exit(1)
        print("generated ISA files up to date: " + ", ".join(i.name for i in all_isas)); return
    for p, t in outs.items():
        os.makedirs(os.path.dirname(p), exist_ok=True)
        if not os.path.exists(p) or open(p).read() != t:
            open(p, 'w').write(t); print("wrote", os.path.relpath(p, ROOT))
    for isa in chosen:
        if isa.missing_semantics:
            print(f"{isa.name}: {len(isa.missing_semantics)} instructions have no semantics yet")


if __name__ == '__main__':
    main()
