"""The semantics notation: parser, analysis and executor generators.

An ISA definition (see isatool/model.py) gives each instruction one line of
register-transfer notation; its SEMANTICS_PREAMBLE defines the notation. This
module parses those lines against the instruction's operands and generates:

  gen_c(isa)   <arch>/exec_gen.h   the fetch/decode/execute step sim_c runs
  gen_py(isa)  <arch>/exec_gen.py  the same step for the Python simulator

Both come from the same syntax tree through different back ends and are run
in lockstep by tools/rig.py. `analyse()` summarises what an instruction reads
and writes, which the random generator uses to decide how to exercise it.
"""
import re

HDR = "Generated by isatool/gen.py from {arch}/isa.py -- do not edit; edit the ISA and run `make isa`."

OPS = ['<=u', '<=s', '>=u', '>=s', '>>s', '/u', '%u', '/s', '%s', '<u', '<s', '>u', '>s',
       '==', '!=', '<<', '>>', '+', '-', '*', '&', '|', '^', '~', '!', '?', ':', '(', ')',
       '[', ']', ',', ';', '=']
TOK = re.compile(r'\s*(?:(0x[0-9a-fA-F]+|\d+)|([A-Za-z_][A-Za-z0-9_]*)|(' +
                 '|'.join(re.escape(o) for o in OPS) + '))')
MEM = {'M8': 8, 'M16': 16, 'M32': 32}
LEVELS = [['|'], ['^'], ['&'], ['==', '!='], ['<u', '<=u', '>u', '>=u', '<s', '<=s', '>s', '>=s'],
          ['<<', '>>', '>>s'], ['+', '-'], ['*', '/u', '%u', '/s', '%s']]
CORE_FIELDS = {'PC': 'pc', 'SP': 'sp', 'BP': 'bp', 'LR': 'lr'}   # special registers the simulators hold


class SemError(Exception):
    pass


def tokenize(src):
    out, i, src = [], 0, src.rstrip()
    while i < len(src):
        m = TOK.match(src, i)
        if not m or m.end() == i:
            raise SemError(f"cannot read {src[i:]!r}")
        num, name, op = m.groups()
        out.append(('num', int(num, 0)) if num else ('name', name) if name else ('op', op))
        i = m.end()
    return out + [('end', None)]


class Parser:
    def __init__(self, isa, src, operands):
        self.isa, self.t, self.k, self.operands = isa, tokenize(src), 0, operands
        self.special = dict(isa.special); self.special['H'] = 1

    def peek(self, v=None):
        kind, val = self.t[self.k]
        return (kind, val) if v is None else (val == v and kind in ('op', 'name'))

    def take(self, v=None):
        tok = self.t[self.k]
        if v is not None and tok[1] != v:
            raise SemError(f"expected {v!r}, found {tok[1]!r}")
        self.k += 1
        return tok

    def program(self):
        stmts = [self.stmt()]
        while self.peek(';'):
            self.take(';'); stmts.append(self.stmt())
        if self.peek()[0] != 'end':
            raise SemError(f"unexpected {self.peek()[1]!r}")
        return stmts

    def expression(self):
        e = self.expr()
        if self.peek()[0] != 'end':
            raise SemError(f"unexpected {self.peek()[1]!r}")
        return e

    def stmt(self):
        if self.peek('if'):
            self.take('if'); c = self.expr(); self.take('then')
            return ('if', c, self.stmt())
        kind, val = self.peek()
        if kind == 'name' and val == 'putchar':
            return ('do', self.primary())
        lv = self.lvalue(); self.take('='); return ('assign', lv, self.expr())

    def lvalue(self):
        kind, val = self.take()
        if val == 'R':
            self.take('['); e = self.expr(); self.take(']'); return ('reg', e)
        if val in self.special:
            return ('spec', val)
        if val in MEM:
            self.take('['); e = self.expr(); self.take(']'); return ('mem', MEM[val], e)
        raise SemError(f"cannot assign to {val!r}")

    def expr(self):
        c = self.binary(0)
        if self.peek('?'):
            self.take('?'); a = self.expr(); self.take(':'); b = self.expr()
            return ('cond', c, a, b)
        return c

    def binary(self, lvl):
        if lvl == len(LEVELS):
            return self.unary()
        a = self.binary(lvl + 1)
        while self.peek()[0] == 'op' and self.peek()[1] in LEVELS[lvl]:
            op = self.take()[1]; a = ('bin', op, a, self.binary(lvl + 1))
        return a

    def unary(self):
        if self.peek()[0] == 'op' and self.peek()[1] in ('-', '~', '!'):
            op = self.take()[1]; return ('un', op, self.unary())
        return self.primary()

    def primary(self):
        kind, val = self.take()
        if kind == 'num':
            return ('num', val)
        if kind == 'op' and val == '(':
            e = self.expr(); self.take(')'); return e
        if kind != 'name':
            raise SemError(f"unexpected {val!r}")
        if val == 'R':
            self.take('['); e = self.expr(); self.take(']'); return ('reg', e)
        if val in MEM:
            self.take('['); e = self.expr(); self.take(']'); return ('mem', MEM[val], e)
        if val in self.special:
            return ('spec', val)
        if self.peek('('):
            self.take('('); args = [self.expr()]
            while self.peek(','):
                self.take(','); args.append(self.expr())
            self.take(')')
            want = {'sext': 1, 'sx': 2, 'zx': 2, 'lo16': 1, 'putchar': 1, **self.isa.primitives}
            if val not in want:
                raise SemError(f"unknown function {val!r}")
            if len(args) != want[val]:
                raise SemError(f"{val} takes {want[val]} argument(s)")
            if val == 'sext' and args[0][0] != 'operand':
                raise SemError("sext() takes an immediate operand name")
            return ('call', val, args)
        if val in self.operands:
            return ('operand', val)
        raise SemError(f"unknown name {val!r}")


def parse(isa, i):
    try:
        return Parser(isa, isa.semantics[i.name], set(i.op_names)).program()
    except SemError as e:
        raise SemError(f"{isa.name} {i.name}: {e} in {isa.semantics[i.name]!r}") from None


def parse_invariant(isa, expr):
    try:
        return Parser(isa, expr, set()).expression()
    except SemError as e:
        raise SemError(f"{isa.name} invariant {expr!r}: {e}") from None


# ---------------------------------------------------------------- analysis
def analyse(isa, i):
    """What the instruction touches: {'writes': set, 'reads': set, 'cond': bool, 'mem_r', 'mem_w', 'call', 'halt'}.
    Names: 'R', 'M', 'PC', 'SP', 'BP', 'LR', 'H', 'out'."""
    info = {'writes': set(), 'reads': set(), 'cond': False, 'pc_forms': set(), 'mem_addr': []}
    if i.name not in isa.semantics:
        info['unspecified'] = True
        return info

    def expr(n):
        k = n[0]
        if k == 'reg': info['reads'].add('R'); expr(n[1])
        elif k == 'spec': info['reads'].add(n[1])
        elif k == 'mem': info['reads'].add('M'); info['mem_addr'].append(n[2]); expr(n[2])
        elif k in ('un',): expr(n[2])
        elif k == 'bin': expr(n[2]); expr(n[3])
        elif k == 'cond': expr(n[1]); expr(n[2]); expr(n[3])
        elif k == 'call':
            for a in n[2]: expr(a)

    def stmt(s):
        if s[0] == 'if':
            info['cond'] = True; expr(s[1]); stmt(s[2])
        elif s[0] == 'do':
            info['writes'].add('out'); expr(s[1])
        else:
            lv, v = s[1], s[2]
            if lv[0] == 'reg': info['writes'].add('R'); expr(lv[1])
            elif lv[0] == 'spec':
                info['writes'].add(lv[1])
                if lv[1] == 'PC':
                    info['pc_forms'].add('rel' if v[0] == 'bin' and v[2] == ('spec', 'PC') else
                                         'reg' if v[0] == 'reg' else
                                         'imm' if v[0] == 'operand' else 'mem')
            elif lv[0] == 'mem': info['writes'].add('M'); info['mem_addr'].append(lv[2]); expr(lv[2])
            expr(v)
    for s in parse(isa, i):
        stmt(s)
    return info


# ---------------------------------------------------------------- C back end
def c_extract(op, total):
    expr = None
    for shift, width in op.runs(total):
        part = f"((w >> {shift}) & 0x{(1 << width) - 1:x}u)"
        expr = part if expr is None else f"(({expr}) << {width}) | {part}"
    return expr


def check_core(isa):
    extra = set(isa.special) - set(CORE_FIELDS)
    if extra:
        raise SemError(f"{isa.name}: special registers {sorted(extra)} have no place in the simulators' state yet")


class CGen:
    def __init__(self, isa, i):
        self.isa, self.i = isa, i
        self.ops = {o.name: o for o in i.ops} if i is not None else {}

    def e(self, n):
        k = n[0]
        if k == 'num':
            return f"0x{n[1]:x}u"
        if k == 'operand':
            o = self.ops[n[1]]
            if o.reg:
                raise SemError(f"{self.i.name}: register field {n[1]} used as a value; write R[{n[1]}]")
            return f"f_{n[1]}"
        if k == 'reg':
            idx = n[1]
            if idx[0] == 'operand' and self.ops[idx[1]].reg:
                return f"cc->r[f_{idx[1]}]"
            if idx[0] == 'num':
                if idx[1] >= self.isa.ngpr:
                    raise SemError(f"R[{idx[1]}] is beyond the {self.isa.ngpr} registers")
                return f"cc->r[{idx[1]}]"
            raise SemError(f"{self.i.name}: R[] takes a register field or a constant")
        if k == 'spec':
            return "(uint32_t)cc->H" if n[1] == 'H' else f"(uint32_t)cc->{CORE_FIELDS[n[1]]}"
        if k == 'mem':
            return f"gen_rd{n[1]}({self.e(n[2])}, oldpc)"
        if k == 'un':
            a = self.e(n[2])
            return {'-': f"(uint32_t)(0u - {a})", '~': f"(uint32_t)~{a}", '!': f"(uint32_t)!{a}"}[n[1]]
        if k == 'cond':
            return f"({self.e(n[1])} ? {self.e(n[2])} : {self.e(n[3])})"
        if k == 'call':
            f, a = n[1], n[2]
            if f == 'sext':
                return f"sx32(f_{a[0][1]}, {self.ops[a[0][1]].bits})"
            if f == 'sx':
                return f"sx32({self.e(a[0])}, {self.const(a[1])})"
            if f == 'zx':
                return f"({self.e(a[0])} & 0x{(1 << self.const(a[1])) - 1:x}u)"
            if f == 'lo16':
                return f"({self.e(a[0])} & 0xffffu)"
            if f in self.isa.primitives:
                return f"{self.isa.prim_prefix}{f}(" + ", ".join(self.e(x) for x in a) + ")"
            raise SemError(f"{f}() is a statement, not a value")
        if k == 'bin':
            op, a, b = n[1], self.e(n[2]), self.e(n[3])
            if op in ('+', '-', '*', '&', '|', '^', '==', '!='):
                return f"(uint32_t)({a} {op} {b})"
            if op[-1] in 'us' and op[:-1] in ('<', '<=', '>', '>='):
                c = op[:-1]
                return f"(uint32_t)({a} {c} {b})" if op[-1] == 'u' else f"(uint32_t)((int32_t){a} {c} (int32_t){b})"
            fn = {'<<': 'shl32', '>>': 'shr32', '>>s': 'sar32', '/u': 'divu32', '%u': 'modu32',
                  '/s': 'divs32', '%s': 'mods32'}[op]
            return f"{fn}({a}, {b})"
        raise SemError(f"cannot generate {k}")

    def const(self, n):
        if n[0] != 'num':
            raise SemError("width must be a constant")
        return n[1]

    def s(self, st, ind="    "):
        k = st[0]
        if k == 'if':
            return f"{ind}if ({self.e(st[1])}) {{\n{self.s(st[2], ind + '    ')}{ind}}}\n"
        if k == 'do':
            return f"{ind}gen_putchar({self.e(st[1][2][0])});\n"
        lv, v = st[1], self.e(st[2])
        if lv[0] == 'reg':
            return f"{ind}{self.e(lv)} = {v};\n"
        if lv[0] == 'spec':
            if lv[1] == 'H':
                return f"{ind}cc->H = ({v}) & 1u;\n"
            return f"{ind}cc->{CORE_FIELDS[lv[1]]} = (uint16_t)({v});\n"
        if lv[0] == 'mem':
            return f"{ind}gen_wr{lv[1]}({self.e(lv[2])}, {v}, oldpc);\n"
        raise SemError("bad assignment")

    def function(self):
        i, p = self.i, self.isa.name
        sem = self.isa.semantics.get(i.name)
        body = [f"/* {i.name}: {sem if sem else '(no semantics yet)'} */",
                f"static void {p}_gx_{i.name}(Core *cc, uint32_t w, uint16_t oldpc) {{"]
        for o in i.ops:
            body.append(f"    const uint32_t f_{o.name} = {c_extract(o, i.fmt.len)}; (void)f_{o.name};")
        body.append("    (void)w; (void)oldpc;")
        if sem is None:
            body.append(f"    gen_unimplemented(cc, \"{i.name}\", oldpc);")
        else:
            for st in parse(self.isa, i):
                body.append(self.s(st).rstrip("\n"))
        body.append("}")
        return "\n".join(body)


def decode_blocks(isa):
    """First-byte dispatch: {(length, [(key value, instr)] or instr, key positions): [first byte values]}."""
    blocks = []
    for v in range(256):
        cands = [i for i in isa.instrs
                 if all(((v >> (7 - p)) & 1) == b for p, b in i.pattern.items() if p < 8)]
        if not cands:
            continue
        lens = {i.len for i in cands}
        if len(lens) != 1:
            raise SemError(f"{isa.name}: first byte 0x{v:02x} starts instructions of different lengths "
                           f"({', '.join(i.name for i in cands)}); the length must be known from the first byte")
        n = lens.pop()
        keypos = sorted({p for i in cands for p in i.pattern if p >= 8})
        arms = []
        for i in cands:
            missing = [p for p in keypos if p not in i.pattern]
            if missing:
                raise SemError(f"{isa.name}: 0x{v:02x}: {i.name} leaves a distinguishing bit free")
            kv = 0
            for p in keypos:
                kv = (kv << 1) | i.pattern[p]
            arms.append((kv, i))
        blocks.append((v, n, keypos, arms))
    return blocks


def gen_c(isa):
    check_core(isa)
    p = isa.name
    L = [f"/* {HDR.format(arch=p)} */",
         f"/* The {p} fetch/decode/execute step, generated from the format templates,",
         " * opcodes, operands, invariants and semantics in the ISA definition.",
         " * Included by sim_c.c after isatool/exec_common.h. */",
         f"#ifndef {p.upper()}_EXEC_GEN_H", f"#define {p.upper()}_EXEC_GEN_H", ""]
    if isa.prim_c:      # the primitives' header, a path from the toolchain root; this file is <arch>/exec_gen.h
        L += [f'#include "../{isa.prim_c}"', ""]
    for i in isa.instrs:
        L.append(CGen(isa, i).function()); L.append("")
    # invariants
    L.append(f"static void {p}_gen_check(Core *cc, uint16_t oldpc) {{")
    for expr, msg in isa.invariants:
        e = CGen(isa, None).e(parse_invariant(isa, expr))
        L.append(f"    if ({e}) {{ fprintf(stderr, \"{p.upper()} {msg} (0x%x) at pc=0x%04x\\n\", (unsigned){e}, oldpc); cc->H = 1; }}")
    L += ["    (void)cc; (void)oldpc;", "}", ""]
    # decoder
    L += [f"/* Execute one instruction for core cc; returns its length in bytes. */",
          f"static int {p}_gen_step(Core *cc) {{",
          "    const uint16_t oldpc = cc->pc;",
          "    uint32_t w;",
          "    int n = 1;",
          "    switch (read8(oldpc)) {"]
    groups = {}
    for v, n, keypos, arms in decode_blocks(isa):
        if len(arms) == 1 and not keypos:
            code = f"{p}_gx_{arms[0][1].name}(cc, w, oldpc);"
        else:
            key = c_extract(_Pos(keypos), n * 8)
            body = "\n".join(f"        case 0x{kv:x}: {p}_gx_{i.name}(cc, w, oldpc); break;" for kv, i in arms)
            code = f"switch ({key}) {{\n{body}\n        default: gen_unknown(cc, w, oldpc); break;\n        }}"
        groups.setdefault((n, code), []).append(v)
    for (n, code), vals in sorted(groups.items(), key=lambda kv: kv[1][0]):
        L.append("    " + " ".join(f"case 0x{v:02x}:" for v in vals))
        L.append(f"        n = {n}; w = gen_fetch(oldpc, {n}); cc->pc = (uint16_t)(oldpc + {n});")
        L.append(f"        {code}")
        L.append("        break;")
    L += ["    default:",
          "        gen_unknown(cc, read8(oldpc), oldpc);",
          "        cc->pc = (uint16_t)(oldpc + 1);",
          "        break;",
          "    }",
          f"    {p}_gen_check(cc, oldpc);",
          "    return n;",
          "}", "#endif", ""]
    return "\n".join(L)


class _Pos:
    """Adapter so a list of key positions can use c_extract/py_extract."""
    def __init__(self, positions):
        self.positions = positions

    def runs(self, total):
        out, cur = [], [self.positions[0]]
        for q in self.positions[1:]:
            if q == cur[-1] + 1:
                cur.append(q)
            else:
                out.append(cur); cur = [q]
        out.append(cur)
        return [(total - 1 - r[-1], len(r)) for r in out]


# ---------------------------------------------------------------- Python back end
M32 = "0xffffffff"


def py_extract(op, total):
    expr = None
    for shift, width in op.runs(total):
        part = f"((w >> {shift}) & 0x{(1 << width) - 1:x})"
        expr = part if expr is None else f"(({expr}) << {width}) | {part}"
    return expr


class PyGen(CGen):
    def e(self, n):
        k = n[0]
        if k == 'num':
            return str(n[1])
        if k == 'operand':
            o = self.ops[n[1]]
            if o.reg:
                raise SemError(f"{self.i.name}: register field {n[1]} used as a value; write R[{n[1]}]")
            return f"f_{n[1]}"
        if k == 'reg':
            idx = n[1]
            if idx[0] == 'operand' and self.ops[idx[1]].reg:
                return f"s.r[f_{idx[1]}]"
            if idx[0] == 'num':
                return f"s.r[{idx[1]}]"
            raise SemError(f"{self.i.name}: R[] takes a register field or a constant")
        if k == 'spec':
            return "s.H" if n[1] == 'H' else f"s.{CORE_FIELDS[n[1]]}"
        if k == 'mem':
            return f"rd{n[1]}(m, {self.e(n[2])}, oldpc)"
        if k == 'un':
            a = self.e(n[2])
            return {'-': f"((-{a}) & {M32})", '~': f"((~{a}) & {M32})", '!': f"(0 if {a} else 1)"}[n[1]]
        if k == 'cond':
            return f"({self.e(n[2])} if {self.e(n[1])} else {self.e(n[3])})"
        if k == 'call':
            f, a = n[1], n[2]
            if f == 'sext':
                return f"sx32(f_{a[0][1]}, {self.ops[a[0][1]].bits})"
            if f == 'sx':
                return f"sx32({self.e(a[0])}, {self.const(a[1])})"
            if f == 'zx':
                return f"({self.e(a[0])} & {(1 << self.const(a[1])) - 1})"
            if f == 'lo16':
                return f"({self.e(a[0])} & 0xffff)"
            if f in self.isa.primitives:
                return f"{self.isa.prim_prefix}{f}(" + ", ".join(self.e(x) for x in a) + ")"
            raise SemError(f"{f}() is a statement, not a value")
        if k == 'bin':
            op, a, b = n[1], self.e(n[2]), self.e(n[3])
            if op in ('+', '-', '*'):
                return f"(({a} {op} {b}) & {M32})"
            if op in ('&', '|', '^'):
                return f"({a} {op} {b})"
            if op in ('==', '!='):
                return f"int({a} {op} {b})"
            if op[-1] in 'us' and op[:-1] in ('<', '<=', '>', '>='):
                c = op[:-1]
                return f"int({a} {c} {b})" if op[-1] == 'u' else f"int(s32({a}) {c} s32({b}))"
            fn = {'<<': 'shl32', '>>': 'shr32', '>>s': 'sar32', '/u': 'divu32', '%u': 'modu32',
                  '/s': 'divs32', '%s': 'mods32'}[op]
            return f"{fn}({a}, {b})"
        raise SemError(f"cannot generate {k}")

    def s(self, st, ind="    "):
        k = st[0]
        if k == 'if':
            return f"{ind}if {self.e(st[1])}:\n{self.s(st[2], ind + '    ')}"
        if k == 'do':
            return f"{ind}putc({self.e(st[1][2][0])})\n"
        lv, v = st[1], self.e(st[2])
        if lv[0] == 'reg':
            return f"{ind}{self.e(lv)} = {v}\n"
        if lv[0] == 'spec':
            return f"{ind}s.H = {v} & 1\n" if lv[1] == 'H' else f"{ind}s.{CORE_FIELDS[lv[1]]} = {v} & 0xffff\n"
        if lv[0] == 'mem':
            return f"{ind}wr{lv[1]}(m, {self.e(lv[2])}, {v}, oldpc)\n"
        raise SemError("bad assignment")

    def function(self):
        i = self.i
        sem = self.isa.semantics.get(i.name)
        body = [f"def gx_{i.name}(s, m, w, oldpc):", f"    # {sem if sem else '(no semantics yet)'}"]
        for o in i.ops:
            body.append(f"    f_{o.name} = {py_extract(o, i.fmt.len)}")
        if sem is None:
            body.append(f"    unimplemented(s, {i.name!r}, oldpc)")
        else:
            for st in parse(self.isa, i):
                body.append(self.s(st).rstrip("\n"))
        return "\n".join(body)


PY_HELPERS = '''import sys

M = 0xffffffff
MW = None   # when a list, every store is appended as (address, value, bytes) for the retirement trace
# The float primitives (PRIMITIVES in the ISA definition) are bound into this
# module's namespace by isatool/pysim.py before the first step.

def s32(v): return v - 0x100000000 if v & 0x80000000 else v
def sx32(v, n): v &= (1 << n) - 1; return (v - (1 << n)) & M if v >> (n - 1) else v
def shl32(a, b): return 0 if b >= 32 else (a << b) & M
def shr32(a, b): return 0 if b >= 32 else a >> b
def sar32(a, b): return (M if a & 0x80000000 else 0) if b >= 32 else (s32(a) >> b) & M
def divu32(a, b): return a // b if b else 0
def modu32(a, b): return a % b if b else 0
def divs32(a, b):
    if not b: return 0
    if a == 0x80000000 and b == M: return a
    q = abs(s32(a)) // abs(s32(b))
    return (q if (s32(a) < 0) == (s32(b) < 0) else -q) & M
def mods32(a, b):
    if not b: return 0
    if a == 0x80000000 and b == M: return 0
    r = abs(s32(a)) % abs(s32(b))
    return (-r if s32(a) < 0 else r) & M
def _fault(bits, a, pc):
    sys.stderr.write('%s alignment error: %d-bit access to unaligned address 0x%08x at pc=0x%04x\\n' % (ARCH.upper(), bits, a, pc))
    sys.exit(1)
def rd8(m, a, pc): return m.read8(a, False)
def rd16(m, a, pc):
    if a & 1: _fault(16, a, pc)
    return m.read16(a, False)
def rd32(m, a, pc):
    if a & 3: _fault(32, a, pc)
    return m.read32(a, False)
def wr8(m, a, v, pc):
    if MW is not None: MW.append((a, v & 0xff, 1))
    m.write8(a, v & 0xff)
def wr16(m, a, v, pc):
    if a & 1: _fault(16, a, pc)
    if MW is not None: MW.append((a, v & 0xffff, 2))
    m.write16(a, v & 0xffff)
def wr32(m, a, v, pc):
    if a & 3: _fault(32, a, pc)
    if MW is not None: MW.append((a, v, 4))
    m.write32(a, v)
def putc(v):
    sys.stderr.write(chr(v & 0xff)); sys.stderr.flush()
def unknown(s, w, pc):
    sys.stderr.write('%s: unknown instruction 0x%x at pc=%04x\\n' % (ARCH, w, pc))
    s.H = 1
def unimplemented(s, name, pc):
    sys.stderr.write('%s: instruction %s at pc=%04x has no semantics yet\\n' % (ARCH, name, pc))
    s.H = 1
'''


def gen_py(isa):
    check_core(isa)
    L = [f"# {HDR.format(arch=isa.name)}",
         f'"""The {isa.name} fetch/decode/execute step for the Python simulator (isatool/pysim.py)."""',
         f"ARCH = {isa.name!r}", PY_HELPERS]
    for i in isa.instrs:
        L.append(PyGen(isa, i).function()); L.append("")
    L.append("def check(s, oldpc):")
    for expr, msg in isa.invariants:
        e = PyGen(isa, None).e(parse_invariant(isa, expr))
        L.append(f"    if {e}:")
        L.append(f"        sys.stderr.write('{isa.name.upper()} {msg} (0x%x) at pc=0x%04x\\n' % ({e}, oldpc)); s.H = 1")
    L += ["    pass", ""]
    keyfns, entries = {}, []
    for v, n, keypos, arms in decode_blocks(isa):
        if len(arms) == 1 and not keypos:
            entries.append(f"    0x{v:02x}: ({n}, gx_{arms[0][1].name}, None, None),")
            continue
        kexpr = py_extract(_Pos(keypos), n * 8)
        kname = keyfns.setdefault(kexpr, f"_key{len(keyfns)}")
        entries.append(f"    0x{v:02x}: ({n}, None, {kname}, {{" + ", ".join(f"0x{kv:x}: gx_{i.name}" for kv, i in arms) + "}),")
    for kexpr, kname in keyfns.items():
        L.append(f"def {kname}(w): return {kexpr}")
    L += ["", "DECODE = {"] + entries + ["}", "",
          "def step(s, m):",
          '    """Execute one instruction; returns its length in bytes."""',
          "    oldpc = s.pc",
          "    e = DECODE.get(m.read8(oldpc, False))",
          "    if e is None:",
          "        unknown(s, m.read8(oldpc, False), oldpc); s.pc = (oldpc + 1) & 0xffff",
          "        check(s, oldpc)",
          "        return 1",
          "    n, fn, key, table = e",
          "    w = 0",
          "    for i in range(n):",
          "        w = (w << 8) | m.read8((oldpc + i) & 0xffff, False)",
          "    s.pc = (oldpc + n) & 0xffff",
          "    if fn is None:",
          "        fn = table.get(key(w))",
          "    if fn is None:",
          "        unknown(s, w, oldpc)",
          "    else:",
          "        fn(s, m, w, oldpc)",
          "    check(s, oldpc)",
          "    return n",
          ""]
    return "\n".join(L)


def check_all(isa):
    """Parse every line and invariant and build every function; raise on the first problem."""
    for i in isa.instrs:
        if i.name in isa.semantics:
            parse(isa, i)
        CGen(isa, i).function(); PyGen(isa, i).function()
    for expr, _ in isa.invariants:
        parse_invariant(isa, expr)
    decode_blocks(isa)
