/*
 * sim_c.c — assembler + simulator for the ISAs defined by <arch>/isa.py
 * (instruction tables and executors generated by isatool/gen.py; CPU4 is
 * the default, the device models are CPU4's)
 *
 * Usage:  ./sim_c [-trace FILE] [-arch NAME] [-maxsteps N] [-load ADDR FILE] file.s
 * Output: putchar to stderr; state line to stdout
 *   r0:..r7:XXXXXXXX sp:XXXX bp:XXXX lr:XXXX pc:XXXX H:X cycles:N
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <ctype.h>
#include <math.h>
#include <stdbool.h>
#include <stdarg.h>
#include "isatool/isa_types.h"      /* tables generated from <arch>/isa.py */

/* ------------------------------------------------------------------ */
/* Memory                                                               */
/* ------------------------------------------------------------------ */
/*
 * The hardware data port is a 32-bit byte address with three regions
 * (per cpu4_hardware/docs/architecture.md §"Memory map and routing"):
 *
 *   0x0000_0000–0x0000_FEFF  64 KB − 256 B  BRAM (code + data + stack)
 *   0x0000_FF00–0x0000_FFFF  256 B          MMIO sub-decode
 *   0x0001_0000–0x01FF_FFFF  ~32 MB         SDRAM (chip byte address = CPU addr)
 *   0x0200_0000–0xFFFF_FFFF  —              Aliases SDRAM (addr[24:0] reaches chip)
 *
 * The first 64 KB of SDRAM (chip byte 0x0..0xFFFF) is shadowed by BRAM
 * and unreachable from the un-aliased range; the alias is the only way
 * to reach it. Aligned-access checks are still enforced (see
 * check_align16/check_align32).
 */

static uint8_t  mem[65536];                    /* 64 KB BRAM (assembler image) */
static uint8_t *sdram = NULL;                  /* 32 MB, lazy allocated */

/* ── Multi-core support (-cores N) ──────────────────────────────────
 * N cores, each with its own registers and a private copy of the 64 KB
 * BRAM image (SPMD: every core boots the same program at pc=0 and
 * branches on CORE_ID, MMIO 0xFF24). SDRAM, the display, and the SDRAM
 * keyhole are shared. Scheduling is deterministic round-robin: one
 * instruction per live core per tick; g_cycles counts ticks (for
 * -cores 1 that is identical to the historical instructions count).
 * `mem` above stays the pristine assembler image; execution runs
 * against the current core's BRAM via g_bram. */
#define SIM_MAX_CORES 1024
typedef struct {
    uint32_t r[ISA_MAX_GPR];   /* the ISA uses the first g_arch->ngpr */
    uint16_t sp, bp, lr, pc;
    int      H;
    uint64_t insns;            /* instructions executed by this core */
    uint8_t *bram;             /* private BRAM (code + data + stack); shared by a tile's contexts in -soc */
} Core;
static Core    *g_cores  = NULL;
static int      g_ncores = 1;
static int      g_curcore = 0;     /* index of the core executing now */
static uint8_t *g_bram   = mem;    /* BRAM the router reads/writes */

/* ── -soc: the KU5P cpu4_socN model (2026-09-15) ─────────────────────
 * Each of the N cores is a barrel TILE of SOC_NCTX hardware contexts that
 * share the tile's 64 KB BRAM (one Core entry per context; g_cores has
 * N*SOC_NCTX entries, contexts 1..7 start parked = halted). The SoC's MMIO
 * replaces the legacy core-id words:
 *   0xFF24 LAUNCH_PCSP  w: {sp[15:0], pc[15:0]}   r: the same word
 *   0xFF28 LAUNCH_CTRL  w: {bit8 kill, [2:0] ctx} starts (or parks) that
 *                          context at the last LAUNCH_PCSP; r: bit0 busy (0)
 *   0xFF2C CORE_ID      r: {NCORES[15:8], id[7:0]}
 * Without -soc the historical map (CORE_ID 0xFF24 / NCORES 0xFF28) stands. */
#define SOC_NCTX 8
static int      g_soc    = 0;
static int      g_nunits = 1;      /* schedulable Core entries (= g_ncores, or g_ncores*SOC_NCTX) */
static int      g_live   = 0;      /* non-halted units */
typedef struct { uint16_t launch_pc, launch_sp; } Tile;
static Tile    *g_tiles  = NULL;

#define MMIO_BASE 0xFF00u
#define SDRAM_SIZE (32u * 1024u * 1024u)       /* 0x0200_0000 */

static void ensure_sdram(void) {
    if (!sdram) {
        sdram = calloc(SDRAM_SIZE, 1);
        if (!sdram) { fprintf(stderr, "sim_c: SDRAM allocation failed\n"); exit(1); }
    }
}

/* SDRAM chip byte for any 32-bit CPU address that lives in the SDRAM
 * range (callers must have already routed away from BRAM and MMIO).
 * Both the un-aliased (0x10000..0x1FFFFFF) and aliased (>=0x2000000)
 * ranges land here; addr[31:25] is don't-care. */
static uint32_t sdram_chip_byte(uint32_t a) { return a & 0x1FFFFFFu; }

static uint64_t g_cycles = 0;   /* MMIO 0xFF00 reads the low 32 bits */

/* ------------------------------------------------------------------ */
/* Profiling                                                            */
/* ------------------------------------------------------------------ */

static int       g_profile   = 0;
static const char *g_pccount_out = NULL;   /* -pccount FILE: "pc count" per executed pc */
static FILE      *g_imap = NULL;           /* -imap FILE: "addr len mnemonic" per assembled instruction */
static const char *g_dump_out = NULL;
static uint16_t  g_asm_end   = 0;   /* high-water mark of assembler cur */
static uint32_t  prof_count[65536];   /* execution count per PC address */
static int16_t   prof_lineno[65536];  /* addr -> source line index (-1 = none) */
static char    **prof_lines  = NULL;  /* original source lines (strdup'd) */
static int       prof_nlines = 0;

/* ------------------------------------------------------------------ */
/* Source-line map (-linemap): PC -> (file, line)                       */
/* Populated from "; @src FILE LINE" directives emitted by smallcc -g.  */
/* ------------------------------------------------------------------ */

typedef struct { uint16_t addr; char file[128]; int line; } SrcLoc;
static SrcLoc   *g_srclocs      = NULL;
static int       g_nsrclocs     = 0;
static int       g_cap_srclocs  = 0;
static const char *g_linemap_out = NULL;
static const char *g_hex_out     = NULL;

static void add_srcloc(uint16_t addr, const char *file, int line)
{
    if (g_nsrclocs == g_cap_srclocs) {
        int nc = g_cap_srclocs ? g_cap_srclocs * 2 : 256;
        SrcLoc *nb = realloc(g_srclocs, nc * sizeof(SrcLoc));
        if (!nb) { fprintf(stderr, "oom srcloc\n"); exit(1); }
        g_srclocs = nb; g_cap_srclocs = nc;
    }
    SrcLoc *sl = &g_srclocs[g_nsrclocs++];
    sl->addr = addr;
    sl->line = line;
    size_t n = strlen(file);
    if (n >= sizeof(sl->file)) n = sizeof(sl->file) - 1;
    memcpy(sl->file, file, n);
    sl->file[n] = '\0';
}

/* Dump the assembled image as whitespace-delimited hex bytes. Covers
 * [0 .. g_asm_end), i.e. all code + data the assembler produced. */
static void dump_hex(const char *path)
{
    FILE *f = fopen(path, "w");
    if (!f) { perror(path); return; }
    for (uint16_t a = 0; a < g_asm_end; a++) {
        fprintf(f, "%02x%c", mem[a],
                ((a + 1) % 32 == 0 || a + 1 == g_asm_end) ? '\n' : ' ');
    }
    fclose(f);
}

/* Dump collected (pc -> file:line) entries as JSON. */
static void dump_linemap(const char *path)
{
    FILE *f = fopen(path, "w");
    if (!f) { perror(path); return; }
    fprintf(f, "{\n");
    for (int i = 0; i < g_nsrclocs; i++) {
        fprintf(f, "  \"0x%04x\": {\"file\": \"%s\", \"line\": %d}%s\n",
                g_srclocs[i].addr, g_srclocs[i].file, g_srclocs[i].line,
                (i == g_nsrclocs - 1) ? "" : ",");
    }
    fprintf(f, "}\n");
    fclose(f);
}

static void prof_split_lines(const char *src)
{
    /* Count lines */
    int n = 0;
    const char *p = src;
    while (*p) { if (*p++ == '\n') n++; }
    if (src[0] != '\0') n++;  /* last line even without trailing newline */

    prof_lines = malloc(((size_t)n + 1) * sizeof(char *));
    if (!prof_lines) { fprintf(stderr, "oom\n"); exit(1); }
    prof_nlines = 0;

    p = src;
    while (*p) {
        const char *eol = strchr(p, '\n');
        size_t len = eol ? (size_t)(eol - p) : strlen(p);
        char *line = malloc(len + 1);
        if (!line) { fprintf(stderr, "oom\n"); exit(1); }
        memcpy(line, p, len);
        line[len] = '\0';
        if (len > 0 && line[len-1] == '\r') line[--len] = '\0';
        prof_lines[prof_nlines++] = line;
        if (!eol) break;
        p = eol + 1;
    }
}

typedef struct { uint32_t count; uint16_t addr; } ProfEntry;

static int prof_entry_cmp(const void *a, const void *b)
{
    const ProfEntry *pa = (const ProfEntry *)a;
    const ProfEntry *pb = (const ProfEntry *)b;
    if (pb->count > pa->count) return  1;
    if (pb->count < pa->count) return -1;
    return 0;
}

static void print_profile(void)
{
    unsigned long long total = 0;
    for (int i = 0; i < 65536; i++) total += prof_count[i];
    fprintf(stderr, "\nProfile: %llu instructions executed\n\n", total);

    /* --- Section A: top 40 hottest instructions --- */
    ProfEntry *entries = malloc(65536 * sizeof(ProfEntry));
    if (!entries) { fprintf(stderr, "oom\n"); return; }
    int nentries = 0;
    for (int i = 0; i < 65536; i++) {
        if (prof_count[i] > 0) {
            entries[nentries].count = prof_count[i];
            entries[nentries].addr  = (uint16_t)i;
            nentries++;
        }
    }
    qsort(entries, (size_t)nentries, sizeof(ProfEntry), prof_entry_cmp);

    fprintf(stderr, "Top 40 hot instructions:\n");
    fprintf(stderr, "  %10s  %7s  %4s  %s\n", "count", "%total", "addr", "source");
    int top = nentries < 40 ? nentries : 40;
    for (int i = 0; i < top; i++) {
        uint16_t    a   = entries[i].addr;
        uint32_t    cnt = entries[i].count;
        double      pct = total ? (100.0 * cnt / total) : 0.0;
        int16_t     ln  = prof_lineno[a];
        const char *src = (ln >= 0 && ln < prof_nlines) ? prof_lines[ln] : "";
        while (*src == ' ' || *src == '\t') src++;
        fprintf(stderr, "  %10u  %6.2f%%  %04x  %s\n", cnt, pct, (unsigned)a, src);
    }
    free(entries);

    /* --- Section B: annotated listing --- */
    /* Build lineno2addr: first address seen for each source line */
    int *lineno2addr = malloc((size_t)prof_nlines * sizeof(int));
    if (!lineno2addr) { fprintf(stderr, "oom\n"); return; }
    for (int i = 0; i < prof_nlines; i++) lineno2addr[i] = -1;
    for (int a = 0; a < 65536; a++) {
        int16_t ln = prof_lineno[a];
        if (ln >= 0 && ln < prof_nlines && lineno2addr[ln] == -1)
            lineno2addr[ln] = a;
    }

    fprintf(stderr, "\nAnnotated listing:\n");
    for (int ln = 0; ln < prof_nlines; ln++) {
        int         a    = lineno2addr[ln];
        const char *text = prof_lines[ln];
        if (a >= 0 && prof_count[a] > 0) {
            uint32_t cnt = prof_count[a];
            double   pct = total ? (100.0 * cnt / total) : 0.0;
            fprintf(stderr, "%10u %6.2f%%  %04x  |%s\n", cnt, pct, (unsigned)a, text);
        } else {
            fprintf(stderr, "                    |%s\n", text);
        }
    }
    free(lineno2addr);
}

/* MMIO state. Most registers are simple word-aligned RW shadows; the
 * SDRAM keyhole is modelled with a single-slot scoreboard that completes
 * synchronously (a real-hardware request takes ~10–20 cycles, but for
 * simulator behavioural fidelity instant completion is fine — software
 * still polls the busy bit, it just always sees it clear). */
static uint32_t g_disp_mode      = 0;          /* 0xFF1C */
static uint32_t g_disp_lut[256]  = {0};        /* 0xFF20 latches via index byte */
static uint32_t g_perfcnt[16]    = {0};        /* 0xFF40-0xFF7C  (cycle counter at idx 0 mirrors g_cycles) */
static uint32_t g_sdram_addr_w   = 0;          /* 0xFFA0 — word address into SDRAM */
static uint32_t g_sdram_wdata    = 0;          /* 0xFFA4 */
static uint32_t g_sdram_rdata    = 0;          /* 0xFFAC — last completed READ result */

static uint16_t g_watch_pc = 0; /* set to pc of instruction being executed */
static uint32_t g_watch_r0 = 0;
static uint16_t g_watch_sp = 0, g_watch_bp = 0;
/* Print writes below the code/data boundary after assembler init.
   Threshold defaults to 0x5000; updated to _globals_start after assembly. */
static int      g_assembler_done  = 0;
static uint16_t g_write_threshold = 0x5000;

/* MMIO 32-bit read/write. Word-aligned addresses only (`a & 3 == 0`);
 * sub-word access is rare and the hardware decode is word-keyed too,
 * so the few callers that go through the byte/halfword paths just
 * extract the relevant bytes from a word read. */
static uint32_t mmio_read32(uint32_t a) {
    if (a == 0xFF00)                              return (uint32_t)g_cycles;
    if (a == 0xFF1C)                              return g_disp_mode;
    if (g_soc) {
        int tile = g_curcore / SOC_NCTX;
        if (a == 0xFF24) return ((uint32_t)g_tiles[tile].launch_sp << 16) | g_tiles[tile].launch_pc;
        if (a == 0xFF28) return 0;                                   /* launch never busy */
        if (a == 0xFF2C) return ((uint32_t)g_ncores << 8) | (uint32_t)tile;
    } else {
        if (a == 0xFF24)                          return (uint32_t)g_curcore;
        if (a == 0xFF28)                          return (uint32_t)g_ncores;
    }
    if (a >= 0xFF40 && a < 0xFF80 && (a & 3) == 0) return g_perfcnt[(a - 0xFF40) >> 2];
    if (a == 0xFFA0)                              return g_sdram_addr_w;
    if (a == 0xFFA4)                              return g_sdram_wdata;
    if (a == 0xFFAC)                              return g_sdram_rdata;
    if (a == 0xFFB0)                              return 0;   /* SDRAM_STATUS — never busy */
    /* Reads from unmapped MMIO addresses return zero (matches hardware) */
    return 0;
}

static void mmio_write32(uint32_t a, uint32_t v) {
    if (a == 0xFF1C) { g_disp_mode = v;                                       return; }
    if (g_soc && a == 0xFF24) {
        Tile *t = &g_tiles[g_curcore / SOC_NCTX];
        t->launch_pc = (uint16_t)(v & 0xffffu); t->launch_sp = (uint16_t)(v >> 16);
        return;
    }
    if (g_soc && a == 0xFF28) {
        int tile = g_curcore / SOC_NCTX, k = (int)(v & 7u);
        Core *c = &g_cores[tile * SOC_NCTX + k];
        if (v & 0x100u) {                       /* kill: park the context */
            if (!c->H) { c->H = 1; g_live--; }
        } else {                                /* launch at LAUNCH_PCSP, fresh registers */
            Tile *t = &g_tiles[tile];
            if (c->H) g_live++;
            memset(c->r, 0, sizeof(c->r));
            c->pc = t->launch_pc; c->sp = t->launch_sp; c->bp = t->launch_sp; c->lr = 0; c->H = 0;
        }
        return;
    }
    if (a == 0xFF20) { g_disp_lut[(v >> 24) & 0xFF] = v & 0xFFFFFFu;          return; }
    if (a == 0xFF80) { for (int i = 0; i < 16; i++) g_perfcnt[i] = 0;          return; }
    if (a == 0xFFA0) { g_sdram_addr_w = v & 0x7FFFFFu;                         return; }
    if (a == 0xFFA4) { g_sdram_wdata  = v;                                    return; }
    if (a == 0xFFA8) {
        /* Trigger READ (bit 0) or WRITE (bit 1). The hardware completes
         * asynchronously via a pbus state machine; we complete inline. */
        ensure_sdram();
        uint32_t byte_addr = g_sdram_addr_w << 2;
        if (byte_addr + 4 > SDRAM_SIZE) return;  /* out of range — silently no-op */
        if (v & 1u) {
            g_sdram_rdata = (uint32_t)sdram[byte_addr]
                          | ((uint32_t)sdram[byte_addr + 1] << 8)
                          | ((uint32_t)sdram[byte_addr + 2] << 16)
                          | ((uint32_t)sdram[byte_addr + 3] << 24);
        }
        if (v & 2u) {
            sdram[byte_addr]     = (uint8_t)g_sdram_wdata;
            sdram[byte_addr + 1] = (uint8_t)(g_sdram_wdata >> 8);
            sdram[byte_addr + 2] = (uint8_t)(g_sdram_wdata >> 16);
            sdram[byte_addr + 3] = (uint8_t)(g_sdram_wdata >> 24);
        }
        return;
    }
    /* µs counter, perfcnt slots, build ID, etc. are read-only or RO-aliased. */
}

static uint8_t mmio_read8(uint32_t a) {
    uint32_t aligned = a & ~3u;
    uint32_t shift   = (a & 3u) * 8;
    return (uint8_t)(mmio_read32(aligned) >> shift);
}

/* ──────────────────────────────────────────────────────────────────
 * 32-bit read/write through the BRAM/MMIO/SDRAM router.
 * ────────────────────────────────────────────────────────────────── */

static int addr_is_mmio(uint32_t a) {
    return a >= 0xFF00u && a <= 0xFFFFu;
}
static int addr_is_bram(uint32_t a) {
    return a < 0xFF00u;
}
static int addr_is_sdram(uint32_t a) {
    return a >= 0x10000u;
}

static void write8_inner (uint32_t a, uint8_t  v) {
    if (addr_is_bram(a)) {
        if (g_assembler_done && a < g_write_threshold)
            fprintf(stderr, "  WRITE8 to %04x = %02x  at pc=%04x sp=%04x bp=%04x r0=%08x\n",
                    (unsigned)a, v, g_watch_pc, g_watch_sp, g_watch_bp, g_watch_r0);
        g_bram[a] = v;
        return;
    }
    if (addr_is_mmio(a)) {
        /* 8-bit MMIO write: read-modify-write the enclosing word. */
        uint32_t aligned = a & ~3u;
        uint32_t shift   = (a & 3u) * 8;
        uint32_t cur     = mmio_read32(aligned);
        cur = (cur & ~(0xFFu << shift)) | ((uint32_t)v << shift);
        mmio_write32(aligned, cur);
        return;
    }
    if (addr_is_sdram(a)) { ensure_sdram(); sdram[sdram_chip_byte(a)] = v; return; }
}

static void write16_inner(uint32_t a, uint16_t v) {
    write8_inner(a,     (uint8_t)v);
    write8_inner(a + 1, (uint8_t)(v >> 8));
}

static void write32_inner(uint32_t a, uint32_t v) {
    if (addr_is_mmio(a) && (a & 3u) == 0) { mmio_write32(a, v); return; }
    write16_inner(a,     (uint16_t)v);
    write16_inner(a + 2, (uint16_t)(v >> 16));
}

/* Every architectural store goes through these; with -retire each one is
 * recorded so the retirement line can list it. */
static FILE *g_retire_out = NULL;
static struct { uint32_t a, v; int n; } g_mw[16];
static int g_nmw = 0;
static void mw_log(uint32_t a, uint32_t v, int n) { if (g_retire_out && g_nmw < 16) { g_mw[g_nmw].a = a; g_mw[g_nmw].v = v; g_mw[g_nmw].n = n; g_nmw++; } }
static void write8 (uint32_t a, uint8_t  v) { mw_log(a, v, 1); write8_inner(a, v); }
static void write16(uint32_t a, uint16_t v) { mw_log(a, v, 2); write16_inner(a, v); }
static void write32(uint32_t a, uint32_t v) { mw_log(a, v, 4); write32_inner(a, v); }

static uint8_t read8(uint32_t a) {
    if (addr_is_bram(a))   return g_bram[a];
    if (addr_is_mmio(a))   return mmio_read8(a);
    if (addr_is_sdram(a))  { ensure_sdram(); return sdram[sdram_chip_byte(a)]; }
    return 0;
}

static uint16_t read16(uint32_t a) {
    return (uint16_t)read8(a) | ((uint16_t)read8(a + 1) << 8);
}

static uint32_t read32(uint32_t a) {
    if (addr_is_mmio(a) && (a & 3u) == 0) return mmio_read32(a);
    return (uint32_t)read16(a) | ((uint32_t)read16(a + 2) << 16);
}

/* CPU4 alignment checking. Hardware doesn't (yet) raise an exception
 * on misaligned multi-byte access — see abi.md §3 — so this is the
 * only line of defence on this side. The address is the full 32-bit
 * data-port address; pc stays 16-bit (code lives in BRAM). */
static void check_align16(uint32_t addr, uint16_t pc) {
    if (addr & 1u) {
        fprintf(stderr, "CPU4 alignment error: 16-bit access to unaligned address 0x%08x at pc=0x%04x\n",
                (unsigned)addr, pc);
        exit(1);
    }
}
static void check_align32(uint32_t addr, uint16_t pc) {
    if (addr & 3u) {
        fprintf(stderr, "CPU4 alignment error: 32-bit access to unaligned address 0x%08x at pc=0x%04x\n",
                (unsigned)addr, pc);
        exit(1);
    }
}

/* ------------------------------------------------------------------ */
/* Symbol table                                                         */
/* ------------------------------------------------------------------ */

#define MAX_SYMS 16384      /* inlining multiplies block labels */
#define MAX_NAME 128
#define SYM_HASH 32768      /* open-addressed index into syms[], power of 2 */

typedef struct { char name[MAX_NAME]; uint16_t addr; } Sym;
static Sym syms[MAX_SYMS];
static int nsyms = 0;
static int sym_hash[SYM_HASH];   /* syms index + 1; 0 = empty */

static unsigned sym_hash_of(const char *n)
{
    unsigned h = 2166136261u;
    while (*n) { h ^= (unsigned char)*n++; h *= 16777619u; }
    return h;
}

static int find_sym(const char *n)
{
    for (unsigned i = sym_hash_of(n) & (SYM_HASH - 1); sym_hash[i]; i = (i + 1) & (SYM_HASH - 1))
        if (strcmp(syms[sym_hash[i] - 1].name, n) == 0) return sym_hash[i] - 1;
    return -1;
}

static void add_sym(const char *n, uint16_t addr)
{
    int i = find_sym(n);
    if (i >= 0) { syms[i].addr = addr; return; }
    if (nsyms >= MAX_SYMS) { fprintf(stderr, "too many symbols\n"); exit(1); }
    strncpy(syms[nsyms].name, n, MAX_NAME-1);
    syms[nsyms].name[MAX_NAME-1] = '\0';
    syms[nsyms].addr = addr;
    unsigned h = sym_hash_of(syms[nsyms].name) & (SYM_HASH - 1);
    while (sym_hash[h]) h = (h + 1) & (SYM_HASH - 1);
    sym_hash[h] = nsyms + 1;
    nsyms++;
}

static uint16_t lookup_sym(const char *n)
{
    int i = find_sym(n);
    if (i >= 0) return syms[i].addr;
    const char *op = strpbrk(n + 1, "+-");          /* label+offset, label-offset */
    if (op && (size_t)(op - n) < MAX_NAME) {
        char base[MAX_NAME];
        memcpy(base, n, op - n); base[op - n] = '\0';
        char *e; long off = strtol(op, &e, 0);
        i = find_sym(base);
        if (i >= 0 && *e == '\0') return (uint16_t)(syms[i].addr + off);
    }
    fprintf(stderr, "undefined symbol: %s\n", n); exit(1);
}




/* Split on commas and/or whitespace — for CPU4 operand lists. */
static int tokenize4(const char *s, char toks[][MAX_NAME], int max)
{
    int n = 0;
    const char *p = s;
    while (*p && n < max) {
        while (*p && (isspace((unsigned char)*p) || *p == ',')) p++;
        if (!*p) break;
        const char *start = p;
        while (*p && !isspace((unsigned char)*p) && *p != ',') p++;
        size_t len = (size_t)(p - start);
        if (len >= MAX_NAME) len = MAX_NAME - 1;
        strncpy(toks[n], start, len);
        toks[n][len] = '\0';
        n++;
    }
    return n;
}

/* ------------------------------------------------------------------ */
/* Assembler                                                            */
/* ------------------------------------------------------------------ */

/* Trim trailing whitespace in-place. */
static void rtrim(char *s)
{
    char *p = s + strlen(s);
    while (p > s && isspace((unsigned char)p[-1])) *--p = '\0';
}

/* Strip comment (semicolon to end of line). */
static void strip_comment(char *s)
{
    char *p = s;
    while (*p && *p != ';') p++;
    *p = '\0';
    rtrim(s);
}


/* Parse a token value: hex/decimal integer or label name.
   On pass 1, labels resolve to 0. */
static uint32_t parse_tok(const char *s, int pass)
{
    char *end;
    long v = strtol(s, &end, 0);
    if (end != s && (*end == '\0' || isspace((unsigned char)*end))) {
        return (uint32_t)v;
    }
    if (pass == 2) return lookup_sym(s);
    return 0;
}

/* ------------------------------------------------------------------ */
/* Float helpers                                                        */
/* ------------------------------------------------------------------ */

#include "cpu4/fpu_model.h"

/* ------------------------------------------------------------------ */
/* ISAs: tables and executors generated from <arch>/isa.py              */
/* ------------------------------------------------------------------ */
static int g_gen_bad = 0;                 /* set by a generated step on an unknown instruction */
static const char *g_arch_name = "cpu4";
#include "isatool/exec_common.h"
#include "isatool/arches.h"               /* every <arch>/isa_table_c.h and exec_gen.h */
static const IsaArch *g_arch = &isa_arches[0];

static const IsaInstr *isa_find(const char *n)
{
    for (const IsaInstr *in = g_arch->instrs; in->name; in++)
        if (strcmp(in->name, n) == 0) return in;
    return NULL;
}

static int isa_parse_reg(const char *s)
{
    if (s[0] != 'r' || !isdigit((unsigned char)s[1])) return -1;
    char *e; long v = strtol(s + 1, &e, 10);
    return (*e == '\0' && v >= 0 && v < g_arch->ngpr) ? (int)v : -1;
}

static void asm_fail(int line, const char *fmt, ...)
{
    va_list ap; va_start(ap, fmt);
    fprintf(stderr, "asm error (line %d): ", line);
    vfprintf(stderr, fmt, ap); fputc('\n', stderr);
    va_end(ap); exit(1);
}

/* Encode one instruction from its operand tokens using the ISA table: the
 * word starts as the instruction's fixed bits and each operand's value is
 * range-checked and scattered into its field. Labels are resolved in pass 2. */
static void isa_encode(const IsaInstr *in, char ops[][MAX_NAME], int nops, int addr, int pass, int line, uint8_t out[4])
{
    uint32_t w = in->match;
    if (pass == 2 && nops != in->nops)
        asm_fail(line, "%s takes %d operand(s), got %d", in->name, in->nops, nops);
    for (int k = 0; k < in->nops; k++) {
        const IsaOp *o = &in->ops[k];
        const char *t = k < nops ? ops[k] : "0";
        int64_t v;
        if (o->kind == ISA_REG) {
            int r = isa_parse_reg(t);
            if (r < 0) {
                if (pass == 2) asm_fail(line, "%s operand %d: expected a register r0..r%d, got '%s'", in->name, k + 1, g_arch->ngpr - 1, t);
                r = 0;
            }
            v = r;
        } else {
            char *e; long n = strtol(t, &e, 0);
            if (e != t && *e == '\0') v = n;
            else if (o->kind == ISA_RAW || o->kind == ISA_ABS || o->kind == ISA_PCREL) v = (pass == 2) ? (int64_t)lookup_sym(t) : 0;
            else {
                if (pass == 2) asm_fail(line, "%s operand %d: expected a number, got '%s'", in->name, k + 1, t);
                v = 0;
            }
            if (o->kind == ISA_PCREL) v = (pass == 2) ? v - (addr + in->len) : 0;
            if (o->kind == ISA_BYTES) {
                if (pass == 2 && (v % o->scale)) asm_fail(line, "%s operand %d: byte offset %lld is not a multiple of %d at 0x%04x", in->name, k + 1, (long long)v, o->scale, addr);
                v /= o->scale;
            }
            int64_t lo = -(1LL << (o->bits - 1)), hi = (1LL << (o->bits - 1)) - 1;
            if (o->kind == ISA_UIMM) { lo = 0; hi = (1LL << o->bits) - 1; }
            if (o->kind == ISA_RAW || o->kind == ISA_ABS) hi = (1LL << o->bits) - 1;
            if (pass == 2 && (v < lo || v > hi))
                asm_fail(line, "%s operand %d value %lld out of range [%lld..%lld] at 0x%04x", in->name, k + 1,
                         (long long)(v * o->scale), (long long)(lo * o->scale), (long long)(hi * o->scale), addr);
        }
        uint32_t field = (uint32_t)v & (o->bits >= 32 ? 0xffffffffu : ((1u << o->bits) - 1));
        int left = o->bits;
        for (int r = 0; r < o->nruns; r++) {
            left -= o->width[r];
            w |= ((field >> left) & ((1u << o->width[r]) - 1)) << o->shift[r];
        }
    }
    for (int k = 0; k < in->len; k++) out[k] = (uint8_t)(w >> (8 * (in->len - 1 - k)));
}

static float  bits2float(uint32_t b) { float f; memcpy(&f, &b, 4); return f; }
static uint32_t float2bits(float f)  { uint32_t b; memcpy(&b, &f, 4); return b; }

/* ------------------------------------------------------------------ */
/* CPU4 assembler                                                       */
/* ------------------------------------------------------------------ */

static void assemble_cpu4(const char *src)
{
    size_t srclen = strlen(src);
    char *buf = malloc(srclen + 2);
    if (!buf) { fprintf(stderr, "oom\n"); exit(1); }
    memcpy(buf, src, srclen + 1);

    for (int pass = 1; pass <= 2; pass++) {
        int cur = 0;
        int lineno = 0;
        char last_label[MAX_NAME] = "<none>";  /* named in alignment errors */
        char *p = buf;
        while (*p) {
            char *eol = strchr(p, '\n');
            char line[512];
            size_t linelen;
            if (eol) {
                linelen = (size_t)(eol - p);
                if (linelen >= sizeof(line)) linelen = sizeof(line)-1;
                strncpy(line, p, linelen);
                line[linelen] = '\0';
                p = eol + 1;
            } else {
                strncpy(line, p, sizeof(line)-1);
                line[sizeof(line)-1] = '\0';
                p += strlen(p);
            }
            int cur_lineno = lineno++;

            /* Debug directive "; @src FILE LINE" — recorded against the
             * NEXT emitted byte address (cur). Parsed before strip_comment
             * swallows the semicolon. */
            if (pass == 2) {
                const char *sp = line;
                while (*sp == ' ' || *sp == '\t') sp++;
                if (sp[0] == ';') {
                    sp++;
                    while (*sp == ' ' || *sp == '\t') sp++;
                    if (strncmp(sp, "@src", 4) == 0 &&
                        (sp[4] == ' ' || sp[4] == '\t')) {
                        sp += 5;
                        while (*sp == ' ' || *sp == '\t') sp++;
                        char file[128];
                        size_t fi = 0;
                        while (*sp && *sp != ' ' && *sp != '\t' &&
                               fi + 1 < sizeof(file))
                            file[fi++] = *sp++;
                        file[fi] = '\0';
                        while (*sp == ' ' || *sp == '\t') sp++;
                        int ln = (int)strtol(sp, NULL, 0);
                        if (fi > 0 && ln > 0)
                            add_srcloc((uint16_t)cur, file, ln);
                    }
                }
            }

            strip_comment(line);
            if (line[0] == '\0') continue;

            char *lp = line;

            /* Section directive */
            if (lp[0] == '.') {
                char *eq = strchr(lp, '=');
                if (eq) cur = (int)strtol(eq+1, NULL, 0);
                continue;
            }

            /* Label */
            if (!isspace((unsigned char)lp[0])) {
                char *colon = strchr(lp, ':');
                if (colon) {
                    char lname[MAX_NAME];
                    size_t nlen = (size_t)(colon - lp);
                    if (nlen >= MAX_NAME) nlen = MAX_NAME-1;
                    strncpy(lname, lp, nlen);
                    lname[nlen] = '\0';
                    for (char *c = lname; *c; c++)
                        if (isspace((unsigned char)*c)) { *c = '\0'; break; }
                    if (pass == 1) add_sym(lname, (uint16_t)cur);
                    strncpy(last_label, lname, MAX_NAME-1);
                    last_label[MAX_NAME-1] = '\0';
                    lp = colon + 1;
                    while (*lp && isspace((unsigned char)*lp)) lp++;
                    if (*lp == '\0') continue;
                }
            } else {
                while (*lp && isspace((unsigned char)*lp)) lp++;
                if (*lp == '\0') continue;
            }

            /* Split mnemonic from operand string */
            char mnem[MAX_NAME] = {0};
            const char *mp = lp;
            while (*mp && !isspace((unsigned char)*mp)) mp++;
            size_t mlen = (size_t)(mp - lp);
            if (mlen >= MAX_NAME) mlen = MAX_NAME-1;
            strncpy(mnem, lp, mlen);
            while (*mp && isspace((unsigned char)*mp)) mp++;

            /* Tokenize comma-separated operands */
            char ops[8][MAX_NAME];
            int nops = tokenize4(mp, ops, 8);

            /* Directives */
            if (strcmp(mnem, "align") == 0) {
                /* CPU4: align to 4-byte boundary (matches cpu4/assembler.py behaviour) */
                while (cur & 3) { if (pass == 2) write8((uint16_t)cur, 0); cur++; }
                continue;
            }
            if (strcmp(mnem, "allocb") == 0) {
                int n = (nops > 0) ? (int)strtol(ops[0], NULL, 0) : 0;
                cur += n; continue;
            }
            if (strcmp(mnem, "allocw") == 0) {
                int n = (nops > 0) ? (int)strtol(ops[0], NULL, 0) : 0;
                if (cur & 1) cur++;
                cur += n * 2; continue;
            }
            if (strcmp(mnem, "byte") == 0) {
                for (int i = 0; i < nops; i++) {
                    if (pass == 2) write8((uint16_t)cur, (uint8_t)parse_tok(ops[i], pass));
                    cur++;
                }
                continue;
            }
            if (strcmp(mnem, "word") == 0) {
                if (pass == 2 && (cur & 1)) {
                    fprintf(stderr, "asm error (line %d): word directive at unaligned address 0x%04x (after label %s); insert 'align' before the label (docs/issues/0001)\n",
                            cur_lineno+1, (unsigned)cur, last_label);
                    exit(1);
                }
                for (int i = 0; i < nops; i++) {
                    if (pass == 2) write16((uint16_t)cur, (uint16_t)parse_tok(ops[i], pass));
                    cur += 2;
                }
                continue;
            }
            if (strcmp(mnem, "long") == 0) {
                if (pass == 2 && (cur & 3)) {
                    fprintf(stderr, "asm error (line %d): long directive at unaligned address 0x%04x (after label %s); insert 'align' before the label (docs/issues/0001)\n",
                            cur_lineno+1, (unsigned)cur, last_label);
                    exit(1);
                }
                for (int i = 0; i < nops; i++) {
                    if (pass == 2) write32((uint16_t)cur, parse_tok(ops[i], pass));
                    cur += 4;
                }
                continue;
            }
            if (strcmp(mnem, "clearmem") == 0) continue;

            /* Pseudo-ops: operand permutations of a real instruction (ISA table). */
            char real_mnem[MAX_NAME];
            strncpy(real_mnem, mnem, MAX_NAME-1);
            real_mnem[MAX_NAME-1] = '\0';
            for (const IsaPseudo *ps = g_arch->pseudos; ps->name; ps++) {
                if (strcmp(ps->name, mnem) != 0) continue;
                char src[8][MAX_NAME];
                memcpy(src, ops, sizeof src);
                for (int k = 0; k < ps->n; k++) {
                    if (ps->src[k] >= nops) asm_fail(cur_lineno+1, "%s needs more operands", mnem);
                    strcpy(ops[k], src[ps->src[k]]);
                }
                nops = ps->n;
                strcpy(real_mnem, ps->real);
                break;
            }

            const IsaInstr *instr = isa_find(real_mnem);
            if (!instr) {
                fprintf(stderr, "%s asm: unknown mnemonic: %s\n", g_arch->name, real_mnem);
                exit(1);
            }
            if (pass == 2 && g_profile) prof_lineno[cur] = (int16_t)cur_lineno;
            uint8_t enc[4];
            isa_encode(instr, ops, nops, cur, pass, cur_lineno+1, enc);
            if (pass == 2)
                for (int k = 0; k < instr->len; k++) write8((uint16_t)(cur + k), enc[k]);
            if (pass == 2 && g_imap) fprintf(g_imap, "%04x %d %s\n", cur & 0xffff, instr->len, instr->name);
            cur += instr->len;
        }
        if (pass == 2 && (uint16_t)cur > g_asm_end)
            g_asm_end = (uint16_t)cur;
    }
    free(buf);
}

/* ------------------------------------------------------------------ */
/* Disassembler / dump                                                   */
/* ------------------------------------------------------------------ */


/* Find a symbol name at a given address (first match) */
static const char *sym_at_addr(uint16_t addr)
{
    for (int i = 0; i < nsyms; i++)
        if (syms[i].addr == addr) return syms[i].name;
    return NULL;
}

/* Find a symbol name for a branch/jump target; returns "" if none */
static const char *sym_for_target(uint16_t addr)
{
    const char *s = sym_at_addr(addr);
    return s ? s : "";
}

static int sym_cmp(const void *a, const void *b)
{
    const Sym *sa = (const Sym *)a;
    const Sym *sb = (const Sym *)b;
    if (sa->addr != sb->addr) return (int)sa->addr - (int)sb->addr;
    return strcmp(sa->name, sb->name);
}


static void print_dump(uint16_t code_end, uint16_t data_end, const char *path)
{
    FILE *out = fopen(path, "w");
    if (!out) { perror(path); return; }

    /* --- Symbol table --- */
    Sym *sorted = malloc((size_t)nsyms * sizeof(Sym));
    if (!sorted) { fprintf(stderr, "oom\n"); return; }
    memcpy(sorted, syms, (size_t)nsyms * sizeof(Sym));
    qsort(sorted, (size_t)nsyms, sizeof(Sym), sym_cmp);

    fprintf(out, "=== Symbol Table (%d symbols) ===\n", nsyms);
    for (int i = 0; i < nsyms; i++)
        fprintf(out, "  %04x  %s\n", sorted[i].addr, sorted[i].name);
    fprintf(out, "\n");
    free(sorted);

    /* --- Code disassembly --- */
    fprintf(out, "=== Code (0x0000 - 0x%04x) ===\n\n", code_end ? code_end - 1 : 0);

    uint16_t pc = 0;
    while (pc < code_end) {
        /* Print all labels at this address */
        for (int i = 0; i < nsyms; i++)
            if (syms[i].addr == pc) fprintf(out, "%s:\n", syms[i].name);

        const IsaInstr *in = NULL;
        uint32_t w = 0;
        for (const IsaInstr *c = g_arch->instrs; c->name; c++) {
            uint32_t x = 0;
            for (int k = 0; k < c->len; k++) x = (x << 8) | mem[(uint16_t)(pc + k)];
            if ((x & c->mask) == c->match) { in = c; w = x; break; }
        }
        int len = in ? in->len : 1;
        char hexbytes[16];
        int hp = 0;
        for (int k = 0; k < len; k++)
            hp += snprintf(hexbytes + hp, sizeof hexbytes - hp, k ? " %02x" : "%02x", mem[(uint16_t)(pc + k)]);
        const char *mnem = in ? in->name : ".byte";
        char operands[96] = "";
        if (!in) snprintf(operands, sizeof operands, "???");
        else {
            int op = 0;
            for (int k = 0; k < in->nops; k++) {
                const IsaOp *o = &in->ops[k];
                uint32_t f = 0;
                for (int r = 0; r < o->nruns; r++) f = (f << o->width[r]) | ((w >> o->shift[r]) & ((1u << o->width[r]) - 1));
                int32_t sv = (int32_t)(f << (32 - o->bits)) >> (32 - o->bits);
                char buf[48];
                const char *sym;
                switch (o->kind) {
                case ISA_REG:  snprintf(buf, sizeof buf, "r%u", f); break;
                case ISA_UIMM: snprintf(buf, sizeof buf, "%u", f); break;
                case ISA_RAW:  snprintf(buf, sizeof buf, "0x%0*x", (o->bits + 3) / 4, f); break;
                case ISA_ABS:
                    sym = sym_for_target((uint16_t)f);
                    if (*sym) snprintf(buf, sizeof buf, "%s", sym); else snprintf(buf, sizeof buf, "0x%04x", f);
                    break;
                case ISA_PCREL: {
                    uint16_t t = (uint16_t)((int)(pc + len) + sv);
                    sym = sym_for_target(t);
                    if (*sym) snprintf(buf, sizeof buf, "%s", sym); else snprintf(buf, sizeof buf, "0x%04x", t);
                    break; }
                default:       snprintf(buf, sizeof buf, "%d", (int)(sv * o->scale)); break;
                }
                op += snprintf(operands + op, sizeof operands - op, "%s%s", k ? ", " : "", buf);
            }
        }

        fprintf(out, "  %04x  %-9s %-7s %s\n", (unsigned)pc, hexbytes, mnem ? mnem : "???", operands);
        pc += (uint16_t)len;
    }

    /* --- Data section --- */
    if (data_end > code_end) {
        fprintf(out, "\n=== Data (0x%04x - 0x%04x) ===\n\n", code_end, data_end - 1);
        uint16_t addr = code_end;
        while (addr < data_end) {
            /* Print all labels at this address */
            for (int i = 0; i < nsyms; i++)
                if (syms[i].addr == addr) fprintf(out, "%s:\n", syms[i].name);

            /* Print up to 16 bytes per row */
            int row_len = data_end - addr;
            if (row_len > 16) row_len = 16;

            /* But break at the next symbol boundary */
            for (int i = 0; i < nsyms; i++) {
                if (syms[i].addr > addr && syms[i].addr < addr + row_len)
                    row_len = syms[i].addr - addr;
            }

            fprintf(out, "  %04x ", (unsigned)addr);
            for (int j = 0; j < row_len; j++)
                fprintf(out, " %02x", mem[(uint16_t)(addr + j)]);
            /* Pad to align ASCII column */
            for (int j = row_len; j < 16; j++)
                fprintf(out, "   ");
            fprintf(out, "  |");
            for (int j = 0; j < row_len; j++) {
                uint8_t c = mem[(uint16_t)(addr + j)];
                fprintf(out, "%c", (c >= 0x20 && c < 0x7f) ? c : '.');
            }
            fprintf(out, "|\n");
            addr += (uint16_t)row_len;
        }
    }

    fprintf(out, "\n");
    fclose(out);
}

/* ------------------------------------------------------------------ */
/* CPU4 sign-extension helpers                                          */
/* ------------------------------------------------------------------ */

#define MAX_STEPS 100000000
static long long g_max_steps = MAX_STEPS;


/* ------------------------------------------------------------------ */
/* CPU4 executor                                                        */
/* ------------------------------------------------------------------ */

static FILE *g_trace_out = NULL;
static int   g_last_len = 1;          /* length of the instruction just executed */


/* -retire: one line per retired instruction, listing everything it changed.
 * The format is the contract a retirement port on the RTL will match. */
static void retire_line(int ci, uint16_t pc0, int len, const uint32_t *r0, uint16_t sp0, uint16_t bp0, uint16_t lr0, const Core *cc) {
    FILE *f = g_retire_out;
    if (g_ncores > 1) fprintf(f, "c%d ", ci);
    fprintf(f, "%04x ", pc0);
    for (int i = 0; i < len; i++) fprintf(f, "%02x", read8((uint16_t)(pc0 + i)));
    for (int i = 0; i < g_arch->ngpr; i++) if (cc->r[i] != r0[i]) fprintf(f, " r%d=%08x", i, cc->r[i]);
    if (cc->sp != sp0) fprintf(f, " sp=%04x", cc->sp);
    if (cc->bp != bp0) fprintf(f, " bp=%04x", cc->bp);
    if (cc->lr != lr0) fprintf(f, " lr=%04x", cc->lr);
    for (int i = 0; i < g_nmw; i++) fprintf(f, " m%d[%08x]=%0*x", g_mw[i].n, g_mw[i].a, g_mw[i].n * 2, g_mw[i].v);
    if (cc->H) fprintf(f, " halt");
    fprintf(f, " >%04x\n", cc->pc);
}

static void run_cpu4(void)
{
    g_cycles = 0;

    enum { TRACE_N4 = 32 };
    struct { uint16_t t_pc; uint8_t t_op; uint32_t t_r0; uint16_t t_sp, t_bp; int t_core; } trace[TRACE_N4];
    memset(trace, 0, sizeof(trace));
    int trace_idx = 0;

    g_live = 0;
    for (int i = 0; i < g_nunits; i++) if (!g_cores[i].H) g_live++;

/* The executor body below reads/writes core state through these
 * aliases; `cc` is the core being stepped this iteration. The macros
 * are #undef'd right after the loop. */
#define r  (cc->r)
#define sp (cc->sp)
#define bp (cc->bp)
#define lr (cc->lr)
#define pc (cc->pc)
#define H  (cc->H)

    for (long long step = 0; step < g_max_steps && g_live > 0; step++, g_cycles++) {
      for (int ci = 0; ci < g_nunits; ci++) {
        Core *cc = &g_cores[ci];
        if (H) continue;
        g_curcore = ci;
        g_bram    = cc->bram;

        const uint16_t step_pc = pc;
        uint32_t r_before[ISA_MAX_GPR]; uint16_t sp_before = sp, bp_before = bp, lr_before = lr;
        if (g_retire_out || g_trace_out) { memcpy(r_before, r, sizeof r_before); g_nmw = 0; }
        if (g_profile || g_pccount_out) prof_count[step_pc]++;
        g_watch_pc = step_pc; g_watch_r0 = r[0]; g_watch_sp = sp; g_watch_bp = bp;
        trace[trace_idx].t_pc = step_pc; trace[trace_idx].t_op = read8(step_pc);
        trace[trace_idx].t_r0 = r[0]; trace[trace_idx].t_sp = sp; trace[trace_idx].t_bp = bp;
        trace[trace_idx].t_core = ci;
        trace_idx = (trace_idx + 1) % TRACE_N4;

        /* Fetch, decode and execute: generated from cpu4/isa.py (cpu4/exec_gen.h). */
        g_gen_bad = 0;
        g_last_len = g_arch->step(cc);

        if (g_gen_bad) {
            fprintf(stderr, "Last %d instructions:\n", TRACE_N4);
            for (int _ti = 0; _ti < TRACE_N4; _ti++) {
                int _idx = (trace_idx + _ti) % TRACE_N4;
                fprintf(stderr, "  c%d [%04x] op=%02x r0=%08x sp=%04x bp=%04x\n",
                        trace[_idx].t_core, trace[_idx].t_pc, trace[_idx].t_op,
                        trace[_idx].t_r0, trace[_idx].t_sp, trace[_idx].t_bp);
            }
        }
        if (g_trace_out) {      /* state before the instruction, as the trace has always shown it */
            char ins_buf[8]; int p = 0;
            for (int i = 0; i < g_last_len && i < 3; i++)
                p += snprintf(ins_buf + p, sizeof(ins_buf) - p, "%02x", read8((uint16_t)(step_pc + i)));
            if (g_ncores > 1) fprintf(g_trace_out, "c%d ", ci);
            fprintf(g_trace_out, "pc=%04x ins=%-6s", step_pc, ins_buf);
            for (int i = 0; i < g_arch->ngpr; i++) fprintf(g_trace_out, " r%d=%08x", i, r_before[i]);
            fprintf(g_trace_out, " sp=%04x bp=%04x lr=%04x\n", sp_before, bp_before, lr_before);
        }
        sp &= 0xffff; bp &= 0xffff; lr &= 0xffff; pc &= 0xffff;
        /* The ISA's invariants (SP/BP alignment on CPU4) are checked by the generated step. */
        if (g_retire_out) retire_line(ci, step_pc, g_last_len, r_before, sp_before, bp_before, lr_before, cc);

        cc->insns++;
        if (H) g_live--;
      }
    }

#undef r
#undef sp
#undef bp
#undef lr
#undef pc
#undef H

    /* Single-core output stays byte-compatible with the historical
     * format (test harnesses parse it). Multi-core prints one line per
     * core (cycles: = that core's executed instructions) plus a
     * summary tick count. */
    for (int ci = 0; ci < g_nunits; ci++) {
        Core *c = &g_cores[ci];
        if (g_soc) { if (ci % SOC_NCTX && c->H && c->insns == 0) continue;   /* never-launched context */
                     printf("core%d.ctx%d ", ci / SOC_NCTX, ci % SOC_NCTX); }
        else if (g_ncores > 1) printf("core%d ", ci);
        for (int i = 0; i < g_arch->ngpr; i++) printf("r%d:%08x ", i, c->r[i]);
        printf("sp:%04x bp:%04x lr:%04x pc:%04x H:%x cycles:%llu\n",
               c->sp, c->bp, c->lr, c->pc, c->H,
               (unsigned long long)(g_ncores > 1 ? c->insns : g_cycles));
    }
    if (g_ncores > 1)
        printf("ticks:%llu\n", (unsigned long long)g_cycles);
}

/* ------------------------------------------------------------------ */
/* CPU                                                                  */
/* ------------------------------------------------------------------ */

/* ------------------------------------------------------------------ */
/* Main                                                                 */
/* ------------------------------------------------------------------ */

static char *read_file(const char *path)
{
    FILE *f = fopen(path, "r");
    if (!f) { perror(path); exit(1); }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc((size_t)len + 2);
    if (!buf) { fprintf(stderr, "oom\n"); exit(1); }
    size_t n = fread(buf, 1, (size_t)len, f);
    buf[n] = '\0';
    fclose(f);
    return buf;
}

/* Dump the 80x30 ASCII framebuffer at 0xF000 to stderr.
 * Each row is printed as up to 80 chars, trimmed of trailing whitespace, + '\n'.
 * Non-printable bytes (including \0) render as ' '. */
static void dump_framebuffer(void)
{
    for (int row = 0; row < 30; row++) {
        char line[81];
        for (int col = 0; col < 80; col++) {
            uint8_t b = g_cores[0].bram[0xF000 + row * 80 + col];
            line[col] = (b >= 32 && b < 127) ? (char)b : ' ';
        }
        int end = 80;
        while (end > 0 && line[end - 1] == ' ') end--;
        line[end] = '\0';
        fprintf(stderr, "%s\n", line);
    }
}

/* Dump the bitmap framebuffer to a binary PPM (P6) file. The framebuffer
 * lives in SDRAM at chip byte 0x10000 (= word 0x4000); resolution and
 * pixel format come from g_disp_mode (the DISP_MODE MMIO register):
 *
 *   bit 0 (mode_320)   → 320x240 source resolution (vs 640x480)
 *   bit 1 (mode_8bpp)  → 8-bit indexed (vs 32bpp XRGB), 4 indices per pbus
 *                        word, indices look up an XRGB triple in g_disp_lut
 *
 * In all modes the source pixel format on disk is XRGB; bits[23:16]=R,
 * [15:8]=G, [7:0]=B. The PPM is written at the *fb resolution* (no pixel
 * doubling in the output) — viewers can scale. */
static void dump_bitmap_fb(const char *path)
{
    if (!sdram) {
        fprintf(stderr, "sim_c: -fb requested but SDRAM was never allocated; nothing to dump\n");
        return;
    }
    int mode_320  = (g_disp_mode & 0x1u) != 0;
    int mode_8bpp = (g_disp_mode & 0x2u) != 0;
    int w = mode_320 ? 320 : 640;
    int h = mode_320 ? 240 : 480;

    FILE *f = fopen(path, "wb");
    if (!f) { perror(path); return; }
    fprintf(f, "P6\n%d %d\n255\n", w, h);

    uint32_t fb_base = 0x10000;            /* SDRAM byte 0x10000 = word 0x4000 */
    for (int y = 0; y < h; y++) {
        for (int x = 0; x < w; x++) {
            uint32_t xrgb;
            if (mode_8bpp) {
                /* Each fb byte indexes the LUT. Pixels pack 4 per word
                 * with `i mod 4` selecting the byte. */
                uint32_t idx = sdram[fb_base + y * w + x];
                xrgb = g_disp_lut[idx];
            } else {
                /* 32bpp XRGB packed in one pbus word */
                uint32_t off = fb_base + (uint32_t)(y * w + x) * 4u;
                xrgb = (uint32_t)sdram[off]
                     | ((uint32_t)sdram[off + 1] << 8)
                     | ((uint32_t)sdram[off + 2] << 16)
                     | ((uint32_t)sdram[off + 3] << 24);
            }
            uint8_t r = (uint8_t)(xrgb >> 16);
            uint8_t g = (uint8_t)(xrgb >> 8);
            uint8_t b = (uint8_t)(xrgb);
            fputc(r, f); fputc(g, f); fputc(b, f);
        }
    }
    fclose(f);
    fprintf(stderr, "sim_c: wrote %dx%d %s framebuffer to %s\n",
            w, h, mode_8bpp ? "8bpp" : "32bpp", path);
}

static const char *usage_text =
"usage: sim_c [options] file.s\n"
"\n"
"Assemble and run a program for one of the ISAs sim_c is built with\n"
"(every <arch>/isa.py in the toolchain; see isatool/arches.h).\n"
"\n"
"Options:\n"
"  -h, --help         Show this help and exit\n"
"  -trace FILE        Write a per-instruction execution trace to FILE\n"
"  -arch NAME         ISA to assemble and run (default cpu4; e.g. cpu5)\n"
"  -maxsteps N        Override the default instruction-step cap\n"
"                     (with -cores: N is ticks; each live core runs one\n"
"                     instruction per tick)\n"
"  -load ADDR FILE    Before running, copy FILE's bytes into SDRAM at ADDR\n"
"                     (0x10000 or above; may be repeated). For data too big\n"
"                     for the 64 KB image, e.g. a guest kernel\n"
"  -cores N           Simulate N CPU4 cores (default 1, max 1024). Every\n"
"                     core boots the same image at pc=0 with a private\n"
"                     64 KB BRAM; SDRAM and the display are shared.\n"
"                     Software reads CORE_ID at MMIO 0xFF24 (NCORES at\n"
"                     0xFF28) and branches. Deterministic round-robin.\n"
"  -soc               Model the KU5P cpu4_socN tile: each core is a barrel of 8\n"
"                     contexts sharing its BRAM (context launch via 0xFF24/0xFF28,\n"
"                     CORE_ID = {NCORES, id} at 0xFF2C) instead of the legacy\n"
"                     CORE_ID/NCORES words. Contexts 1..7 start parked.\n"
"  -dump FILE         Assemble and write a bytecode dump; do not execute\n"
"  -dumpfb            After running, dump the legacy 80x30 text framebuffer at 0xF000\n"
"  -fb FILE           After running, dump the bitmap framebuffer to FILE.ppm\n"
"                     (640x480 32bpp by default; honors DISP_MODE bits — 320x240 / 8bpp).\n"
"  -profile           Collect and print a per-source-line execution profile\n"
"  -pccount FILE      Write each executed pc with its execution count (tools/isaprof.py)\n"
"  -imap FILE         Write each assembled instruction's address, length and mnemonic\n"
"  -retire FILE       Write one line per retired instruction: pc, bytes, every\n"
"                     register and memory change, next pc\n"
"  -linemap FILE      Assemble and write a PC->source JSON map; do not execute\n"
"  -hex FILE          Assemble and write whitespace-delimited hex bytes; do not execute\n"
"\n"
"-dump, -linemap, and -hex stop after assembly and produce no runtime output.\n";

static void print_usage(FILE *f) { fputs(usage_text, f); }

int main(int argc, char **argv)
{
    int dumpfb = 0;
    const char *trace_path = NULL;
    const char *filename = NULL;
    const char *fb_out = NULL;
    long long maxsteps_override = 0;
    enum { MAX_LOADS = 16 };
    const char *load_path[MAX_LOADS]; uint32_t load_addr[MAX_LOADS]; int nloads = 0;

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0) {
            print_usage(stdout);
            return 0;
        }
        else if (strcmp(argv[i], "-trace") == 0 && i+1 < argc) trace_path = argv[++i];
        else if (strcmp(argv[i], "-profile") == 0) g_profile = 1;
        else if (strcmp(argv[i], "-pccount") == 0 && i+1 < argc) g_pccount_out = argv[++i];
        else if (strcmp(argv[i], "-imap") == 0 && i+1 < argc) {
            g_imap = fopen(argv[++i], "w");
            if (!g_imap) { perror(argv[i]); return 1; }
        }
        else if (strcmp(argv[i], "-retire") == 0 && i+1 < argc) {
            g_retire_out = fopen(argv[++i], "w");
            if (!g_retire_out) { perror(argv[i]); return 1; }
        }
        else if (strcmp(argv[i], "-dump") == 0 && i+1 < argc) g_dump_out = argv[++i];
        else if (strcmp(argv[i], "-dumpfb") == 0) dumpfb = 1;
        else if (strcmp(argv[i], "-fb") == 0 && i+1 < argc) fb_out = argv[++i];
        else if (strcmp(argv[i], "-arch") == 0 && i+1 < argc) {
            i++;
            const IsaArch *a = NULL;
            for (const IsaArch *c = isa_arches; c->name; c++) if (strcmp(c->name, argv[i]) == 0) a = c;
            if (!a) {
                fprintf(stderr, "sim_c: unknown arch '%s'; built with:", argv[i]);
                for (const IsaArch *c = isa_arches; c->name; c++) fprintf(stderr, " %s", c->name);
                fprintf(stderr, "\n");
                return 1;
            }
            g_arch = a; g_arch_name = a->name;
        }
        else if (strcmp(argv[i], "-maxsteps") == 0 && i+1 < argc) {
            maxsteps_override = atoll(argv[++i]);
        }
        else if (strcmp(argv[i], "-load") == 0 && i+2 < argc) {
            if (nloads == MAX_LOADS) { fprintf(stderr, "sim_c: at most %d -load files\n", MAX_LOADS); return 1; }
            load_addr[nloads] = (uint32_t)strtoul(argv[i+1], NULL, 0);
            load_path[nloads++] = argv[i+2];
            i += 2;
        }
        else if (strcmp(argv[i], "-soc") == 0) { g_soc = 1; }
        else if (strcmp(argv[i], "-cores") == 0 && i+1 < argc) {
            g_ncores = atoi(argv[++i]);
            if (g_ncores < 1 || g_ncores > SIM_MAX_CORES) {
                fprintf(stderr, "sim_c: -cores must be 1..%d\n", SIM_MAX_CORES);
                return 1;
            }
        }
        else if (strcmp(argv[i], "-linemap") == 0 && i+1 < argc) {
            g_linemap_out = argv[++i];
        }
        else if (strcmp(argv[i], "-hex") == 0 && i+1 < argc) {
            g_hex_out = argv[++i];
        }
        else filename = argv[i];
    }
    if (!filename) {
        print_usage(stderr);
        return 1;
    }

    if (maxsteps_override > 0) g_max_steps = maxsteps_override;
    if (g_profile) memset(prof_lineno, 0xff, sizeof(prof_lineno));  /* -1 = no mapping */
    char *src = read_file(filename);
    g_assembler_done = 0;
    if (g_profile) prof_split_lines(src);
    assemble_cpu4(src);
    free(src);
    for (int k = 0; k < nloads; k++) {
        /* SDRAM only: the BRAM image is the assembler's. The chip byte
         * range must not wrap, so an aliased address loads like its
         * un-aliased one. */
        uint32_t a = load_addr[k];
        if (!addr_is_sdram(a)) {
            fprintf(stderr, "sim_c: -load address 0x%x is not in SDRAM (0x10000 or above)\n", (unsigned)a);
            return 1;
        }
        FILE *lf = fopen(load_path[k], "rb");
        if (!lf) { perror(load_path[k]); return 1; }
        ensure_sdram();
        uint32_t chip = sdram_chip_byte(a);
        (void)fread(sdram + chip, 1, SDRAM_SIZE - chip, lf);
        int more = fgetc(lf) != EOF;
        fclose(lf);
        if (more) {
            fprintf(stderr, "sim_c: %s does not fit in SDRAM at 0x%x\n", load_path[k], (unsigned)a);
            return 1;
        }
    }
    if (g_linemap_out) dump_linemap(g_linemap_out);
    if (g_hex_out)     dump_hex(g_hex_out);
    { int i = find_sym("_globals_start"); if (i >= 0) g_write_threshold = syms[i].addr; }
    g_assembler_done = 1;
    if (g_dump_out) {
        uint16_t code_end = g_asm_end;
        { int i = find_sym("_globals_start"); if (i >= 0) code_end = syms[i].addr; }
        print_dump(code_end, g_asm_end, g_dump_out);
    }
    /* -dump / -linemap / -hex are assembly-only passes — do not execute. */
    if (g_dump_out || g_linemap_out || g_hex_out) return 0;
    if (trace_path) {
        g_trace_out = fopen(trace_path, "w");
        if (!g_trace_out) { perror(trace_path); return 1; }
    }
    g_nunits = g_soc ? g_ncores * SOC_NCTX : g_ncores;
    g_cores = calloc((size_t)g_nunits, sizeof(Core));
    g_tiles = calloc((size_t)g_ncores, sizeof(Tile));
    if (!g_cores || !g_tiles) { fprintf(stderr, "sim_c: out of memory for %d cores\n", g_ncores); return 1; }
    for (int i = 0; i < g_ncores; i++) {
        uint8_t *b = malloc(sizeof(mem));
        if (!b) { fprintf(stderr, "sim_c: out of memory for core %d BRAM\n", i); return 1; }
        memcpy(b, mem, sizeof(mem));
        if (g_soc) {
            for (int k = 0; k < SOC_NCTX; k++) { g_cores[i * SOC_NCTX + k].bram = b; g_cores[i * SOC_NCTX + k].H = (k != 0); }
        } else {
            g_cores[i].bram = b;
        }
    }
    g_bram = g_cores[0].bram;
    run_cpu4();
    if (g_trace_out) fclose(g_trace_out);
    if (g_retire_out) fclose(g_retire_out);
    if (dumpfb) dump_framebuffer();
    if (fb_out)  dump_bitmap_fb(fb_out);
    if (g_profile) print_profile();
    if (g_pccount_out) {
        FILE *pf = fopen(g_pccount_out, "w");
        if (pf) {
            for (int a = 0; a < 65536; a++)
                if (prof_count[a]) fprintf(pf, "%04x %u\n", a, prof_count[a]);
            fclose(pf);
        }
    }
    return 0;
}
