#!/usr/bin/env python3
"""Regenerate tests/cases/floats/fpu_vectors.c from the Python FPU model
(cpu4/cpu.py, a port of cpu4/fpu_model.h). Run after any change to the
float semantics; sim_c, irsim and the RTL bench must all reproduce the hash."""
import sys, struct, random, os
here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(here, '..', 'cpu4')); import cpu
def f2b(f): return struct.unpack('<I', struct.pack('<f', f))[0]
vals=[f2b(v) for v in [0.0,1.0,-1.0,0.1,0.2,0.3,1.5,2.5,3.0,1.0/3,1e-3,123456.0,1.1,0.9999,2.0**24+1,-2.0**24-3,3.4e38,1e-38,1e-40,7.25,-7.25]]
vals+= [0x80000000, 0x7f800000, 0xff800000, 0x3f800001, 0x3f7fffff, 0x00000001, 0x007fffff, 0x4b000001, 0xcb000001, 0x4effffff, 0x5f000000]
random.seed(20260924)
vals+=[random.getrandbits(32) for _ in range(20)]
pairs=[(vals[i], vals[(i*7+3)%len(vals)]) for i in range(len(vals))]+[(random.choice(vals), random.choice(vals)) for _ in range(40)]
h=0x811c9dc5
def mix(v):
    global h; h=((h ^ (v & 0xffffffff)) * 0x01000193) & 0xffffffff
for a,b in pairs:
    mix(cpu.cpu4_fadd(a,b)); mix(cpu.cpu4_fsub(a,b)); mix(cpu.cpu4_fmul(a,b)); mix(cpu.cpu4_fdiv(a,b))
    mix(cpu.cpu4_flt(a,b)); mix(cpu.cpu4_fle(a,b)); mix(cpu.cpu4_ftoi(a)); mix(cpu.cpu4_itof(a)); mix(cpu.cpu4_frecip(a)); mix(cpu.cpu4_frsqrt(a))
exp = h if h < 0x80000000 else h - 0x100000000
L=[]
L.append("// EXPECT_R0: %d" % exp)
L.append("// TIMEOUT: 4000000")
L.append("// FPU semantics vectors (cpu4/fpu_model.h): fadd/fsub/fmul/fdiv/flt/fle/ftoi/itof/")
L.append("// frecip/frsqrt over %d operand pairs (ties, cancellation, overflow, underflow," % len(pairs))
L.append("// denormals, infinities, signed zeros, random patterns), folded into an FNV hash.")
L.append("// Generated by tests/gen_fpu_vectors.py from the Python model; the same program on")
L.append("// the RTL bench proves the hardware is bit-exact. Operands come from a volatile")
L.append("// table so the compiler never folds them.")
L.append("typedef union { float f; int i; unsigned u; } U;")
L.append("static volatile unsigned g_a[%d] = {" % len(pairs) + ",".join("0x%08xu" % a for a,b in pairs) + "};")
L.append("static volatile unsigned g_b[%d] = {" % len(pairs) + ",".join("0x%08xu" % b for a,b in pairs) + "};")
L.append("static unsigned h;")
L.append("static void mix(unsigned v) { h = (h ^ v) * 0x01000193u; }")
L.append("static unsigned bits(float f) { U u; u.f = f; return u.u; }")
L.append("int main(void) {")
L.append("    int k;")
L.append("    h = 0x811c9dc5u;")
L.append("    for (k = 0; k < %d; k++) {" % len(pairs))
L.append("        U a, b; a.u = g_a[k]; b.u = g_b[k];")
L.append("        mix(bits(a.f + b.f)); mix(bits(a.f - b.f)); mix(bits(a.f * b.f)); mix(bits(a.f / b.f));")
L.append("        mix(a.f < b.f); mix(a.f <= b.f); mix((unsigned)(int)a.f); mix(bits((float)a.i));")
L.append("        mix(bits(__builtin_frecip(a.f))); mix(bits(__builtin_frsqrt(a.f)));")
L.append("    }")
L.append("    return (int)h;")
L.append("}")
open(os.path.join(here, 'cases', 'floats', 'fpu_vectors.c'), 'w').write("\n".join(L)+"\n")
print("fpu_vectors.c: expected", exp, "pairs", len(pairs))
