/* Generated by isatool/gen.py from cpu5/isa.py -- do not edit; edit the ISA and run `make isa`. */
/* The cpu5 fetch/decode/execute step, generated from the format templates,
 * opcodes, operands, invariants and semantics in the ISA definition.
 * Included by sim_c.c after isatool/exec_common.h. */
#ifndef CPU5_EXEC_GEN_H
#define CPU5_EXEC_GEN_H

#include "../cpu5/fpu_model.h"

/* ret: SP = BP; BP = M32[SP]; PC = M32[SP] >> 16; SP = SP + 4 */
static void cpu5_gx_ret(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->sp = (uint16_t)((uint32_t)cc->bp);
    cc->bp = (uint16_t)(gen_rd32((uint32_t)cc->sp, oldpc));
    cc->pc = (uint16_t)(shr32(gen_rd32((uint32_t)cc->sp, oldpc), 0x10u));
    cc->sp = (uint16_t)((uint32_t)((uint32_t)cc->sp + 0x4u));
}

/* zero0: R[0] = 0 */
static void cpu5_gx_zero0(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[0] = 0x0u;
}

/* zero1: R[1] = 0 */
static void cpu5_gx_zero1(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[1] = 0x0u;
}

/* zero2: R[2] = 0 */
static void cpu5_gx_zero2(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[2] = 0x0u;
}

/* zero3: R[3] = 0 */
static void cpu5_gx_zero3(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[3] = 0x0u;
}

/* zero4: R[4] = 0 */
static void cpu5_gx_zero4(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[4] = 0x0u;
}

/* zero5: R[5] = 0 */
static void cpu5_gx_zero5(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[5] = 0x0u;
}

/* zero6: R[6] = 0 */
static void cpu5_gx_zero6(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[6] = 0x0u;
}

/* halt: H = 1 */
static void cpu5_gx_halt(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->H = (0x1u) & 1u;
}

/* zero7: R[7] = 0 */
static void cpu5_gx_zero7(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[7] = 0x0u;
}

/* zero8: R[8] = 0 */
static void cpu5_gx_zero8(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[8] = 0x0u;
}

/* zero9: R[9] = 0 */
static void cpu5_gx_zero9(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[9] = 0x0u;
}

/* zeroa: R[10] = 0 */
static void cpu5_gx_zeroa(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[10] = 0x0u;
}

/* zerob: R[11] = 0 */
static void cpu5_gx_zerob(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[11] = 0x0u;
}

/* zeroc: R[12] = 0 */
static void cpu5_gx_zeroc(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[12] = 0x0u;
}

/* zerod: R[13] = 0 */
static void cpu5_gx_zerod(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[13] = 0x0u;
}

/* zeroe: R[14] = 0 */
static void cpu5_gx_zeroe(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[14] = 0x0u;
}

/* zerof: R[15] = 0 */
static void cpu5_gx_zerof(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[15] = 0x0u;
}

/* sxb: R[rd] = sx(R[rd], 8) */
static void cpu5_gx_sxb(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = sx32(cc->r[f_rd], 8);
}

/* sxw: R[rd] = sx(R[rd], 16) */
static void cpu5_gx_sxw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = sx32(cc->r[f_rd], 16);
}

/* inc: R[rd] = R[rd] + 1 */
static void cpu5_gx_inc(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rd] + 0x1u);
}

/* dec: R[rd] = R[rd] - 1 */
static void cpu5_gx_dec(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rd] - 0x1u);
}

/* pushr: SP = SP - 4; M32[SP] = R[rd] */
static void cpu5_gx_pushr(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->sp = (uint16_t)((uint32_t)((uint32_t)cc->sp - 0x4u));
    gen_wr32((uint32_t)cc->sp, cc->r[f_rd], oldpc);
}

/* popr: R[rd] = M32[SP]; SP = SP + 4 */
static void cpu5_gx_popr(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = gen_rd32((uint32_t)cc->sp, oldpc);
    cc->sp = (uint16_t)((uint32_t)((uint32_t)cc->sp + 0x4u));
}

/* zxb: R[rd] = zx(R[rd], 8) */
static void cpu5_gx_zxb(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (cc->r[f_rd] & 0xffu);
}

/* itof: R[rd] = itof(R[rd]) */
static void cpu5_gx_itof(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu5_itof(cc->r[f_rd]);
}

/* ftoi: R[rd] = ftoi(R[rd]) */
static void cpu5_gx_ftoi(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu5_ftoi(cc->r[f_rd]);
}

/* jlr: LR = PC; PC = R[rd] */
static void cpu5_gx_jlr(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->lr = (uint16_t)((uint32_t)cc->pc);
    cc->pc = (uint16_t)(cc->r[f_rd]);
}

/* jr: PC = R[rd] */
static void cpu5_gx_jr(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->pc = (uint16_t)(cc->r[f_rd]);
}

/* ssp: SP = R[rd] */
static void cpu5_gx_ssp(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->sp = (uint16_t)(cc->r[f_rd]);
}

/* neg: R[rd] = -R[rd] */
static void cpu5_gx_neg(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(0u - cc->r[f_rd]);
}

/* frecip: R[rd] = frecip(R[rd]) */
static void cpu5_gx_frecip(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu5_frecip(cc->r[f_rd]);
}

/* frsqrt: R[rd] = frsqrt(R[rd]) */
static void cpu5_gx_frsqrt(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu5_frsqrt(cc->r[f_rd]);
}

/* putchar: putchar(R[rd]) */
static void cpu5_gx_putchar(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 0) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    gen_putchar(cc->r[f_rd]);
}

/* ll: R[rx] = M32[lo16(BP + sext(imm) * 4)] */
static void cpu5_gx_ll(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = gen_rd32(((uint32_t)((uint32_t)cc->bp + (uint32_t)(sx32(f_imm, 7) * 0x4u)) & 0xffffu), oldpc);
}

/* sl: M32[lo16(BP + sext(imm) * 4)] = R[rx] */
static void cpu5_gx_sl(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    gen_wr32(((uint32_t)((uint32_t)cc->bp + (uint32_t)(sx32(f_imm, 7) * 0x4u)) & 0xffffu), cc->r[f_rx], oldpc);
}

/* shli: R[rx] = R[rx] << (imm & 31) */
static void cpu5_gx_shli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = shl32(cc->r[f_rx], (uint32_t)(f_imm & 0x1fu));
}

/* imms: R[rx] = sext(imm) */
static void cpu5_gx_imms(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = sx32(f_imm, 7);
}

/* mov: R[rd] = R[rx] */
static void cpu5_gx_mov(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 4) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 0) & 0xfu); (void)f_rx;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cc->r[f_rx];
}

/* zxw: R[rd] = zx(R[rd], 16) */
static void cpu5_gx_zxw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 4) & 0xfu); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (cc->r[f_rd] & 0xffffu);
}

/* llb_0: R[rd] = M8[R[rx]] */
static void cpu5_gx_llb_0(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 4) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 0) & 0xfu); (void)f_rx;
    (void)w; (void)oldpc;
    cc->r[f_rd] = gen_rd8(cc->r[f_rx], oldpc);
}

/* llw_0: R[rd] = M16[R[rx]] */
static void cpu5_gx_llw_0(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 4) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 0) & 0xfu); (void)f_rx;
    (void)w; (void)oldpc;
    cc->r[f_rd] = gen_rd16(cc->r[f_rx], oldpc);
}

/* lll_0: R[rd] = M32[R[rx]] */
static void cpu5_gx_lll_0(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 4) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 0) & 0xfu); (void)f_rx;
    (void)w; (void)oldpc;
    cc->r[f_rd] = gen_rd32(cc->r[f_rx], oldpc);
}

/* slb_0: M8[R[ry]] = R[rx] */
static void cpu5_gx_slb_0(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    gen_wr8(cc->r[f_ry], cc->r[f_rx], oldpc);
}

/* slw_0: M16[R[ry]] = R[rx] */
static void cpu5_gx_slw_0(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    gen_wr16(cc->r[f_ry], cc->r[f_rx], oldpc);
}

/* sll_0: M32[R[ry]] = R[rx] */
static void cpu5_gx_sll_0(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    gen_wr32(cc->r[f_ry], cc->r[f_rx], oldpc);
}

/* llbx_0: R[rd] = sx(M8[R[rx]], 8) */
static void cpu5_gx_llbx_0(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 4) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 0) & 0xfu); (void)f_rx;
    (void)w; (void)oldpc;
    cc->r[f_rd] = sx32(gen_rd8(cc->r[f_rx], oldpc), 8);
}

/* llwx_0: R[rd] = sx(M8[R[rx]], 16) */
static void cpu5_gx_llwx_0(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 4) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 0) & 0xfu); (void)f_rx;
    (void)w; (void)oldpc;
    cc->r[f_rd] = sx32(gen_rd8(cc->r[f_rx], oldpc), 16);
}

/* add: R[rd] = R[rx] + R[ry] */
static void cpu5_gx_add(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] + cc->r[f_ry]);
}

/* sub: R[rd] = R[rx] - R[ry] */
static void cpu5_gx_sub(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] - cc->r[f_ry]);
}

/* mul: R[rd] = R[rx] * R[ry] */
static void cpu5_gx_mul(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] * cc->r[f_ry]);
}

/* div: R[rd] = R[rx] /u R[ry] */
static void cpu5_gx_div(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = divu32(cc->r[f_rx], cc->r[f_ry]);
}

/* mod: R[rd] = R[rx] %u R[ry] */
static void cpu5_gx_mod(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = modu32(cc->r[f_rx], cc->r[f_ry]);
}

/* shl: R[rd] = R[rx] << (R[ry] & 31) */
static void cpu5_gx_shl(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = shl32(cc->r[f_rx], (uint32_t)(cc->r[f_ry] & 0x1fu));
}

/* shr: R[rd] = R[rx] >> (R[ry] & 31) */
static void cpu5_gx_shr(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = shr32(cc->r[f_rx], (uint32_t)(cc->r[f_ry] & 0x1fu));
}

/* lt: R[rd] = R[rx] <u R[ry] */
static void cpu5_gx_lt(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] < cc->r[f_ry]);
}

/* le: R[rd] = R[rx] <=u R[ry] */
static void cpu5_gx_le(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] <= cc->r[f_ry]);
}

/* eq: R[rd] = R[rx] == R[ry] */
static void cpu5_gx_eq(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] == cc->r[f_ry]);
}

/* ne: R[rd] = R[rx] != R[ry] */
static void cpu5_gx_ne(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] != cc->r[f_ry]);
}

/* and: R[rd] = R[rx] & R[ry] */
static void cpu5_gx_and(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] & cc->r[f_ry]);
}

/* or: R[rd] = R[rx] | R[ry] */
static void cpu5_gx_or(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] | cc->r[f_ry]);
}

/* xor: R[rd] = R[rx] ^ R[ry] */
static void cpu5_gx_xor(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] ^ cc->r[f_ry]);
}

/* lts: R[rd] = R[rx] <s R[ry] */
static void cpu5_gx_lts(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)((int32_t)cc->r[f_rx] < (int32_t)cc->r[f_ry]);
}

/* les: R[rd] = R[rx] <=s R[ry] */
static void cpu5_gx_les(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)((int32_t)cc->r[f_rx] <= (int32_t)cc->r[f_ry]);
}

/* divs: R[rd] = R[rx] /s R[ry] */
static void cpu5_gx_divs(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = divs32(cc->r[f_rx], cc->r[f_ry]);
}

/* mods: R[rd] = R[rx] %s R[ry] */
static void cpu5_gx_mods(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = mods32(cc->r[f_rx], cc->r[f_ry]);
}

/* shrs: R[rd] = R[rx] >>s (R[ry] & 31) */
static void cpu5_gx_shrs(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = sar32(cc->r[f_rx], (uint32_t)(cc->r[f_ry] & 0x1fu));
}

/* fadd: R[rd] = fadd(R[rx], R[ry]) */
static void cpu5_gx_fadd(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu5_fadd(cc->r[f_rx], cc->r[f_ry]);
}

/* fsub: R[rd] = fsub(R[rx], R[ry]) */
static void cpu5_gx_fsub(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu5_fsub(cc->r[f_rx], cc->r[f_ry]);
}

/* fmul: R[rd] = fmul(R[rx], R[ry]) */
static void cpu5_gx_fmul(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu5_fmul(cc->r[f_rx], cc->r[f_ry]);
}

/* fdiv: R[rd] = fdiv(R[rx], R[ry]) */
static void cpu5_gx_fdiv(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu5_fdiv(cc->r[f_rx], cc->r[f_ry]);
}

/* flt: R[rd] = flt(R[rx], R[ry]) */
static void cpu5_gx_flt(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu5_flt(cc->r[f_rx], cc->r[f_ry]);
}

/* fle: R[rd] = fle(R[rx], R[ry]) */
static void cpu5_gx_fle(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu5_fle(cc->r[f_rx], cc->r[f_ry]);
}

/* zxwor: R[rd] = zx(R[rx] | R[ry], 16) */
static void cpu5_gx_zxwor(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = ((uint32_t)(cc->r[f_rx] | cc->r[f_ry]) & 0xffffu);
}

/* sxwor: R[rd] = sx(R[rx] | R[ry], 16) */
static void cpu5_gx_sxwor(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 8) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 4) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0xfu); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = sx32((uint32_t)(cc->r[f_rx] | cc->r[f_ry]), 16);
}

/* j: PC = imm */
static void cpu5_gx_j(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->pc = (uint16_t)(f_imm);
}

/* jl: LR = PC; PC = imm */
static void cpu5_gx_jl(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->lr = (uint16_t)((uint32_t)cc->pc);
    cc->pc = (uint16_t)(f_imm);
}

/* enter: M32[lo16(SP - 4)] = (LR << 16) | BP; BP = SP - 4; SP = SP - imm - 4 */
static void cpu5_gx_enter(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    gen_wr32(((uint32_t)((uint32_t)cc->sp - 0x4u) & 0xffffu), (uint32_t)(shl32((uint32_t)cc->lr, 0x10u) | (uint32_t)cc->bp), oldpc);
    cc->bp = (uint16_t)((uint32_t)((uint32_t)cc->sp - 0x4u));
    cc->sp = (uint16_t)((uint32_t)((uint32_t)((uint32_t)cc->sp - f_imm) - 0x4u));
}

/* lea: R[rd] = lo16(BP + sext(imm) * 4) */
static void cpu5_gx_lea(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 16) & 0xfu); (void)f_rd;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = ((uint32_t)((uint32_t)cc->bp + (uint32_t)(sx32(f_imm, 16) * 0x4u)) & 0xffffu);
}

/* immw: R[rx] = imm */
static void cpu5_gx_immw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = f_imm;
}

/* immwh: R[rx] = zx(R[rx], 16) | (imm << 16) */
static void cpu5_gx_immwh(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = (uint32_t)((cc->r[f_rx] & 0xffffu) | shl32(f_imm, 0x10u));
}

/* jz: if R[rx] == 0 then PC = imm */
static void cpu5_gx_jz(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] == 0x0u)) {
        cc->pc = (uint16_t)(f_imm);
    }
}

/* jnz: if R[rx] != 0 then PC = imm */
static void cpu5_gx_jnz(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] != 0x0u)) {
        cc->pc = (uint16_t)(f_imm);
    }
}

/* addli: R[rd] = R[rx] + sext(imm) */
static void cpu5_gx_addli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] + sx32(f_imm, 16));
}

/* subli: R[rd] = R[rx] - sext(imm) */
static void cpu5_gx_subli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] - sx32(f_imm, 16));
}

/* mulli: R[rd] = R[rx] * sext(imm) */
static void cpu5_gx_mulli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] * sx32(f_imm, 16));
}

/* divli: R[rd] = R[rx] /u sext(imm) */
static void cpu5_gx_divli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = divu32(cc->r[f_rx], sx32(f_imm, 16));
}

/* modli: R[rd] = R[rx] %u sext(imm) */
static void cpu5_gx_modli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = modu32(cc->r[f_rx], sx32(f_imm, 16));
}

/* shlli: R[rd] = R[rx] << (imm & 31) */
static void cpu5_gx_shlli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = shl32(cc->r[f_rx], (uint32_t)(f_imm & 0x1fu));
}

/* shrli: R[rd] = R[rx] >> (imm & 31) */
static void cpu5_gx_shrli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = shr32(cc->r[f_rx], (uint32_t)(f_imm & 0x1fu));
}

/* leli: R[rd] = R[rx] <=u sext(imm) */
static void cpu5_gx_leli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] <= sx32(f_imm, 16));
}

/* gtli: R[rd] = R[rx] >u sext(imm) */
static void cpu5_gx_gtli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] > sx32(f_imm, 16));
}

/* eqli: R[rd] = R[rx] == sext(imm) */
static void cpu5_gx_eqli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] == sx32(f_imm, 16));
}

/* neli: R[rd] = R[rx] != sext(imm) */
static void cpu5_gx_neli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] != sx32(f_imm, 16));
}

/* andli: R[rd] = R[rx] & sext(imm) */
static void cpu5_gx_andli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] & sx32(f_imm, 16));
}

/* orli: R[rd] = R[rx] | sext(imm) */
static void cpu5_gx_orli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] | sx32(f_imm, 16));
}

/* xorli: R[rd] = R[rx] ^ sext(imm) */
static void cpu5_gx_xorli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] ^ sx32(f_imm, 16));
}

/* lesli: R[rd] = R[rx] <=s sext(imm) */
static void cpu5_gx_lesli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)((int32_t)cc->r[f_rx] <= (int32_t)sx32(f_imm, 16));
}

/* gtsli: R[rd] = R[rx] >s sext(imm) */
static void cpu5_gx_gtsli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)((int32_t)cc->r[f_rx] > (int32_t)sx32(f_imm, 16));
}

/* divsli: R[rd] = R[rx] /s sext(imm) */
static void cpu5_gx_divsli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = divs32(cc->r[f_rx], sx32(f_imm, 16));
}

/* modsli: R[rd] = R[rx] %s sext(imm) */
static void cpu5_gx_modsli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = mods32(cc->r[f_rx], sx32(f_imm, 16));
}

/* shrsli: R[rd] = R[rx] >>s (imm & 31) */
static void cpu5_gx_shrsli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = sar32(cc->r[f_rx], (uint32_t)(f_imm & 0x1fu));
}

/* bitex: R[rd] = (R[rx] >> (imm & 31)) & ((2 << ((imm >> 5) & 15)) - 1) */
static void cpu5_gx_bitex(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(shr32(cc->r[f_rx], (uint32_t)(f_imm & 0x1fu)) & (uint32_t)(shl32(0x2u, (uint32_t)(shr32(f_imm, 0x5u) & 0xfu)) - 0x1u));
}

/* rsubli: R[rd] = sext(imm) - R[rx] */
static void cpu5_gx_rsubli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(sx32(f_imm, 16) - cc->r[f_rx]);
}

/* rdivli: R[rd] = sext(imm) /u R[rx] */
static void cpu5_gx_rdivli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = divu32(sx32(f_imm, 16), cc->r[f_rx]);
}

/* rmodli: R[rd] = sext(imm) %u R[rx] */
static void cpu5_gx_rmodli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = modu32(sx32(f_imm, 16), cc->r[f_rx]);
}

/* rdivsli: R[rd] = sext(imm) /s R[rx] */
static void cpu5_gx_rdivsli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 20) & 0xfu); (void)f_rd;
    const uint32_t f_rx = ((w >> 16) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = divs32(sx32(f_imm, 16), cc->r[f_rx]);
}

/* lb: R[rx] = M8[lo16(BP + sext(imm))] */
static void cpu5_gx_lb(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = gen_rd8(((uint32_t)((uint32_t)cc->bp + sx32(f_imm, 16)) & 0xffffu), oldpc);
}

/* lw: R[rx] = M16[lo16(BP + sext(imm) * 2)] */
static void cpu5_gx_lw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = gen_rd16(((uint32_t)((uint32_t)cc->bp + (uint32_t)(sx32(f_imm, 16) * 0x2u)) & 0xffffu), oldpc);
}

/* sb: M8[lo16(BP + sext(imm))] = R[rx] */
static void cpu5_gx_sb(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    gen_wr8(((uint32_t)((uint32_t)cc->bp + sx32(f_imm, 16)) & 0xffffu), cc->r[f_rx], oldpc);
}

/* sw: M16[lo16(BP + sext(imm) * 2)] = R[rx] */
static void cpu5_gx_sw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    gen_wr16(((uint32_t)((uint32_t)cc->bp + (uint32_t)(sx32(f_imm, 16) * 0x2u)) & 0xffffu), cc->r[f_rx], oldpc);
}

/* lbx: R[rx] = sx(M8[lo16(BP + sext(imm))], 8) */
static void cpu5_gx_lbx(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = sx32(gen_rd8(((uint32_t)((uint32_t)cc->bp + sx32(f_imm, 16)) & 0xffffu), oldpc), 8);
}

/* lwx: R[rx] = sx(M16[lo16(BP + sext(imm) * 2)], 16) */
static void cpu5_gx_lwx(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = sx32(gen_rd16(((uint32_t)((uint32_t)cc->bp + (uint32_t)(sx32(f_imm, 16) * 0x2u)) & 0xffffu), oldpc), 16);
}

/* addi: R[rx] = R[rx] + sext(imm) */
static void cpu5_gx_addi(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = (uint32_t)(cc->r[f_rx] + sx32(f_imm, 16));
}

/* andi: R[rx] = R[rx] & imm */
static void cpu5_gx_andi(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = (uint32_t)(cc->r[f_rx] & f_imm);
}

/* shrsi: R[rx] = R[rx] >>s (imm & 31) */
static void cpu5_gx_shrsi(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = sar32(cc->r[f_rx], (uint32_t)(f_imm & 0x1fu));
}

/* adjw: SP = SP + sext(imm) * 4 */
static void cpu5_gx_adjw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->sp = (uint16_t)((uint32_t)((uint32_t)cc->sp + (uint32_t)(sx32(f_imm, 16) * 0x4u)));
}

/* llb: R[rx] = M8[R[ry] + sext(imm)] */
static void cpu5_gx_llb(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 16) & 0xfu); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = gen_rd8((uint32_t)(cc->r[f_ry] + sx32(f_imm, 16)), oldpc);
}

/* llw: R[rx] = M16[R[ry] + sext(imm) * 2] */
static void cpu5_gx_llw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 16) & 0xfu); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = gen_rd16((uint32_t)(cc->r[f_ry] + (uint32_t)(sx32(f_imm, 16) * 0x2u)), oldpc);
}

/* lll: R[rx] = M32[R[ry] + sext(imm) * 4] */
static void cpu5_gx_lll(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 16) & 0xfu); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = gen_rd32((uint32_t)(cc->r[f_ry] + (uint32_t)(sx32(f_imm, 16) * 0x4u)), oldpc);
}

/* slb: M8[R[ry] + sext(imm)] = R[rx] */
static void cpu5_gx_slb(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 16) & 0xfu); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    gen_wr8((uint32_t)(cc->r[f_ry] + sx32(f_imm, 16)), cc->r[f_rx], oldpc);
}

/* slw: M16[R[ry] + sext(imm) * 2] = R[rx] */
static void cpu5_gx_slw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 16) & 0xfu); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    gen_wr16((uint32_t)(cc->r[f_ry] + (uint32_t)(sx32(f_imm, 16) * 0x2u)), cc->r[f_rx], oldpc);
}

/* sll: M32[R[ry] + sext(imm) * 4] = R[rx] */
static void cpu5_gx_sll(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 16) & 0xfu); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    gen_wr32((uint32_t)(cc->r[f_ry] + (uint32_t)(sx32(f_imm, 16) * 0x4u)), cc->r[f_rx], oldpc);
}

/* llbx: R[rx] = sx(M8[R[ry] + sext(imm)], 8) */
static void cpu5_gx_llbx(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 16) & 0xfu); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = sx32(gen_rd8((uint32_t)(cc->r[f_ry] + sx32(f_imm, 16)), oldpc), 8);
}

/* llwx: R[rx] = sx(M16[R[ry] + sext(imm) * 2], 16) */
static void cpu5_gx_llwx(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 16) & 0xfu); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = sx32(gen_rd16((uint32_t)(cc->r[f_ry] + (uint32_t)(sx32(f_imm, 16) * 0x2u)), oldpc), 16);
}

/* beq: if R[rx] == R[ry] then PC = PC + sext(disp) */
static void cpu5_gx_beq(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 16) & 0xfu); (void)f_ry;
    const uint32_t f_disp = ((w >> 0) & 0xffffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] == cc->r[f_ry])) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 16)));
    }
}

/* bne: if R[rx] != R[ry] then PC = PC + sext(disp) */
static void cpu5_gx_bne(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 16) & 0xfu); (void)f_ry;
    const uint32_t f_disp = ((w >> 0) & 0xffffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] != cc->r[f_ry])) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 16)));
    }
}

/* blt: if R[rx] <u R[ry] then PC = PC + sext(disp) */
static void cpu5_gx_blt(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 16) & 0xfu); (void)f_ry;
    const uint32_t f_disp = ((w >> 0) & 0xffffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] < cc->r[f_ry])) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 16)));
    }
}

/* ble: if R[rx] <=u R[ry] then PC = PC + sext(disp) */
static void cpu5_gx_ble(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 16) & 0xfu); (void)f_ry;
    const uint32_t f_disp = ((w >> 0) & 0xffffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] <= cc->r[f_ry])) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 16)));
    }
}

/* blts: if R[rx] <s R[ry] then PC = PC + sext(disp) */
static void cpu5_gx_blts(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 16) & 0xfu); (void)f_ry;
    const uint32_t f_disp = ((w >> 0) & 0xffffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)((int32_t)cc->r[f_rx] < (int32_t)cc->r[f_ry])) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 16)));
    }
}

/* bles: if R[rx] <=s R[ry] then PC = PC + sext(disp) */
static void cpu5_gx_bles(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_ry = ((w >> 16) & 0xfu); (void)f_ry;
    const uint32_t f_disp = ((w >> 0) & 0xffffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)((int32_t)cc->r[f_rx] <= (int32_t)cc->r[f_ry])) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 16)));
    }
}

/* beqz: if R[rx] == 0 then PC = PC + sext(disp) */
static void cpu5_gx_beqz(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_disp = ((w >> 0) & 0xffffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] == 0x0u)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 16)));
    }
}

/* bnez: if R[rx] != 0 then PC = PC + sext(disp) */
static void cpu5_gx_bnez(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_disp = ((w >> 0) & 0xffffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] != 0x0u)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 16)));
    }
}

/* dbnz: R[rx] = R[rx] - 1; if R[rx] != 0 then PC = PC + sext(disp) */
static void cpu5_gx_dbnz(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_disp = ((w >> 0) & 0xffffu); (void)f_disp;
    (void)w; (void)oldpc;
    cc->r[f_rx] = (uint32_t)(cc->r[f_rx] - 0x1u);
    if ((uint32_t)(cc->r[f_rx] != 0x0u)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 16)));
    }
}

/* bltz: if R[rx] <s 0 then PC = PC + sext(disp) */
static void cpu5_gx_bltz(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_disp = ((w >> 0) & 0xffffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)((int32_t)cc->r[f_rx] < (int32_t)0x0u)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 16)));
    }
}

/* bgez: if R[rx] >=s 0 then PC = PC + sext(disp) */
static void cpu5_gx_bgez(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_disp = ((w >> 0) & 0xffffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)((int32_t)cc->r[f_rx] >= (int32_t)0x0u)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 16)));
    }
}

/* bgtz: if R[rx] >s 0 then PC = PC + sext(disp) */
static void cpu5_gx_bgtz(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_disp = ((w >> 0) & 0xffffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)((int32_t)cc->r[f_rx] > (int32_t)0x0u)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 16)));
    }
}

/* blez: if R[rx] <=s 0 then PC = PC + sext(disp) */
static void cpu5_gx_blez(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_disp = ((w >> 0) & 0xffffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)((int32_t)cc->r[f_rx] <= (int32_t)0x0u)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 16)));
    }
}

/* cbeq: if R[rx] == imm8 then PC = PC + sext(disp) */
static void cpu5_gx_cbeq(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_imm8 = ((w >> 12) & 0xffu); (void)f_imm8;
    const uint32_t f_disp = ((w >> 0) & 0xfffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] == f_imm8)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 12)));
    }
}

/* cbne: if R[rx] != imm8 then PC = PC + sext(disp) */
static void cpu5_gx_cbne(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 20) & 0xfu); (void)f_rx;
    const uint32_t f_imm8 = ((w >> 12) & 0xffu); (void)f_imm8;
    const uint32_t f_disp = ((w >> 0) & 0xfffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] != f_imm8)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 12)));
    }
}

static void cpu5_gen_check(Core *cc, uint16_t oldpc) {
    if ((uint32_t)((uint32_t)cc->sp & 0x3u)) { fprintf(stderr, "CPU5 alignment error: SP misaligned (0x%x) at pc=0x%04x\n", (unsigned)(uint32_t)((uint32_t)cc->sp & 0x3u), oldpc); cc->H = 1; }
    if ((uint32_t)((uint32_t)cc->bp & 0x3u)) { fprintf(stderr, "CPU5 alignment error: BP misaligned (0x%x) at pc=0x%04x\n", (unsigned)(uint32_t)((uint32_t)cc->bp & 0x3u), oldpc); cc->H = 1; }
    (void)cc; (void)oldpc;
}

/* Execute one instruction for core cc; returns its length in bytes. */
static int cpu5_gen_step(Core *cc) {
    const uint16_t oldpc = cc->pc;
    uint32_t w;
    int n = 1;
    switch (read8(oldpc)) {
    case 0x00: case 0x01: case 0x02: case 0x03: case 0x04: case 0x05: case 0x06: case 0x07: case 0x08: case 0x09: case 0x0a: case 0x0b: case 0x0c: case 0x0d: case 0x0e: case 0x0f:
        n = 3; w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        cpu5_gx_j(cc, w, oldpc);
        break;
    case 0x10: case 0x11: case 0x12: case 0x13: case 0x14: case 0x15: case 0x16: case 0x17: case 0x18: case 0x19: case 0x1a: case 0x1b: case 0x1c: case 0x1d: case 0x1e: case 0x1f:
        n = 3; w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        cpu5_gx_jl(cc, w, oldpc);
        break;
    case 0x20: case 0x21: case 0x22: case 0x23: case 0x24: case 0x25: case 0x26: case 0x27: case 0x28: case 0x29: case 0x2a: case 0x2b: case 0x2c: case 0x2d: case 0x2e: case 0x2f:
        n = 3; w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        cpu5_gx_enter(cc, w, oldpc);
        break;
    case 0x30: case 0x31: case 0x32: case 0x33: case 0x34: case 0x35: case 0x36: case 0x37: case 0x38: case 0x39: case 0x3a: case 0x3b: case 0x3c: case 0x3d: case 0x3e: case 0x3f:
        n = 3; w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        cpu5_gx_lea(cc, w, oldpc);
        break;
    case 0x40: case 0x41: case 0x42: case 0x43: case 0x44: case 0x45: case 0x46: case 0x47: case 0x48: case 0x49: case 0x4a: case 0x4b: case 0x4c: case 0x4d: case 0x4e: case 0x4f:
        n = 3; w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        cpu5_gx_immw(cc, w, oldpc);
        break;
    case 0x50: case 0x51: case 0x52: case 0x53: case 0x54: case 0x55: case 0x56: case 0x57: case 0x58: case 0x59: case 0x5a: case 0x5b: case 0x5c: case 0x5d: case 0x5e: case 0x5f:
        n = 3; w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        cpu5_gx_immwh(cc, w, oldpc);
        break;
    case 0x60: case 0x61: case 0x62: case 0x63: case 0x64: case 0x65: case 0x66: case 0x67: case 0x68: case 0x69: case 0x6a: case 0x6b: case 0x6c: case 0x6d: case 0x6e: case 0x6f:
        n = 3; w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        cpu5_gx_jz(cc, w, oldpc);
        break;
    case 0x70: case 0x71: case 0x72: case 0x73: case 0x74: case 0x75: case 0x76: case 0x77: case 0x78: case 0x79: case 0x7a: case 0x7b: case 0x7c: case 0x7d: case 0x7e: case 0x7f:
        n = 3; w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        cpu5_gx_jnz(cc, w, oldpc);
        break;
    case 0x80:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_addli(cc, w, oldpc);
        break;
    case 0x81:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_subli(cc, w, oldpc);
        break;
    case 0x82:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_mulli(cc, w, oldpc);
        break;
    case 0x83:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_divli(cc, w, oldpc);
        break;
    case 0x84:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_modli(cc, w, oldpc);
        break;
    case 0x85:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_shlli(cc, w, oldpc);
        break;
    case 0x86:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_shrli(cc, w, oldpc);
        break;
    case 0x87:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_leli(cc, w, oldpc);
        break;
    case 0x88:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_gtli(cc, w, oldpc);
        break;
    case 0x89:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_eqli(cc, w, oldpc);
        break;
    case 0x8a:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_neli(cc, w, oldpc);
        break;
    case 0x8b:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_andli(cc, w, oldpc);
        break;
    case 0x8c:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_orli(cc, w, oldpc);
        break;
    case 0x8d:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_xorli(cc, w, oldpc);
        break;
    case 0x8e:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_lesli(cc, w, oldpc);
        break;
    case 0x8f:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_gtsli(cc, w, oldpc);
        break;
    case 0x90:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_divsli(cc, w, oldpc);
        break;
    case 0x91:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_modsli(cc, w, oldpc);
        break;
    case 0x92:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_shrsli(cc, w, oldpc);
        break;
    case 0x93:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_bitex(cc, w, oldpc);
        break;
    case 0x94:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_rsubli(cc, w, oldpc);
        break;
    case 0x95:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_rdivli(cc, w, oldpc);
        break;
    case 0x96:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_rmodli(cc, w, oldpc);
        break;
    case 0x97:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_rdivsli(cc, w, oldpc);
        break;
    case 0x98:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_lb(cc, w, oldpc);
        break;
    case 0x99:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_lw(cc, w, oldpc);
        break;
    case 0x9a:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_sb(cc, w, oldpc);
        break;
    case 0x9b:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_sw(cc, w, oldpc);
        break;
    case 0x9c:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_lbx(cc, w, oldpc);
        break;
    case 0x9d:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_lwx(cc, w, oldpc);
        break;
    case 0x9e:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_addi(cc, w, oldpc);
        break;
    case 0x9f:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_andi(cc, w, oldpc);
        break;
    case 0xa0:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_shrsi(cc, w, oldpc);
        break;
    case 0xa1:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_adjw(cc, w, oldpc);
        break;
    case 0xa2:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_llb(cc, w, oldpc);
        break;
    case 0xa3:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_llw(cc, w, oldpc);
        break;
    case 0xa4:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_lll(cc, w, oldpc);
        break;
    case 0xa5:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_slb(cc, w, oldpc);
        break;
    case 0xa6:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_slw(cc, w, oldpc);
        break;
    case 0xa7:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_sll(cc, w, oldpc);
        break;
    case 0xa8:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_llbx(cc, w, oldpc);
        break;
    case 0xa9:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_llwx(cc, w, oldpc);
        break;
    case 0xaa:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_beq(cc, w, oldpc);
        break;
    case 0xab:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_bne(cc, w, oldpc);
        break;
    case 0xac:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_blt(cc, w, oldpc);
        break;
    case 0xad:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_ble(cc, w, oldpc);
        break;
    case 0xae:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_blts(cc, w, oldpc);
        break;
    case 0xaf:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_bles(cc, w, oldpc);
        break;
    case 0xb0:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_beqz(cc, w, oldpc);
        break;
    case 0xb1:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_bnez(cc, w, oldpc);
        break;
    case 0xb2:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_dbnz(cc, w, oldpc);
        break;
    case 0xb3:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_bltz(cc, w, oldpc);
        break;
    case 0xb4:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_bgez(cc, w, oldpc);
        break;
    case 0xb5:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_bgtz(cc, w, oldpc);
        break;
    case 0xb6:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_blez(cc, w, oldpc);
        break;
    case 0xc0: case 0xc1: case 0xc2: case 0xc3: case 0xc4: case 0xc5: case 0xc6: case 0xc7:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        cpu5_gx_ll(cc, w, oldpc);
        break;
    case 0xc8: case 0xc9: case 0xca: case 0xcb: case 0xcc: case 0xcd: case 0xce: case 0xcf:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        cpu5_gx_sl(cc, w, oldpc);
        break;
    case 0xd0: case 0xd1: case 0xd2: case 0xd3: case 0xd4: case 0xd5: case 0xd6: case 0xd7:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        cpu5_gx_shli(cc, w, oldpc);
        break;
    case 0xd8: case 0xd9: case 0xda: case 0xdb: case 0xdc: case 0xdd: case 0xde: case 0xdf:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        cpu5_gx_imms(cc, w, oldpc);
        break;
    case 0xe0:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        cpu5_gx_mov(cc, w, oldpc);
        break;
    case 0xe1:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        cpu5_gx_zxw(cc, w, oldpc);
        break;
    case 0xe2:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        cpu5_gx_llb_0(cc, w, oldpc);
        break;
    case 0xe3:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        cpu5_gx_llw_0(cc, w, oldpc);
        break;
    case 0xe4:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        cpu5_gx_lll_0(cc, w, oldpc);
        break;
    case 0xe5:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        cpu5_gx_slb_0(cc, w, oldpc);
        break;
    case 0xe6:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        cpu5_gx_slw_0(cc, w, oldpc);
        break;
    case 0xe7:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        cpu5_gx_sll_0(cc, w, oldpc);
        break;
    case 0xe8:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        cpu5_gx_llbx_0(cc, w, oldpc);
        break;
    case 0xe9:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        cpu5_gx_llwx_0(cc, w, oldpc);
        break;
    case 0xf0:
        n = 1; w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        cpu5_gx_ret(cc, w, oldpc);
        break;
    case 0xf1:
        n = 1; w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        cpu5_gx_zero0(cc, w, oldpc);
        break;
    case 0xf2:
        n = 1; w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        cpu5_gx_zero1(cc, w, oldpc);
        break;
    case 0xf3:
        n = 1; w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        cpu5_gx_zero2(cc, w, oldpc);
        break;
    case 0xf4:
        n = 1; w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        cpu5_gx_zero3(cc, w, oldpc);
        break;
    case 0xf5:
        n = 1; w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        cpu5_gx_zero4(cc, w, oldpc);
        break;
    case 0xf6:
        n = 1; w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        cpu5_gx_zero5(cc, w, oldpc);
        break;
    case 0xf7:
        n = 1; w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        cpu5_gx_zero6(cc, w, oldpc);
        break;
    case 0xf8:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_cbeq(cc, w, oldpc);
        break;
    case 0xf9:
        n = 4; w = gen_fetch(oldpc, 4); cc->pc = (uint16_t)(oldpc + 4);
        cpu5_gx_cbne(cc, w, oldpc);
        break;
    case 0xfc:
        n = 3; w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        switch (((w >> 12) & 0xfu)) {
        case 0x0: cpu5_gx_add(cc, w, oldpc); break;
        case 0x1: cpu5_gx_sub(cc, w, oldpc); break;
        case 0x2: cpu5_gx_mul(cc, w, oldpc); break;
        case 0x3: cpu5_gx_div(cc, w, oldpc); break;
        case 0x4: cpu5_gx_mod(cc, w, oldpc); break;
        case 0x5: cpu5_gx_shl(cc, w, oldpc); break;
        case 0x6: cpu5_gx_shr(cc, w, oldpc); break;
        case 0x7: cpu5_gx_lt(cc, w, oldpc); break;
        case 0x8: cpu5_gx_le(cc, w, oldpc); break;
        case 0x9: cpu5_gx_eq(cc, w, oldpc); break;
        case 0xa: cpu5_gx_ne(cc, w, oldpc); break;
        case 0xb: cpu5_gx_and(cc, w, oldpc); break;
        case 0xc: cpu5_gx_or(cc, w, oldpc); break;
        case 0xd: cpu5_gx_xor(cc, w, oldpc); break;
        case 0xe: cpu5_gx_lts(cc, w, oldpc); break;
        case 0xf: cpu5_gx_les(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        break;
    case 0xfd:
        n = 3; w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        switch (((w >> 12) & 0xfu)) {
        case 0x0: cpu5_gx_divs(cc, w, oldpc); break;
        case 0x1: cpu5_gx_mods(cc, w, oldpc); break;
        case 0x2: cpu5_gx_shrs(cc, w, oldpc); break;
        case 0x3: cpu5_gx_fadd(cc, w, oldpc); break;
        case 0x4: cpu5_gx_fsub(cc, w, oldpc); break;
        case 0x5: cpu5_gx_fmul(cc, w, oldpc); break;
        case 0x6: cpu5_gx_fdiv(cc, w, oldpc); break;
        case 0x7: cpu5_gx_flt(cc, w, oldpc); break;
        case 0x8: cpu5_gx_fle(cc, w, oldpc); break;
        case 0x9: cpu5_gx_zxwor(cc, w, oldpc); break;
        case 0xa: cpu5_gx_sxwor(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        break;
    case 0xfe:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        switch (((w >> 0) & 0xffu)) {
        case 0x0: cpu5_gx_halt(cc, w, oldpc); break;
        case 0x1: cpu5_gx_zero7(cc, w, oldpc); break;
        case 0x2: cpu5_gx_zero8(cc, w, oldpc); break;
        case 0x3: cpu5_gx_zero9(cc, w, oldpc); break;
        case 0x4: cpu5_gx_zeroa(cc, w, oldpc); break;
        case 0x5: cpu5_gx_zerob(cc, w, oldpc); break;
        case 0x6: cpu5_gx_zeroc(cc, w, oldpc); break;
        case 0x7: cpu5_gx_zerod(cc, w, oldpc); break;
        case 0x8: cpu5_gx_zeroe(cc, w, oldpc); break;
        case 0x9: cpu5_gx_zerof(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        break;
    case 0xff:
        n = 2; w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        switch (((w >> 4) & 0xfu)) {
        case 0x0: cpu5_gx_sxb(cc, w, oldpc); break;
        case 0x1: cpu5_gx_sxw(cc, w, oldpc); break;
        case 0x2: cpu5_gx_inc(cc, w, oldpc); break;
        case 0x3: cpu5_gx_dec(cc, w, oldpc); break;
        case 0x4: cpu5_gx_pushr(cc, w, oldpc); break;
        case 0x5: cpu5_gx_popr(cc, w, oldpc); break;
        case 0x6: cpu5_gx_zxb(cc, w, oldpc); break;
        case 0x7: cpu5_gx_itof(cc, w, oldpc); break;
        case 0x8: cpu5_gx_ftoi(cc, w, oldpc); break;
        case 0x9: cpu5_gx_jlr(cc, w, oldpc); break;
        case 0xa: cpu5_gx_jr(cc, w, oldpc); break;
        case 0xb: cpu5_gx_ssp(cc, w, oldpc); break;
        case 0xc: cpu5_gx_neg(cc, w, oldpc); break;
        case 0xd: cpu5_gx_frecip(cc, w, oldpc); break;
        case 0xe: cpu5_gx_frsqrt(cc, w, oldpc); break;
        case 0xf: cpu5_gx_putchar(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        break;
    default:
        gen_unknown(cc, read8(oldpc), oldpc);
        cc->pc = (uint16_t)(oldpc + 1);
        break;
    }
    cpu5_gen_check(cc, oldpc);
    return n;
}
#endif
