# Generated by isatool/gen.py from cpu4/isa.py -- do not edit; edit the ISA and run `make isa`.
"""The cpu4 fetch/decode/execute step for the Python simulator (isatool/pysim.py)."""
ARCH = 'cpu4'
import sys

M = 0xffffffff
MW = None   # when a list, every store is appended as (address, value, bytes) for the retirement trace
# The float primitives (PRIMITIVES in the ISA definition) are bound into this
# module's namespace by isatool/pysim.py before the first step.

def s32(v): return v - 0x100000000 if v & 0x80000000 else v
def sx32(v, n): v &= (1 << n) - 1; return (v - (1 << n)) & M if v >> (n - 1) else v
def shl32(a, b): return 0 if b >= 32 else (a << b) & M
def shr32(a, b): return 0 if b >= 32 else a >> b
def sar32(a, b): return (M if a & 0x80000000 else 0) if b >= 32 else (s32(a) >> b) & M
def divu32(a, b): return a // b if b else 0
def modu32(a, b): return a % b if b else 0
def divs32(a, b):
    if not b: return 0
    if a == 0x80000000 and b == M: return a
    q = abs(s32(a)) // abs(s32(b))
    return (q if (s32(a) < 0) == (s32(b) < 0) else -q) & M
def mods32(a, b):
    if not b: return 0
    if a == 0x80000000 and b == M: return 0
    r = abs(s32(a)) % abs(s32(b))
    return (-r if s32(a) < 0 else r) & M
def _fault(bits, a, pc):
    sys.stderr.write('%s alignment error: %d-bit access to unaligned address 0x%08x at pc=0x%04x\n' % (ARCH.upper(), bits, a, pc))
    sys.exit(1)
def rd8(m, a, pc): return m.read8(a, False)
def rd16(m, a, pc):
    if a & 1: _fault(16, a, pc)
    return m.read16(a, False)
def rd32(m, a, pc):
    if a & 3: _fault(32, a, pc)
    return m.read32(a, False)
def wr8(m, a, v, pc):
    if MW is not None: MW.append((a, v & 0xff, 1))
    m.write8(a, v & 0xff)
def wr16(m, a, v, pc):
    if a & 1: _fault(16, a, pc)
    if MW is not None: MW.append((a, v & 0xffff, 2))
    m.write16(a, v & 0xffff)
def wr32(m, a, v, pc):
    if a & 3: _fault(32, a, pc)
    if MW is not None: MW.append((a, v, 4))
    m.write32(a, v)
def putc(v):
    sys.stderr.write(chr(v & 0xff)); sys.stderr.flush()
def unknown(s, w, pc):
    sys.stderr.write('%s: unknown instruction 0x%x at pc=%04x\n' % (ARCH, w, pc))
    s.H = 1
def unimplemented(s, name, pc):
    sys.stderr.write('%s: instruction %s at pc=%04x has no semantics yet\n' % (ARCH, name, pc))
    s.H = 1

def gx_halt(s, m, w, oldpc):
    # H = 1
    s.H = 1 & 1

def gx_ret(s, m, w, oldpc):
    # SP = BP; BP = M32[SP]; PC = M32[SP] >> 16; SP = SP + 4
    s.sp = s.bp & 0xffff
    s.bp = rd32(m, s.sp, oldpc) & 0xffff
    s.pc = shr32(rd32(m, s.sp, oldpc), 16) & 0xffff
    s.sp = ((s.sp + 4) & 0xffffffff) & 0xffff

def gx_zero0(s, m, w, oldpc):
    # R[0] = 0
    s.r[0] = 0

def gx_zero1(s, m, w, oldpc):
    # R[1] = 0
    s.r[1] = 0

def gx_zero2(s, m, w, oldpc):
    # R[2] = 0
    s.r[2] = 0

def gx_zero3(s, m, w, oldpc):
    # R[3] = 0
    s.r[3] = 0

def gx_zero4(s, m, w, oldpc):
    # R[4] = 0
    s.r[4] = 0

def gx_zero5(s, m, w, oldpc):
    # R[5] = 0
    s.r[5] = 0

def gx_zero6(s, m, w, oldpc):
    # R[6] = 0
    s.r[6] = 0

def gx_zero7(s, m, w, oldpc):
    # R[7] = 0
    s.r[7] = 0

def gx_addli(s, m, w, oldpc):
    # R[rd] = R[rx] + sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = ((s.r[f_rx] + sx32(f_imm, 9)) & 0xffffffff)

def gx_subli(s, m, w, oldpc):
    # R[rd] = R[rx] - sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = ((s.r[f_rx] - sx32(f_imm, 9)) & 0xffffffff)

def gx_mulli(s, m, w, oldpc):
    # R[rd] = R[rx] * sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = ((s.r[f_rx] * sx32(f_imm, 9)) & 0xffffffff)

def gx_divli(s, m, w, oldpc):
    # R[rd] = R[rx] /u sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = divu32(s.r[f_rx], sx32(f_imm, 9))

def gx_modli(s, m, w, oldpc):
    # R[rd] = R[rx] %u sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = modu32(s.r[f_rx], sx32(f_imm, 9))

def gx_shlli(s, m, w, oldpc):
    # R[rd] = R[rx] << (imm & 31)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = shl32(s.r[f_rx], (f_imm & 31))

def gx_shrli(s, m, w, oldpc):
    # R[rd] = R[rx] >> (imm & 31)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = shr32(s.r[f_rx], (f_imm & 31))

def gx_leli(s, m, w, oldpc):
    # R[rd] = R[rx] <=u sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = int(s.r[f_rx] <= sx32(f_imm, 9))

def gx_gtli(s, m, w, oldpc):
    # R[rd] = R[rx] >u sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = int(s.r[f_rx] > sx32(f_imm, 9))

def gx_eqli(s, m, w, oldpc):
    # R[rd] = R[rx] == sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = int(s.r[f_rx] == sx32(f_imm, 9))

def gx_neli(s, m, w, oldpc):
    # R[rd] = R[rx] != sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = int(s.r[f_rx] != sx32(f_imm, 9))

def gx_andli(s, m, w, oldpc):
    # R[rd] = R[rx] & sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = (s.r[f_rx] & sx32(f_imm, 9))

def gx_orli(s, m, w, oldpc):
    # R[rd] = R[rx] | sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = (s.r[f_rx] | sx32(f_imm, 9))

def gx_xorli(s, m, w, oldpc):
    # R[rd] = R[rx] ^ sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = (s.r[f_rx] ^ sx32(f_imm, 9))

def gx_lesli(s, m, w, oldpc):
    # R[rd] = R[rx] <=s sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = int(s32(s.r[f_rx]) <= s32(sx32(f_imm, 9)))

def gx_gtsli(s, m, w, oldpc):
    # R[rd] = R[rx] >s sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = int(s32(s.r[f_rx]) > s32(sx32(f_imm, 9)))

def gx_divsli(s, m, w, oldpc):
    # R[rd] = R[rx] /s sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = divs32(s.r[f_rx], sx32(f_imm, 9))

def gx_modsli(s, m, w, oldpc):
    # R[rd] = R[rx] %s sext(imm)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = mods32(s.r[f_rx], sx32(f_imm, 9))

def gx_shrsli(s, m, w, oldpc):
    # R[rd] = R[rx] >>s (imm & 31)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = sar32(s.r[f_rx], (f_imm & 31))

def gx_bitex(s, m, w, oldpc):
    # R[rd] = (R[rx] >> (imm & 31)) & ((2 << ((imm >> 5) & 15)) - 1)
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = (shr32(s.r[f_rx], (f_imm & 31)) & ((shl32(2, (shr32(f_imm, 5) & 15)) - 1) & 0xffffffff))

def gx_rsubli(s, m, w, oldpc):
    # R[rd] = sext(imm) - R[rx]
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = ((sx32(f_imm, 9) - s.r[f_rx]) & 0xffffffff)

def gx_rdivli(s, m, w, oldpc):
    # R[rd] = sext(imm) /u R[rx]
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = divu32(sx32(f_imm, 9), s.r[f_rx])

def gx_rmodli(s, m, w, oldpc):
    # R[rd] = sext(imm) %u R[rx]
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = modu32(sx32(f_imm, 9), s.r[f_rx])

def gx_rdivsli(s, m, w, oldpc):
    # R[rd] = sext(imm) /s R[rx]
    f_rd = ((w >> 12) & 0x7)
    f_rx = ((w >> 9) & 0x7)
    f_imm = ((w >> 0) & 0x1ff)
    s.r[f_rd] = divs32(sx32(f_imm, 9), s.r[f_rx])

def gx_cbeq(s, m, w, oldpc):
    # if R[rx] == imm7 then PC = PC + sext(disp)
    f_rx = ((w >> 17) & 0x7)
    f_imm7 = ((w >> 10) & 0x7f)
    f_disp = ((w >> 0) & 0x3ff)
    if int(s.r[f_rx] == f_imm7):
        s.pc = ((s.pc + sx32(f_disp, 10)) & 0xffffffff) & 0xffff

def gx_cbne(s, m, w, oldpc):
    # if R[rx] != imm7 then PC = PC + sext(disp)
    f_rx = ((w >> 17) & 0x7)
    f_imm7 = ((w >> 10) & 0x7f)
    f_disp = ((w >> 0) & 0x3ff)
    if int(s.r[f_rx] != f_imm7):
        s.pc = ((s.pc + sx32(f_disp, 10)) & 0xffffffff) & 0xffff

def gx_add(s, m, w, oldpc):
    # R[rd] = R[rx] + R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = ((s.r[f_rx] + s.r[f_ry]) & 0xffffffff)

def gx_sub(s, m, w, oldpc):
    # R[rd] = R[rx] - R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = ((s.r[f_rx] - s.r[f_ry]) & 0xffffffff)

def gx_mul(s, m, w, oldpc):
    # R[rd] = R[rx] * R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = ((s.r[f_rx] * s.r[f_ry]) & 0xffffffff)

def gx_div(s, m, w, oldpc):
    # R[rd] = R[rx] /u R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = divu32(s.r[f_rx], s.r[f_ry])

def gx_mod(s, m, w, oldpc):
    # R[rd] = R[rx] %u R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = modu32(s.r[f_rx], s.r[f_ry])

def gx_shl(s, m, w, oldpc):
    # R[rd] = R[rx] << (R[ry] & 31)
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = shl32(s.r[f_rx], (s.r[f_ry] & 31))

def gx_shr(s, m, w, oldpc):
    # R[rd] = R[rx] >> (R[ry] & 31)
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = shr32(s.r[f_rx], (s.r[f_ry] & 31))

def gx_lt(s, m, w, oldpc):
    # R[rd] = R[rx] <u R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = int(s.r[f_rx] < s.r[f_ry])

def gx_le(s, m, w, oldpc):
    # R[rd] = R[rx] <=u R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = int(s.r[f_rx] <= s.r[f_ry])

def gx_eq(s, m, w, oldpc):
    # R[rd] = R[rx] == R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = int(s.r[f_rx] == s.r[f_ry])

def gx_ne(s, m, w, oldpc):
    # R[rd] = R[rx] != R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = int(s.r[f_rx] != s.r[f_ry])

def gx_and(s, m, w, oldpc):
    # R[rd] = R[rx] & R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = (s.r[f_rx] & s.r[f_ry])

def gx_or(s, m, w, oldpc):
    # R[rd] = R[rx] | R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = (s.r[f_rx] | s.r[f_ry])

def gx_xor(s, m, w, oldpc):
    # R[rd] = R[rx] ^ R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = (s.r[f_rx] ^ s.r[f_ry])

def gx_lts(s, m, w, oldpc):
    # R[rd] = R[rx] <s R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = int(s32(s.r[f_rx]) < s32(s.r[f_ry]))

def gx_les(s, m, w, oldpc):
    # R[rd] = R[rx] <=s R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = int(s32(s.r[f_rx]) <= s32(s.r[f_ry]))

def gx_divs(s, m, w, oldpc):
    # R[rd] = R[rx] /s R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = divs32(s.r[f_rx], s.r[f_ry])

def gx_mods(s, m, w, oldpc):
    # R[rd] = R[rx] %s R[ry]
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = mods32(s.r[f_rx], s.r[f_ry])

def gx_shrs(s, m, w, oldpc):
    # R[rd] = R[rx] >>s (R[ry] & 31)
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = sar32(s.r[f_rx], (s.r[f_ry] & 31))

def gx_fadd(s, m, w, oldpc):
    # R[rd] = fadd(R[rx], R[ry])
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = cpu4_fadd(s.r[f_rx], s.r[f_ry])

def gx_fsub(s, m, w, oldpc):
    # R[rd] = fsub(R[rx], R[ry])
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = cpu4_fsub(s.r[f_rx], s.r[f_ry])

def gx_fmul(s, m, w, oldpc):
    # R[rd] = fmul(R[rx], R[ry])
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = cpu4_fmul(s.r[f_rx], s.r[f_ry])

def gx_fdiv(s, m, w, oldpc):
    # R[rd] = fdiv(R[rx], R[ry])
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = cpu4_fdiv(s.r[f_rx], s.r[f_ry])

def gx_flt(s, m, w, oldpc):
    # R[rd] = flt(R[rx], R[ry])
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = cpu4_flt(s.r[f_rx], s.r[f_ry])

def gx_fle(s, m, w, oldpc):
    # R[rd] = fle(R[rx], R[ry])
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = cpu4_fle(s.r[f_rx], s.r[f_ry])

def gx_zxwor(s, m, w, oldpc):
    # R[rd] = zx(R[rx] | R[ry], 16)
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = ((s.r[f_rx] | s.r[f_ry]) & 65535)

def gx_sxwor(s, m, w, oldpc):
    # R[rd] = sx(R[rx] | R[ry], 16)
    f_rd = ((w >> 6) & 0x7)
    f_rx = ((w >> 3) & 0x7)
    f_ry = ((w >> 0) & 0x7)
    s.r[f_rd] = sx32((s.r[f_rx] | s.r[f_ry]), 16)

def gx_sxb(s, m, w, oldpc):
    # R[rd] = sx(R[rd], 8)
    f_rd = ((w >> 6) & 0x7)
    s.r[f_rd] = sx32(s.r[f_rd], 8)

def gx_sxw(s, m, w, oldpc):
    # R[rd] = sx(R[rd], 16)
    f_rd = ((w >> 6) & 0x7)
    s.r[f_rd] = sx32(s.r[f_rd], 16)

def gx_inc(s, m, w, oldpc):
    # R[rd] = R[rd] + 1
    f_rd = ((w >> 6) & 0x7)
    s.r[f_rd] = ((s.r[f_rd] + 1) & 0xffffffff)

def gx_dec(s, m, w, oldpc):
    # R[rd] = R[rd] - 1
    f_rd = ((w >> 6) & 0x7)
    s.r[f_rd] = ((s.r[f_rd] - 1) & 0xffffffff)

def gx_pushr(s, m, w, oldpc):
    # SP = SP - 4; M32[SP] = R[rd]
    f_rd = ((w >> 6) & 0x7)
    s.sp = ((s.sp - 4) & 0xffffffff) & 0xffff
    wr32(m, s.sp, s.r[f_rd], oldpc)

def gx_popr(s, m, w, oldpc):
    # R[rd] = M32[SP]; SP = SP + 4
    f_rd = ((w >> 6) & 0x7)
    s.r[f_rd] = rd32(m, s.sp, oldpc)
    s.sp = ((s.sp + 4) & 0xffffffff) & 0xffff

def gx_zxb(s, m, w, oldpc):
    # R[rd] = zx(R[rd], 8)
    f_rd = ((w >> 6) & 0x7)
    s.r[f_rd] = (s.r[f_rd] & 255)

def gx_zxw(s, m, w, oldpc):
    # R[rd] = zx(R[rd], 16)
    f_rd = ((w >> 6) & 0x7)
    s.r[f_rd] = (s.r[f_rd] & 65535)

def gx_itof(s, m, w, oldpc):
    # R[rd] = itof(R[rd])
    f_rd = ((w >> 6) & 0x7)
    s.r[f_rd] = cpu4_itof(s.r[f_rd])

def gx_ftoi(s, m, w, oldpc):
    # R[rd] = ftoi(R[rd])
    f_rd = ((w >> 6) & 0x7)
    s.r[f_rd] = cpu4_ftoi(s.r[f_rd])

def gx_jlr(s, m, w, oldpc):
    # LR = PC; PC = R[rd]
    f_rd = ((w >> 6) & 0x7)
    s.lr = s.pc & 0xffff
    s.pc = s.r[f_rd] & 0xffff

def gx_jr(s, m, w, oldpc):
    # PC = R[rd]
    f_rd = ((w >> 6) & 0x7)
    s.pc = s.r[f_rd] & 0xffff

def gx_ssp(s, m, w, oldpc):
    # SP = R[rd]
    f_rd = ((w >> 6) & 0x7)
    s.sp = s.r[f_rd] & 0xffff

def gx_neg(s, m, w, oldpc):
    # R[rd] = -R[rd]
    f_rd = ((w >> 6) & 0x7)
    s.r[f_rd] = ((-s.r[f_rd]) & 0xffffffff)

def gx_frecip(s, m, w, oldpc):
    # R[rd] = frecip(R[rd])
    f_rd = ((w >> 6) & 0x7)
    s.r[f_rd] = cpu4_frecip(s.r[f_rd])

def gx_frsqrt(s, m, w, oldpc):
    # R[rd] = frsqrt(R[rd])
    f_rd = ((w >> 6) & 0x7)
    s.r[f_rd] = cpu4_frsqrt(s.r[f_rd])

def gx_putchar(s, m, w, oldpc):
    # putchar(R[rd])
    f_rd = ((w >> 6) & 0x7)
    putc(s.r[f_rd])

def gx_lb(s, m, w, oldpc):
    # R[rx] = M8[lo16(BP + sext(imm))]
    f_rx = ((w >> 7) & 0x7)
    f_imm = ((w >> 0) & 0x7f)
    s.r[f_rx] = rd8(m, (((s.bp + sx32(f_imm, 7)) & 0xffffffff) & 0xffff), oldpc)

def gx_lw(s, m, w, oldpc):
    # R[rx] = M16[lo16(BP + sext(imm) * 2)]
    f_rx = ((w >> 7) & 0x7)
    f_imm = ((w >> 0) & 0x7f)
    s.r[f_rx] = rd16(m, (((s.bp + ((sx32(f_imm, 7) * 2) & 0xffffffff)) & 0xffffffff) & 0xffff), oldpc)

def gx_ll(s, m, w, oldpc):
    # R[rx] = M32[lo16(BP + sext(imm) * 4)]
    f_rx = ((w >> 7) & 0x7)
    f_imm = ((w >> 0) & 0x7f)
    s.r[f_rx] = rd32(m, (((s.bp + ((sx32(f_imm, 7) * 4) & 0xffffffff)) & 0xffffffff) & 0xffff), oldpc)

def gx_sb(s, m, w, oldpc):
    # M8[lo16(BP + sext(imm))] = R[rx]
    f_rx = ((w >> 7) & 0x7)
    f_imm = ((w >> 0) & 0x7f)
    wr8(m, (((s.bp + sx32(f_imm, 7)) & 0xffffffff) & 0xffff), s.r[f_rx], oldpc)

def gx_sw(s, m, w, oldpc):
    # M16[lo16(BP + sext(imm) * 2)] = R[rx]
    f_rx = ((w >> 7) & 0x7)
    f_imm = ((w >> 0) & 0x7f)
    wr16(m, (((s.bp + ((sx32(f_imm, 7) * 2) & 0xffffffff)) & 0xffffffff) & 0xffff), s.r[f_rx], oldpc)

def gx_sl(s, m, w, oldpc):
    # M32[lo16(BP + sext(imm) * 4)] = R[rx]
    f_rx = ((w >> 7) & 0x7)
    f_imm = ((w >> 0) & 0x7f)
    wr32(m, (((s.bp + ((sx32(f_imm, 7) * 4) & 0xffffffff)) & 0xffffffff) & 0xffff), s.r[f_rx], oldpc)

def gx_lbx(s, m, w, oldpc):
    # R[rx] = sx(M8[lo16(BP + sext(imm))], 8)
    f_rx = ((w >> 7) & 0x7)
    f_imm = ((w >> 0) & 0x7f)
    s.r[f_rx] = sx32(rd8(m, (((s.bp + sx32(f_imm, 7)) & 0xffffffff) & 0xffff), oldpc), 8)

def gx_lwx(s, m, w, oldpc):
    # R[rx] = sx(M16[lo16(BP + sext(imm) * 2)], 16)
    f_rx = ((w >> 7) & 0x7)
    f_imm = ((w >> 0) & 0x7f)
    s.r[f_rx] = sx32(rd16(m, (((s.bp + ((sx32(f_imm, 7) * 2) & 0xffffffff)) & 0xffffffff) & 0xffff), oldpc), 16)

def gx_addi(s, m, w, oldpc):
    # R[rx] = R[rx] + sext(imm)
    f_rx = ((w >> 7) & 0x7)
    f_imm = ((w >> 0) & 0x7f)
    s.r[f_rx] = ((s.r[f_rx] + sx32(f_imm, 7)) & 0xffffffff)

def gx_shli(s, m, w, oldpc):
    # R[rx] = R[rx] << (imm & 31)
    f_rx = ((w >> 7) & 0x7)
    f_imm = ((w >> 0) & 0x7f)
    s.r[f_rx] = shl32(s.r[f_rx], (f_imm & 31))

def gx_andi(s, m, w, oldpc):
    # R[rx] = R[rx] & imm
    f_rx = ((w >> 7) & 0x7)
    f_imm = ((w >> 0) & 0x7f)
    s.r[f_rx] = (s.r[f_rx] & f_imm)

def gx_shrsi(s, m, w, oldpc):
    # R[rx] = R[rx] >>s (imm & 31)
    f_rx = ((w >> 7) & 0x7)
    f_imm = ((w >> 0) & 0x7f)
    s.r[f_rx] = sar32(s.r[f_rx], (f_imm & 31))

def gx_imms(s, m, w, oldpc):
    # R[rx] = sext(imm)
    f_rx = ((w >> 7) & 0x7)
    f_imm = ((w >> 0) & 0x7f)
    s.r[f_rx] = sx32(f_imm, 7)

def gx_j(s, m, w, oldpc):
    # PC = imm
    f_imm = ((w >> 0) & 0xffff)
    s.pc = f_imm & 0xffff

def gx_jl(s, m, w, oldpc):
    # LR = PC; PC = imm
    f_imm = ((w >> 0) & 0xffff)
    s.lr = s.pc & 0xffff
    s.pc = f_imm & 0xffff

def gx_enter(s, m, w, oldpc):
    # M32[lo16(SP - 4)] = (LR << 16) | BP; BP = SP - 4; SP = SP - imm - 4
    f_imm = ((w >> 0) & 0xffff)
    wr32(m, (((s.sp - 4) & 0xffffffff) & 0xffff), (shl32(s.lr, 16) | s.bp), oldpc)
    s.bp = ((s.sp - 4) & 0xffffffff) & 0xffff
    s.sp = ((((s.sp - f_imm) & 0xffffffff) - 4) & 0xffffffff) & 0xffff

def gx_adjw(s, m, w, oldpc):
    # SP = SP + sext(imm) * 4
    f_imm = ((w >> 0) & 0x3fff)
    s.sp = ((s.sp + ((sx32(f_imm, 14) * 4) & 0xffffffff)) & 0xffffffff) & 0xffff

def gx_lea(s, m, w, oldpc):
    # R[rd] = lo16(BP + sext(imm) * 4)
    f_rd = ((w >> 14) & 0x7)
    f_imm = ((w >> 0) & 0x3fff)
    s.r[f_rd] = (((s.bp + ((sx32(f_imm, 14) * 4) & 0xffffffff)) & 0xffffffff) & 0xffff)

def gx_llb(s, m, w, oldpc):
    # R[rx] = M8[R[ry] + sext(imm)]
    f_rx = ((w >> 13) & 0x7)
    f_ry = ((w >> 10) & 0x7)
    f_imm = ((w >> 0) & 0x3ff)
    s.r[f_rx] = rd8(m, ((s.r[f_ry] + sx32(f_imm, 10)) & 0xffffffff), oldpc)

def gx_llw(s, m, w, oldpc):
    # R[rx] = M16[R[ry] + sext(imm) * 2]
    f_rx = ((w >> 13) & 0x7)
    f_ry = ((w >> 10) & 0x7)
    f_imm = ((w >> 0) & 0x3ff)
    s.r[f_rx] = rd16(m, ((s.r[f_ry] + ((sx32(f_imm, 10) * 2) & 0xffffffff)) & 0xffffffff), oldpc)

def gx_lll(s, m, w, oldpc):
    # R[rx] = M32[R[ry] + sext(imm) * 4]
    f_rx = ((w >> 13) & 0x7)
    f_ry = ((w >> 10) & 0x7)
    f_imm = ((w >> 0) & 0x3ff)
    s.r[f_rx] = rd32(m, ((s.r[f_ry] + ((sx32(f_imm, 10) * 4) & 0xffffffff)) & 0xffffffff), oldpc)

def gx_slb(s, m, w, oldpc):
    # M8[R[ry] + sext(imm)] = R[rx]
    f_rx = ((w >> 13) & 0x7)
    f_ry = ((w >> 10) & 0x7)
    f_imm = ((w >> 0) & 0x3ff)
    wr8(m, ((s.r[f_ry] + sx32(f_imm, 10)) & 0xffffffff), s.r[f_rx], oldpc)

def gx_slw(s, m, w, oldpc):
    # M16[R[ry] + sext(imm) * 2] = R[rx]
    f_rx = ((w >> 13) & 0x7)
    f_ry = ((w >> 10) & 0x7)
    f_imm = ((w >> 0) & 0x3ff)
    wr16(m, ((s.r[f_ry] + ((sx32(f_imm, 10) * 2) & 0xffffffff)) & 0xffffffff), s.r[f_rx], oldpc)

def gx_sll(s, m, w, oldpc):
    # M32[R[ry] + sext(imm) * 4] = R[rx]
    f_rx = ((w >> 13) & 0x7)
    f_ry = ((w >> 10) & 0x7)
    f_imm = ((w >> 0) & 0x3ff)
    wr32(m, ((s.r[f_ry] + ((sx32(f_imm, 10) * 4) & 0xffffffff)) & 0xffffffff), s.r[f_rx], oldpc)

def gx_llbx(s, m, w, oldpc):
    # R[rx] = sx(M8[R[ry] + sext(imm)], 8)
    f_rx = ((w >> 13) & 0x7)
    f_ry = ((w >> 10) & 0x7)
    f_imm = ((w >> 0) & 0x3ff)
    s.r[f_rx] = sx32(rd8(m, ((s.r[f_ry] + sx32(f_imm, 10)) & 0xffffffff), oldpc), 8)

def gx_llwx(s, m, w, oldpc):
    # R[rx] = sx(M16[R[ry] + sext(imm) * 2], 16)
    f_rx = ((w >> 13) & 0x7)
    f_ry = ((w >> 10) & 0x7)
    f_imm = ((w >> 0) & 0x3ff)
    s.r[f_rx] = sx32(rd16(m, ((s.r[f_ry] + ((sx32(f_imm, 10) * 2) & 0xffffffff)) & 0xffffffff), oldpc), 16)

def gx_beq(s, m, w, oldpc):
    # if R[rx] == R[ry] then PC = PC + sext(disp)
    f_rx = ((w >> 13) & 0x7)
    f_ry = ((w >> 10) & 0x7)
    f_disp = ((w >> 0) & 0x3ff)
    if int(s.r[f_rx] == s.r[f_ry]):
        s.pc = ((s.pc + sx32(f_disp, 10)) & 0xffffffff) & 0xffff

def gx_bne(s, m, w, oldpc):
    # if R[rx] != R[ry] then PC = PC + sext(disp)
    f_rx = ((w >> 13) & 0x7)
    f_ry = ((w >> 10) & 0x7)
    f_disp = ((w >> 0) & 0x3ff)
    if int(s.r[f_rx] != s.r[f_ry]):
        s.pc = ((s.pc + sx32(f_disp, 10)) & 0xffffffff) & 0xffff

def gx_blt(s, m, w, oldpc):
    # if R[rx] <u R[ry] then PC = PC + sext(disp)
    f_rx = ((w >> 13) & 0x7)
    f_ry = ((w >> 10) & 0x7)
    f_disp = ((w >> 0) & 0x3ff)
    if int(s.r[f_rx] < s.r[f_ry]):
        s.pc = ((s.pc + sx32(f_disp, 10)) & 0xffffffff) & 0xffff

def gx_ble(s, m, w, oldpc):
    # if R[rx] <=u R[ry] then PC = PC + sext(disp)
    f_rx = ((w >> 13) & 0x7)
    f_ry = ((w >> 10) & 0x7)
    f_disp = ((w >> 0) & 0x3ff)
    if int(s.r[f_rx] <= s.r[f_ry]):
        s.pc = ((s.pc + sx32(f_disp, 10)) & 0xffffffff) & 0xffff

def gx_blts(s, m, w, oldpc):
    # if R[rx] <s R[ry] then PC = PC + sext(disp)
    f_rx = ((w >> 13) & 0x7)
    f_ry = ((w >> 10) & 0x7)
    f_disp = ((w >> 0) & 0x3ff)
    if int(s32(s.r[f_rx]) < s32(s.r[f_ry])):
        s.pc = ((s.pc + sx32(f_disp, 10)) & 0xffffffff) & 0xffff

def gx_bles(s, m, w, oldpc):
    # if R[rx] <=s R[ry] then PC = PC + sext(disp)
    f_rx = ((w >> 13) & 0x7)
    f_ry = ((w >> 10) & 0x7)
    f_disp = ((w >> 0) & 0x3ff)
    if int(s32(s.r[f_rx]) <= s32(s.r[f_ry])):
        s.pc = ((s.pc + sx32(f_disp, 10)) & 0xffffffff) & 0xffff

def gx_beqz(s, m, w, oldpc):
    # if R[rx] == 0 then PC = PC + sext(disp)
    f_rx = ((w >> 13) & 0x7)
    f_disp = ((w >> 0) & 0x3ff)
    if int(s.r[f_rx] == 0):
        s.pc = ((s.pc + sx32(f_disp, 10)) & 0xffffffff) & 0xffff

def gx_bnez(s, m, w, oldpc):
    # if R[rx] != 0 then PC = PC + sext(disp)
    f_rx = ((w >> 13) & 0x7)
    f_disp = ((w >> 0) & 0x3ff)
    if int(s.r[f_rx] != 0):
        s.pc = ((s.pc + sx32(f_disp, 10)) & 0xffffffff) & 0xffff

def gx_dbnz(s, m, w, oldpc):
    # R[rx] = R[rx] - 1; if R[rx] != 0 then PC = PC + sext(disp)
    f_rx = ((w >> 13) & 0x7)
    f_disp = ((w >> 0) & 0x3ff)
    s.r[f_rx] = ((s.r[f_rx] - 1) & 0xffffffff)
    if int(s.r[f_rx] != 0):
        s.pc = ((s.pc + sx32(f_disp, 10)) & 0xffffffff) & 0xffff

def gx_bltz(s, m, w, oldpc):
    # if R[rx] <s 0 then PC = PC + sext(disp)
    f_rx = ((w >> 13) & 0x7)
    f_disp = ((w >> 0) & 0x3ff)
    if int(s32(s.r[f_rx]) < s32(0)):
        s.pc = ((s.pc + sx32(f_disp, 10)) & 0xffffffff) & 0xffff

def gx_bgez(s, m, w, oldpc):
    # if R[rx] >=s 0 then PC = PC + sext(disp)
    f_rx = ((w >> 13) & 0x7)
    f_disp = ((w >> 0) & 0x3ff)
    if int(s32(s.r[f_rx]) >= s32(0)):
        s.pc = ((s.pc + sx32(f_disp, 10)) & 0xffffffff) & 0xffff

def gx_bgtz(s, m, w, oldpc):
    # if R[rx] >s 0 then PC = PC + sext(disp)
    f_rx = ((w >> 13) & 0x7)
    f_disp = ((w >> 0) & 0x3ff)
    if int(s32(s.r[f_rx]) > s32(0)):
        s.pc = ((s.pc + sx32(f_disp, 10)) & 0xffffffff) & 0xffff

def gx_blez(s, m, w, oldpc):
    # if R[rx] <=s 0 then PC = PC + sext(disp)
    f_rx = ((w >> 13) & 0x7)
    f_disp = ((w >> 0) & 0x3ff)
    if int(s32(s.r[f_rx]) <= s32(0)):
        s.pc = ((s.pc + sx32(f_disp, 10)) & 0xffffffff) & 0xffff

def gx_immw(s, m, w, oldpc):
    # R[rx] = imm
    f_rx = ((w >> 16) & 0x7)
    f_imm = ((w >> 0) & 0xffff)
    s.r[f_rx] = f_imm

def gx_immwh(s, m, w, oldpc):
    # R[rx] = zx(R[rx], 16) | (imm << 16)
    f_rx = ((w >> 16) & 0x7)
    f_imm = ((w >> 0) & 0xffff)
    s.r[f_rx] = ((s.r[f_rx] & 65535) | shl32(f_imm, 16))

def gx_jz(s, m, w, oldpc):
    # if R[rx] == 0 then PC = imm
    f_rx = ((w >> 16) & 0x7)
    f_imm = ((w >> 0) & 0xffff)
    if int(s.r[f_rx] == 0):
        s.pc = f_imm & 0xffff

def gx_jnz(s, m, w, oldpc):
    # if R[rx] != 0 then PC = imm
    f_rx = ((w >> 16) & 0x7)
    f_imm = ((w >> 0) & 0xffff)
    if int(s.r[f_rx] != 0):
        s.pc = f_imm & 0xffff

def check(s, oldpc):
    if (s.sp & 3):
        sys.stderr.write('CPU4 alignment error: SP misaligned (0x%x) at pc=0x%04x\n' % ((s.sp & 3), oldpc)); s.H = 1
    if (s.bp & 3):
        sys.stderr.write('CPU4 alignment error: BP misaligned (0x%x) at pc=0x%04x\n' % ((s.bp & 3), oldpc)); s.H = 1
    pass

def _key0(w): return ((w >> 15) & 0x1)
def _key1(w): return ((w >> 0) & 0x3f)
def _key2(w): return ((w >> 10) & 0x7)

DECODE = {
    0x00: (1, gx_halt, None, None),
    0x01: (1, gx_ret, None, None),
    0x02: (1, gx_zero0, None, None),
    0x03: (1, gx_zero1, None, None),
    0x04: (1, gx_zero2, None, None),
    0x05: (1, gx_zero3, None, None),
    0x06: (1, gx_zero4, None, None),
    0x07: (1, gx_zero5, None, None),
    0x08: (1, gx_zero6, None, None),
    0x09: (1, gx_zero7, None, None),
    0x10: (3, None, _key0, {0x0: gx_addli, 0x1: gx_subli}),
    0x11: (3, None, _key0, {0x0: gx_mulli, 0x1: gx_divli}),
    0x12: (3, None, _key0, {0x0: gx_modli, 0x1: gx_shlli}),
    0x13: (3, None, _key0, {0x0: gx_shrli, 0x1: gx_leli}),
    0x14: (3, None, _key0, {0x0: gx_gtli, 0x1: gx_eqli}),
    0x15: (3, None, _key0, {0x0: gx_neli, 0x1: gx_andli}),
    0x16: (3, None, _key0, {0x0: gx_orli, 0x1: gx_xorli}),
    0x17: (3, None, _key0, {0x0: gx_lesli, 0x1: gx_gtsli}),
    0x18: (3, None, _key0, {0x0: gx_divsli, 0x1: gx_modsli}),
    0x19: (3, None, _key0, {0x0: gx_shrsli, 0x1: gx_bitex}),
    0x1a: (3, None, _key0, {0x0: gx_rsubli, 0x1: gx_rdivli}),
    0x1b: (3, None, _key0, {0x0: gx_rmodli, 0x1: gx_rdivsli}),
    0x20: (3, gx_cbeq, None, None),
    0x21: (3, gx_cbeq, None, None),
    0x22: (3, gx_cbeq, None, None),
    0x23: (3, gx_cbeq, None, None),
    0x24: (3, gx_cbeq, None, None),
    0x25: (3, gx_cbeq, None, None),
    0x26: (3, gx_cbeq, None, None),
    0x27: (3, gx_cbeq, None, None),
    0x28: (3, gx_cbeq, None, None),
    0x29: (3, gx_cbeq, None, None),
    0x2a: (3, gx_cbeq, None, None),
    0x2b: (3, gx_cbeq, None, None),
    0x2c: (3, gx_cbeq, None, None),
    0x2d: (3, gx_cbeq, None, None),
    0x2e: (3, gx_cbeq, None, None),
    0x2f: (3, gx_cbeq, None, None),
    0x30: (3, gx_cbne, None, None),
    0x31: (3, gx_cbne, None, None),
    0x32: (3, gx_cbne, None, None),
    0x33: (3, gx_cbne, None, None),
    0x34: (3, gx_cbne, None, None),
    0x35: (3, gx_cbne, None, None),
    0x36: (3, gx_cbne, None, None),
    0x37: (3, gx_cbne, None, None),
    0x38: (3, gx_cbne, None, None),
    0x39: (3, gx_cbne, None, None),
    0x3a: (3, gx_cbne, None, None),
    0x3b: (3, gx_cbne, None, None),
    0x3c: (3, gx_cbne, None, None),
    0x3d: (3, gx_cbne, None, None),
    0x3e: (3, gx_cbne, None, None),
    0x3f: (3, gx_cbne, None, None),
    0x40: (2, gx_add, None, None),
    0x41: (2, gx_add, None, None),
    0x42: (2, gx_sub, None, None),
    0x43: (2, gx_sub, None, None),
    0x44: (2, gx_mul, None, None),
    0x45: (2, gx_mul, None, None),
    0x46: (2, gx_div, None, None),
    0x47: (2, gx_div, None, None),
    0x48: (2, gx_mod, None, None),
    0x49: (2, gx_mod, None, None),
    0x4a: (2, gx_shl, None, None),
    0x4b: (2, gx_shl, None, None),
    0x4c: (2, gx_shr, None, None),
    0x4d: (2, gx_shr, None, None),
    0x4e: (2, gx_lt, None, None),
    0x4f: (2, gx_lt, None, None),
    0x50: (2, gx_le, None, None),
    0x51: (2, gx_le, None, None),
    0x52: (2, gx_eq, None, None),
    0x53: (2, gx_eq, None, None),
    0x54: (2, gx_ne, None, None),
    0x55: (2, gx_ne, None, None),
    0x56: (2, gx_and, None, None),
    0x57: (2, gx_and, None, None),
    0x58: (2, gx_or, None, None),
    0x59: (2, gx_or, None, None),
    0x5a: (2, gx_xor, None, None),
    0x5b: (2, gx_xor, None, None),
    0x5c: (2, gx_lts, None, None),
    0x5d: (2, gx_lts, None, None),
    0x5e: (2, gx_les, None, None),
    0x5f: (2, gx_les, None, None),
    0x60: (2, gx_divs, None, None),
    0x61: (2, gx_divs, None, None),
    0x62: (2, gx_mods, None, None),
    0x63: (2, gx_mods, None, None),
    0x64: (2, gx_shrs, None, None),
    0x65: (2, gx_shrs, None, None),
    0x66: (2, gx_fadd, None, None),
    0x67: (2, gx_fadd, None, None),
    0x68: (2, gx_fsub, None, None),
    0x69: (2, gx_fsub, None, None),
    0x6a: (2, gx_fmul, None, None),
    0x6b: (2, gx_fmul, None, None),
    0x6c: (2, gx_fdiv, None, None),
    0x6d: (2, gx_fdiv, None, None),
    0x6e: (2, gx_flt, None, None),
    0x6f: (2, gx_flt, None, None),
    0x70: (2, gx_fle, None, None),
    0x71: (2, gx_fle, None, None),
    0x72: (2, gx_zxwor, None, None),
    0x73: (2, gx_zxwor, None, None),
    0x74: (2, gx_sxwor, None, None),
    0x75: (2, gx_sxwor, None, None),
    0x7e: (2, None, _key1, {0x0: gx_sxb, 0x1: gx_sxw, 0x2: gx_inc, 0x3: gx_dec, 0x4: gx_pushr, 0x5: gx_popr, 0x6: gx_zxb, 0x7: gx_zxw, 0x8: gx_itof, 0x9: gx_ftoi, 0xa: gx_jlr, 0xb: gx_jr, 0xc: gx_ssp, 0xd: gx_neg, 0xe: gx_frecip, 0xf: gx_frsqrt, 0x3f: gx_putchar}),
    0x7f: (2, None, _key1, {0x0: gx_sxb, 0x1: gx_sxw, 0x2: gx_inc, 0x3: gx_dec, 0x4: gx_pushr, 0x5: gx_popr, 0x6: gx_zxb, 0x7: gx_zxw, 0x8: gx_itof, 0x9: gx_ftoi, 0xa: gx_jlr, 0xb: gx_jr, 0xc: gx_ssp, 0xd: gx_neg, 0xe: gx_frecip, 0xf: gx_frsqrt, 0x3f: gx_putchar}),
    0x80: (2, gx_lb, None, None),
    0x81: (2, gx_lb, None, None),
    0x82: (2, gx_lb, None, None),
    0x83: (2, gx_lb, None, None),
    0x84: (2, gx_lw, None, None),
    0x85: (2, gx_lw, None, None),
    0x86: (2, gx_lw, None, None),
    0x87: (2, gx_lw, None, None),
    0x88: (2, gx_ll, None, None),
    0x89: (2, gx_ll, None, None),
    0x8a: (2, gx_ll, None, None),
    0x8b: (2, gx_ll, None, None),
    0x8c: (2, gx_sb, None, None),
    0x8d: (2, gx_sb, None, None),
    0x8e: (2, gx_sb, None, None),
    0x8f: (2, gx_sb, None, None),
    0x90: (2, gx_sw, None, None),
    0x91: (2, gx_sw, None, None),
    0x92: (2, gx_sw, None, None),
    0x93: (2, gx_sw, None, None),
    0x94: (2, gx_sl, None, None),
    0x95: (2, gx_sl, None, None),
    0x96: (2, gx_sl, None, None),
    0x97: (2, gx_sl, None, None),
    0x98: (2, gx_lbx, None, None),
    0x99: (2, gx_lbx, None, None),
    0x9a: (2, gx_lbx, None, None),
    0x9b: (2, gx_lbx, None, None),
    0x9c: (2, gx_lwx, None, None),
    0x9d: (2, gx_lwx, None, None),
    0x9e: (2, gx_lwx, None, None),
    0x9f: (2, gx_lwx, None, None),
    0xa0: (2, gx_addi, None, None),
    0xa1: (2, gx_addi, None, None),
    0xa2: (2, gx_addi, None, None),
    0xa3: (2, gx_addi, None, None),
    0xa4: (2, gx_shli, None, None),
    0xa5: (2, gx_shli, None, None),
    0xa6: (2, gx_shli, None, None),
    0xa7: (2, gx_shli, None, None),
    0xa8: (2, gx_andi, None, None),
    0xa9: (2, gx_andi, None, None),
    0xaa: (2, gx_andi, None, None),
    0xab: (2, gx_andi, None, None),
    0xac: (2, gx_shrsi, None, None),
    0xad: (2, gx_shrsi, None, None),
    0xae: (2, gx_shrsi, None, None),
    0xaf: (2, gx_shrsi, None, None),
    0xb0: (2, gx_imms, None, None),
    0xb1: (2, gx_imms, None, None),
    0xb2: (2, gx_imms, None, None),
    0xb3: (2, gx_imms, None, None),
    0xc0: (3, gx_j, None, None),
    0xc1: (3, gx_jl, None, None),
    0xc2: (3, gx_enter, None, None),
    0xc4: (3, gx_adjw, None, None),
    0xc5: (3, gx_adjw, None, None),
    0xc6: (3, gx_lea, None, None),
    0xc7: (3, gx_lea, None, None),
    0xd0: (3, gx_llb, None, None),
    0xd1: (3, gx_llw, None, None),
    0xd2: (3, gx_lll, None, None),
    0xd3: (3, gx_slb, None, None),
    0xd4: (3, gx_slw, None, None),
    0xd5: (3, gx_sll, None, None),
    0xd6: (3, gx_llbx, None, None),
    0xd7: (3, gx_llwx, None, None),
    0xd8: (3, gx_beq, None, None),
    0xd9: (3, gx_bne, None, None),
    0xda: (3, gx_blt, None, None),
    0xdb: (3, gx_ble, None, None),
    0xdc: (3, gx_blts, None, None),
    0xdd: (3, gx_bles, None, None),
    0xdf: (3, None, _key2, {0x0: gx_beqz, 0x1: gx_bnez, 0x2: gx_dbnz, 0x3: gx_bltz, 0x4: gx_bgez, 0x5: gx_bgtz, 0x6: gx_blez}),
    0xe0: (3, gx_immw, None, None),
    0xe1: (3, gx_immw, None, None),
    0xe2: (3, gx_immw, None, None),
    0xe3: (3, gx_immw, None, None),
    0xe4: (3, gx_immw, None, None),
    0xe5: (3, gx_immw, None, None),
    0xe6: (3, gx_immw, None, None),
    0xe7: (3, gx_immw, None, None),
    0xe8: (3, gx_immwh, None, None),
    0xe9: (3, gx_immwh, None, None),
    0xea: (3, gx_immwh, None, None),
    0xeb: (3, gx_immwh, None, None),
    0xec: (3, gx_immwh, None, None),
    0xed: (3, gx_immwh, None, None),
    0xee: (3, gx_immwh, None, None),
    0xef: (3, gx_immwh, None, None),
    0xf0: (3, gx_jz, None, None),
    0xf1: (3, gx_jz, None, None),
    0xf2: (3, gx_jz, None, None),
    0xf3: (3, gx_jz, None, None),
    0xf4: (3, gx_jz, None, None),
    0xf5: (3, gx_jz, None, None),
    0xf6: (3, gx_jz, None, None),
    0xf7: (3, gx_jz, None, None),
    0xf8: (3, gx_jnz, None, None),
    0xf9: (3, gx_jnz, None, None),
    0xfa: (3, gx_jnz, None, None),
    0xfb: (3, gx_jnz, None, None),
    0xfc: (3, gx_jnz, None, None),
    0xfd: (3, gx_jnz, None, None),
    0xfe: (3, gx_jnz, None, None),
    0xff: (3, gx_jnz, None, None),
}

def step(s, m):
    """Execute one instruction; returns its length in bytes."""
    oldpc = s.pc
    e = DECODE.get(m.read8(oldpc, False))
    if e is None:
        unknown(s, m.read8(oldpc, False), oldpc); s.pc = (oldpc + 1) & 0xffff
        check(s, oldpc)
        return 1
    n, fn, key, table = e
    w = 0
    for i in range(n):
        w = (w << 8) | m.read8((oldpc + i) & 0xffff, False)
    s.pc = (oldpc + n) & 0xffff
    if fn is None:
        fn = table.get(key(w))
    if fn is None:
        unknown(s, w, oldpc)
    else:
        fn(s, m, w, oldpc)
    check(s, oldpc)
    return n
