/* Generated by cpu4/gen_isa.py from cpu4/isa.py (SEMANTICS) -- do not edit; edit isa.py and run `make isa`. */
/* A complete fetch/decode/execute step for CPU4, generated from the
 * format templates, opcode values and semantics lines in cpu4/isa.py.
 * Included by sim_c.c after its memory helpers: this is the executor sim_c runs. */
#ifndef CPU4_EXEC_GEN_H
#define CPU4_EXEC_GEN_H
static uint32_t sx32(uint32_t v, int n) { uint32_t m = 1u << (n - 1); v &= (n == 32) ? 0xffffffffu : ((1u << n) - 1); return (v ^ m) - m; }
static uint32_t shl32(uint32_t a, uint32_t b) { return b >= 32 ? 0 : a << b; }
static uint32_t shr32(uint32_t a, uint32_t b) { return b >= 32 ? 0 : a >> b; }
static uint32_t sar32(uint32_t a, uint32_t b) { return b >= 32 ? ((int32_t)a < 0 ? 0xffffffffu : 0) : (uint32_t)((int32_t)a >> b); }
static uint32_t divu32(uint32_t a, uint32_t b) { return b ? a / b : 0; }
static uint32_t modu32(uint32_t a, uint32_t b) { return b ? a % b : 0; }
static uint32_t divs32(uint32_t a, uint32_t b) { if (!b) return 0; if (a == 0x80000000u && b == 0xffffffffu) return a; return (uint32_t)((int32_t)a / (int32_t)b); }
static uint32_t mods32(uint32_t a, uint32_t b) { if (!b) return 0; if (a == 0x80000000u && b == 0xffffffffu) return 0; return (uint32_t)((int32_t)a % (int32_t)b); }
static uint32_t gen_rd8 (uint32_t a, uint16_t pc) { (void)pc; return read8(a); }
static uint32_t gen_rd16(uint32_t a, uint16_t pc) { check_align16(a, pc); return read16(a); }
static uint32_t gen_rd32(uint32_t a, uint16_t pc) { check_align32(a, pc); return read32(a); }
static void gen_wr8 (uint32_t a, uint32_t v, uint16_t pc) { (void)pc; write8(a, (uint8_t)v); }
static void gen_wr16(uint32_t a, uint32_t v, uint16_t pc) { check_align16(a, pc); write16(a, (uint16_t)v); }
static void gen_wr32(uint32_t a, uint32_t v, uint16_t pc) { check_align32(a, pc); write32(a, v); }
static void gen_putchar(uint32_t v) { fputc((int)(v & 0xff), stderr); fflush(stderr); }
static uint32_t gen_fetch(uint16_t a, int n) { uint32_t w = 0; for (int i = 0; i < n; i++) w = (w << 8) | read8((uint16_t)(a + i)); return w; }

/* halt: H = 1 */
static void gx_halt(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->H = (0x1u) & 1u;
}

/* ret: SP = BP; BP = M32[SP]; PC = M32[SP] >> 16; SP = SP + 4 */
static void gx_ret(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->sp = (uint16_t)((uint32_t)cc->bp);
    cc->bp = (uint16_t)(gen_rd32((uint32_t)cc->sp, oldpc));
    cc->pc = (uint16_t)(shr32(gen_rd32((uint32_t)cc->sp, oldpc), 0x10u));
    cc->sp = (uint16_t)((uint32_t)((uint32_t)cc->sp + 0x4u));
}

/* zero0: R[0] = 0 */
static void gx_zero0(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[0] = 0x0u;
}

/* zero1: R[1] = 0 */
static void gx_zero1(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[1] = 0x0u;
}

/* zero2: R[2] = 0 */
static void gx_zero2(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[2] = 0x0u;
}

/* zero3: R[3] = 0 */
static void gx_zero3(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[3] = 0x0u;
}

/* zero4: R[4] = 0 */
static void gx_zero4(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[4] = 0x0u;
}

/* zero5: R[5] = 0 */
static void gx_zero5(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[5] = 0x0u;
}

/* zero6: R[6] = 0 */
static void gx_zero6(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[6] = 0x0u;
}

/* zero7: R[7] = 0 */
static void gx_zero7(Core *cc, uint32_t w, uint16_t oldpc) {
    (void)w; (void)oldpc;
    cc->r[7] = 0x0u;
}

/* addli: R[rd] = R[rx] + sext(imm) */
static void gx_addli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] + sx32(f_imm, 9));
}

/* subli: R[rd] = R[rx] - sext(imm) */
static void gx_subli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] - sx32(f_imm, 9));
}

/* mulli: R[rd] = R[rx] * sext(imm) */
static void gx_mulli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] * sx32(f_imm, 9));
}

/* divli: R[rd] = R[rx] /u sext(imm) */
static void gx_divli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = divu32(cc->r[f_rx], sx32(f_imm, 9));
}

/* modli: R[rd] = R[rx] %u sext(imm) */
static void gx_modli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = modu32(cc->r[f_rx], sx32(f_imm, 9));
}

/* shlli: R[rd] = R[rx] << (imm & 31) */
static void gx_shlli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = shl32(cc->r[f_rx], (uint32_t)(f_imm & 0x1fu));
}

/* shrli: R[rd] = R[rx] >> (imm & 31) */
static void gx_shrli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = shr32(cc->r[f_rx], (uint32_t)(f_imm & 0x1fu));
}

/* leli: R[rd] = R[rx] <=u sext(imm) */
static void gx_leli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] <= sx32(f_imm, 9));
}

/* gtli: R[rd] = R[rx] >u sext(imm) */
static void gx_gtli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] > sx32(f_imm, 9));
}

/* eqli: R[rd] = R[rx] == sext(imm) */
static void gx_eqli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] == sx32(f_imm, 9));
}

/* neli: R[rd] = R[rx] != sext(imm) */
static void gx_neli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] != sx32(f_imm, 9));
}

/* andli: R[rd] = R[rx] & sext(imm) */
static void gx_andli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] & sx32(f_imm, 9));
}

/* orli: R[rd] = R[rx] | sext(imm) */
static void gx_orli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] | sx32(f_imm, 9));
}

/* xorli: R[rd] = R[rx] ^ sext(imm) */
static void gx_xorli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] ^ sx32(f_imm, 9));
}

/* lesli: R[rd] = R[rx] <=s sext(imm) */
static void gx_lesli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)((int32_t)cc->r[f_rx] <= (int32_t)sx32(f_imm, 9));
}

/* gtsli: R[rd] = R[rx] >s sext(imm) */
static void gx_gtsli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)((int32_t)cc->r[f_rx] > (int32_t)sx32(f_imm, 9));
}

/* divsli: R[rd] = R[rx] /s sext(imm) */
static void gx_divsli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = divs32(cc->r[f_rx], sx32(f_imm, 9));
}

/* modsli: R[rd] = R[rx] %s sext(imm) */
static void gx_modsli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = mods32(cc->r[f_rx], sx32(f_imm, 9));
}

/* shrsli: R[rd] = R[rx] >>s (imm & 31) */
static void gx_shrsli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = sar32(cc->r[f_rx], (uint32_t)(f_imm & 0x1fu));
}

/* bitex: R[rd] = (R[rx] >> (imm & 31)) & ((2 << ((imm >> 5) & 15)) - 1) */
static void gx_bitex(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(shr32(cc->r[f_rx], (uint32_t)(f_imm & 0x1fu)) & (uint32_t)(shl32(0x2u, (uint32_t)(shr32(f_imm, 0x5u) & 0xfu)) - 0x1u));
}

/* rsubli: R[rd] = sext(imm) - R[rx] */
static void gx_rsubli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(sx32(f_imm, 9) - cc->r[f_rx]);
}

/* rdivli: R[rd] = sext(imm) /u R[rx] */
static void gx_rdivli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = divu32(sx32(f_imm, 9), cc->r[f_rx]);
}

/* rmodli: R[rd] = sext(imm) %u R[rx] */
static void gx_rmodli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = modu32(sx32(f_imm, 9), cc->r[f_rx]);
}

/* rdivsli: R[rd] = sext(imm) /s R[rx] */
static void gx_rdivsli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 12) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 9) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x1ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = divs32(sx32(f_imm, 9), cc->r[f_rx]);
}

/* cbeq: if R[rx] == imm7 then PC = PC + sext(disp) */
static void gx_cbeq(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 17) & 0x7u); (void)f_rx;
    const uint32_t f_imm7 = ((w >> 10) & 0x7fu); (void)f_imm7;
    const uint32_t f_disp = ((w >> 0) & 0x3ffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] == f_imm7)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 10)));
    }
}

/* cbne: if R[rx] != imm7 then PC = PC + sext(disp) */
static void gx_cbne(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 17) & 0x7u); (void)f_rx;
    const uint32_t f_imm7 = ((w >> 10) & 0x7fu); (void)f_imm7;
    const uint32_t f_disp = ((w >> 0) & 0x3ffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] != f_imm7)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 10)));
    }
}

/* add: R[rd] = R[rx] + R[ry] */
static void gx_add(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] + cc->r[f_ry]);
}

/* sub: R[rd] = R[rx] - R[ry] */
static void gx_sub(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] - cc->r[f_ry]);
}

/* mul: R[rd] = R[rx] * R[ry] */
static void gx_mul(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] * cc->r[f_ry]);
}

/* div: R[rd] = R[rx] /u R[ry] */
static void gx_div(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = divu32(cc->r[f_rx], cc->r[f_ry]);
}

/* mod: R[rd] = R[rx] %u R[ry] */
static void gx_mod(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = modu32(cc->r[f_rx], cc->r[f_ry]);
}

/* shl: R[rd] = R[rx] << (R[ry] & 31) */
static void gx_shl(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = shl32(cc->r[f_rx], (uint32_t)(cc->r[f_ry] & 0x1fu));
}

/* shr: R[rd] = R[rx] >> (R[ry] & 31) */
static void gx_shr(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = shr32(cc->r[f_rx], (uint32_t)(cc->r[f_ry] & 0x1fu));
}

/* lt: R[rd] = R[rx] <u R[ry] */
static void gx_lt(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] < cc->r[f_ry]);
}

/* le: R[rd] = R[rx] <=u R[ry] */
static void gx_le(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] <= cc->r[f_ry]);
}

/* eq: R[rd] = R[rx] == R[ry] */
static void gx_eq(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] == cc->r[f_ry]);
}

/* ne: R[rd] = R[rx] != R[ry] */
static void gx_ne(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] != cc->r[f_ry]);
}

/* and: R[rd] = R[rx] & R[ry] */
static void gx_and(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] & cc->r[f_ry]);
}

/* or: R[rd] = R[rx] | R[ry] */
static void gx_or(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] | cc->r[f_ry]);
}

/* xor: R[rd] = R[rx] ^ R[ry] */
static void gx_xor(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rx] ^ cc->r[f_ry]);
}

/* lts: R[rd] = R[rx] <s R[ry] */
static void gx_lts(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)((int32_t)cc->r[f_rx] < (int32_t)cc->r[f_ry]);
}

/* les: R[rd] = R[rx] <=s R[ry] */
static void gx_les(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)((int32_t)cc->r[f_rx] <= (int32_t)cc->r[f_ry]);
}

/* divs: R[rd] = R[rx] /s R[ry] */
static void gx_divs(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = divs32(cc->r[f_rx], cc->r[f_ry]);
}

/* mods: R[rd] = R[rx] %s R[ry] */
static void gx_mods(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = mods32(cc->r[f_rx], cc->r[f_ry]);
}

/* shrs: R[rd] = R[rx] >>s (R[ry] & 31) */
static void gx_shrs(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = sar32(cc->r[f_rx], (uint32_t)(cc->r[f_ry] & 0x1fu));
}

/* fadd: R[rd] = fadd(R[rx], R[ry]) */
static void gx_fadd(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu4_fadd(cc->r[f_rx], cc->r[f_ry]);
}

/* fsub: R[rd] = fsub(R[rx], R[ry]) */
static void gx_fsub(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu4_fsub(cc->r[f_rx], cc->r[f_ry]);
}

/* fmul: R[rd] = fmul(R[rx], R[ry]) */
static void gx_fmul(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu4_fmul(cc->r[f_rx], cc->r[f_ry]);
}

/* fdiv: R[rd] = fdiv(R[rx], R[ry]) */
static void gx_fdiv(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu4_fdiv(cc->r[f_rx], cc->r[f_ry]);
}

/* flt: R[rd] = flt(R[rx], R[ry]) */
static void gx_flt(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu4_flt(cc->r[f_rx], cc->r[f_ry]);
}

/* fle: R[rd] = fle(R[rx], R[ry]) */
static void gx_fle(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu4_fle(cc->r[f_rx], cc->r[f_ry]);
}

/* zxwor: R[rd] = zx(R[rx] | R[ry], 16) */
static void gx_zxwor(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = ((uint32_t)(cc->r[f_rx] | cc->r[f_ry]) & 0xffffu);
}

/* sxwor: R[rd] = sx(R[rx] | R[ry], 16) */
static void gx_sxwor(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    const uint32_t f_rx = ((w >> 3) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 0) & 0x7u); (void)f_ry;
    (void)w; (void)oldpc;
    cc->r[f_rd] = sx32((uint32_t)(cc->r[f_rx] | cc->r[f_ry]), 16);
}

/* sxb: R[rd] = sx(R[rd], 8) */
static void gx_sxb(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = sx32(cc->r[f_rd], 8);
}

/* sxw: R[rd] = sx(R[rd], 16) */
static void gx_sxw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = sx32(cc->r[f_rd], 16);
}

/* inc: R[rd] = R[rd] + 1 */
static void gx_inc(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rd] + 0x1u);
}

/* dec: R[rd] = R[rd] - 1 */
static void gx_dec(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(cc->r[f_rd] - 0x1u);
}

/* pushr: SP = SP - 4; M32[SP] = R[rd] */
static void gx_pushr(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->sp = (uint16_t)((uint32_t)((uint32_t)cc->sp - 0x4u));
    gen_wr32((uint32_t)cc->sp, cc->r[f_rd], oldpc);
}

/* popr: R[rd] = M32[SP]; SP = SP + 4 */
static void gx_popr(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = gen_rd32((uint32_t)cc->sp, oldpc);
    cc->sp = (uint16_t)((uint32_t)((uint32_t)cc->sp + 0x4u));
}

/* zxb: R[rd] = zx(R[rd], 8) */
static void gx_zxb(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (cc->r[f_rd] & 0xffu);
}

/* zxw: R[rd] = zx(R[rd], 16) */
static void gx_zxw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (cc->r[f_rd] & 0xffffu);
}

/* itof: R[rd] = itof(R[rd]) */
static void gx_itof(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu4_itof(cc->r[f_rd]);
}

/* ftoi: R[rd] = ftoi(R[rd]) */
static void gx_ftoi(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu4_ftoi(cc->r[f_rd]);
}

/* jlr: LR = PC; PC = R[rd] */
static void gx_jlr(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->lr = (uint16_t)((uint32_t)cc->pc);
    cc->pc = (uint16_t)(cc->r[f_rd]);
}

/* jr: PC = R[rd] */
static void gx_jr(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->pc = (uint16_t)(cc->r[f_rd]);
}

/* ssp: SP = R[rd] */
static void gx_ssp(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->sp = (uint16_t)(cc->r[f_rd]);
}

/* neg: R[rd] = -R[rd] */
static void gx_neg(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = (uint32_t)(0u - cc->r[f_rd]);
}

/* frecip: R[rd] = frecip(R[rd]) */
static void gx_frecip(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu4_frecip(cc->r[f_rd]);
}

/* frsqrt: R[rd] = frsqrt(R[rd]) */
static void gx_frsqrt(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    cc->r[f_rd] = cpu4_frsqrt(cc->r[f_rd]);
}

/* putchar: putchar(R[rd]) */
static void gx_putchar(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 6) & 0x7u); (void)f_rd;
    (void)w; (void)oldpc;
    gen_putchar(cc->r[f_rd]);
}

/* lb: R[rx] = M8[lo16(BP + sext(imm))] */
static void gx_lb(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = gen_rd8(((uint32_t)((uint32_t)cc->bp + sx32(f_imm, 7)) & 0xffffu), oldpc);
}

/* lw: R[rx] = M16[lo16(BP + sext(imm) * 2)] */
static void gx_lw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = gen_rd16(((uint32_t)((uint32_t)cc->bp + (uint32_t)(sx32(f_imm, 7) * 0x2u)) & 0xffffu), oldpc);
}

/* ll: R[rx] = M32[lo16(BP + sext(imm) * 4)] */
static void gx_ll(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = gen_rd32(((uint32_t)((uint32_t)cc->bp + (uint32_t)(sx32(f_imm, 7) * 0x4u)) & 0xffffu), oldpc);
}

/* sb: M8[lo16(BP + sext(imm))] = R[rx] */
static void gx_sb(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    gen_wr8(((uint32_t)((uint32_t)cc->bp + sx32(f_imm, 7)) & 0xffffu), cc->r[f_rx], oldpc);
}

/* sw: M16[lo16(BP + sext(imm) * 2)] = R[rx] */
static void gx_sw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    gen_wr16(((uint32_t)((uint32_t)cc->bp + (uint32_t)(sx32(f_imm, 7) * 0x2u)) & 0xffffu), cc->r[f_rx], oldpc);
}

/* sl: M32[lo16(BP + sext(imm) * 4)] = R[rx] */
static void gx_sl(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    gen_wr32(((uint32_t)((uint32_t)cc->bp + (uint32_t)(sx32(f_imm, 7) * 0x4u)) & 0xffffu), cc->r[f_rx], oldpc);
}

/* lbx: R[rx] = sx(M8[lo16(BP + sext(imm))], 8) */
static void gx_lbx(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = sx32(gen_rd8(((uint32_t)((uint32_t)cc->bp + sx32(f_imm, 7)) & 0xffffu), oldpc), 8);
}

/* lwx: R[rx] = sx(M16[lo16(BP + sext(imm) * 2)], 16) */
static void gx_lwx(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = sx32(gen_rd16(((uint32_t)((uint32_t)cc->bp + (uint32_t)(sx32(f_imm, 7) * 0x2u)) & 0xffffu), oldpc), 16);
}

/* addi: R[rx] = R[rx] + sext(imm) */
static void gx_addi(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = (uint32_t)(cc->r[f_rx] + sx32(f_imm, 7));
}

/* shli: R[rx] = R[rx] << (imm & 31) */
static void gx_shli(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = shl32(cc->r[f_rx], (uint32_t)(f_imm & 0x1fu));
}

/* andi: R[rx] = R[rx] & imm */
static void gx_andi(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = (uint32_t)(cc->r[f_rx] & f_imm);
}

/* shrsi: R[rx] = R[rx] >>s (imm & 31) */
static void gx_shrsi(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = sar32(cc->r[f_rx], (uint32_t)(f_imm & 0x1fu));
}

/* imms: R[rx] = sext(imm) */
static void gx_imms(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 7) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0x7fu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = sx32(f_imm, 7);
}

/* j: PC = imm */
static void gx_j(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->pc = (uint16_t)(f_imm);
}

/* jl: LR = PC; PC = imm */
static void gx_jl(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->lr = (uint16_t)((uint32_t)cc->pc);
    cc->pc = (uint16_t)(f_imm);
}

/* enter: M32[lo16(SP - 4)] = (LR << 16) | BP; BP = SP - 4; SP = SP - imm - 4 */
static void gx_enter(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    gen_wr32(((uint32_t)((uint32_t)cc->sp - 0x4u) & 0xffffu), (uint32_t)(shl32((uint32_t)cc->lr, 0x10u) | (uint32_t)cc->bp), oldpc);
    cc->bp = (uint16_t)((uint32_t)((uint32_t)cc->sp - 0x4u));
    cc->sp = (uint16_t)((uint32_t)((uint32_t)((uint32_t)cc->sp - f_imm) - 0x4u));
}

/* adjw: SP = SP + sext(imm) * 4 */
static void gx_adjw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_imm = ((w >> 0) & 0x3fffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->sp = (uint16_t)((uint32_t)((uint32_t)cc->sp + (uint32_t)(sx32(f_imm, 14) * 0x4u)));
}

/* lea: R[rd] = lo16(BP + sext(imm) * 4) */
static void gx_lea(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rd = ((w >> 14) & 0x7u); (void)f_rd;
    const uint32_t f_imm = ((w >> 0) & 0x3fffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rd] = ((uint32_t)((uint32_t)cc->bp + (uint32_t)(sx32(f_imm, 14) * 0x4u)) & 0xffffu);
}

/* llb: R[rx] = M8[R[ry] + sext(imm)] */
static void gx_llb(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 10) & 0x7u); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0x3ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = gen_rd8((uint32_t)(cc->r[f_ry] + sx32(f_imm, 10)), oldpc);
}

/* llw: R[rx] = M16[R[ry] + sext(imm) * 2] */
static void gx_llw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 10) & 0x7u); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0x3ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = gen_rd16((uint32_t)(cc->r[f_ry] + (uint32_t)(sx32(f_imm, 10) * 0x2u)), oldpc);
}

/* lll: R[rx] = M32[R[ry] + sext(imm) * 4] */
static void gx_lll(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 10) & 0x7u); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0x3ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = gen_rd32((uint32_t)(cc->r[f_ry] + (uint32_t)(sx32(f_imm, 10) * 0x4u)), oldpc);
}

/* slb: M8[R[ry] + sext(imm)] = R[rx] */
static void gx_slb(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 10) & 0x7u); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0x3ffu); (void)f_imm;
    (void)w; (void)oldpc;
    gen_wr8((uint32_t)(cc->r[f_ry] + sx32(f_imm, 10)), cc->r[f_rx], oldpc);
}

/* slw: M16[R[ry] + sext(imm) * 2] = R[rx] */
static void gx_slw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 10) & 0x7u); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0x3ffu); (void)f_imm;
    (void)w; (void)oldpc;
    gen_wr16((uint32_t)(cc->r[f_ry] + (uint32_t)(sx32(f_imm, 10) * 0x2u)), cc->r[f_rx], oldpc);
}

/* sll: M32[R[ry] + sext(imm) * 4] = R[rx] */
static void gx_sll(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 10) & 0x7u); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0x3ffu); (void)f_imm;
    (void)w; (void)oldpc;
    gen_wr32((uint32_t)(cc->r[f_ry] + (uint32_t)(sx32(f_imm, 10) * 0x4u)), cc->r[f_rx], oldpc);
}

/* llbx: R[rx] = sx(M8[R[ry] + sext(imm)], 8) */
static void gx_llbx(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 10) & 0x7u); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0x3ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = sx32(gen_rd8((uint32_t)(cc->r[f_ry] + sx32(f_imm, 10)), oldpc), 8);
}

/* llwx: R[rx] = sx(M16[R[ry] + sext(imm) * 2], 16) */
static void gx_llwx(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 10) & 0x7u); (void)f_ry;
    const uint32_t f_imm = ((w >> 0) & 0x3ffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = sx32(gen_rd16((uint32_t)(cc->r[f_ry] + (uint32_t)(sx32(f_imm, 10) * 0x2u)), oldpc), 16);
}

/* beq: if R[rx] == R[ry] then PC = PC + sext(disp) */
static void gx_beq(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 10) & 0x7u); (void)f_ry;
    const uint32_t f_disp = ((w >> 0) & 0x3ffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] == cc->r[f_ry])) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 10)));
    }
}

/* bne: if R[rx] != R[ry] then PC = PC + sext(disp) */
static void gx_bne(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 10) & 0x7u); (void)f_ry;
    const uint32_t f_disp = ((w >> 0) & 0x3ffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] != cc->r[f_ry])) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 10)));
    }
}

/* blt: if R[rx] <u R[ry] then PC = PC + sext(disp) */
static void gx_blt(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 10) & 0x7u); (void)f_ry;
    const uint32_t f_disp = ((w >> 0) & 0x3ffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] < cc->r[f_ry])) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 10)));
    }
}

/* ble: if R[rx] <=u R[ry] then PC = PC + sext(disp) */
static void gx_ble(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 10) & 0x7u); (void)f_ry;
    const uint32_t f_disp = ((w >> 0) & 0x3ffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] <= cc->r[f_ry])) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 10)));
    }
}

/* blts: if R[rx] <s R[ry] then PC = PC + sext(disp) */
static void gx_blts(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 10) & 0x7u); (void)f_ry;
    const uint32_t f_disp = ((w >> 0) & 0x3ffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)((int32_t)cc->r[f_rx] < (int32_t)cc->r[f_ry])) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 10)));
    }
}

/* bles: if R[rx] <=s R[ry] then PC = PC + sext(disp) */
static void gx_bles(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_ry = ((w >> 10) & 0x7u); (void)f_ry;
    const uint32_t f_disp = ((w >> 0) & 0x3ffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)((int32_t)cc->r[f_rx] <= (int32_t)cc->r[f_ry])) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 10)));
    }
}

/* beqz: if R[rx] == 0 then PC = PC + sext(disp) */
static void gx_beqz(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_disp = ((w >> 0) & 0x3ffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] == 0x0u)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 10)));
    }
}

/* bnez: if R[rx] != 0 then PC = PC + sext(disp) */
static void gx_bnez(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_disp = ((w >> 0) & 0x3ffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] != 0x0u)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 10)));
    }
}

/* dbnz: R[rx] = R[rx] - 1; if R[rx] != 0 then PC = PC + sext(disp) */
static void gx_dbnz(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_disp = ((w >> 0) & 0x3ffu); (void)f_disp;
    (void)w; (void)oldpc;
    cc->r[f_rx] = (uint32_t)(cc->r[f_rx] - 0x1u);
    if ((uint32_t)(cc->r[f_rx] != 0x0u)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 10)));
    }
}

/* bltz: if R[rx] <s 0 then PC = PC + sext(disp) */
static void gx_bltz(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_disp = ((w >> 0) & 0x3ffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)((int32_t)cc->r[f_rx] < (int32_t)0x0u)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 10)));
    }
}

/* bgez: if R[rx] >=s 0 then PC = PC + sext(disp) */
static void gx_bgez(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_disp = ((w >> 0) & 0x3ffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)((int32_t)cc->r[f_rx] >= (int32_t)0x0u)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 10)));
    }
}

/* bgtz: if R[rx] >s 0 then PC = PC + sext(disp) */
static void gx_bgtz(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_disp = ((w >> 0) & 0x3ffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)((int32_t)cc->r[f_rx] > (int32_t)0x0u)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 10)));
    }
}

/* blez: if R[rx] <=s 0 then PC = PC + sext(disp) */
static void gx_blez(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 13) & 0x7u); (void)f_rx;
    const uint32_t f_disp = ((w >> 0) & 0x3ffu); (void)f_disp;
    (void)w; (void)oldpc;
    if ((uint32_t)((int32_t)cc->r[f_rx] <= (int32_t)0x0u)) {
        cc->pc = (uint16_t)((uint32_t)((uint32_t)cc->pc + sx32(f_disp, 10)));
    }
}

/* immw: R[rx] = imm */
static void gx_immw(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 16) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = f_imm;
}

/* immwh: R[rx] = zx(R[rx], 16) | (imm << 16) */
static void gx_immwh(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 16) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    cc->r[f_rx] = (uint32_t)((cc->r[f_rx] & 0xffffu) | shl32(f_imm, 0x10u));
}

/* jz: if R[rx] == 0 then PC = imm */
static void gx_jz(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 16) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] == 0x0u)) {
        cc->pc = (uint16_t)(f_imm);
    }
}

/* jnz: if R[rx] != 0 then PC = imm */
static void gx_jnz(Core *cc, uint32_t w, uint16_t oldpc) {
    const uint32_t f_rx = ((w >> 16) & 0x7u); (void)f_rx;
    const uint32_t f_imm = ((w >> 0) & 0xffffu); (void)f_imm;
    (void)w; (void)oldpc;
    if ((uint32_t)(cc->r[f_rx] != 0x0u)) {
        cc->pc = (uint16_t)(f_imm);
    }
}

static void gen_unknown(Core *cc, uint32_t w, uint16_t oldpc) {
    fprintf(stderr, "cpu4: unknown instruction 0x%x at pc=%04x\n", (unsigned)w, oldpc);
    g_gen_bad = 1;
    cc->H = 1;
}

/* Execute one instruction for core cc; returns its length in bytes. */
static int gen_step(Core *cc) {
    const uint16_t oldpc = cc->pc;
    uint32_t w;
    switch (read8(oldpc)) {
    case 0x00:
        w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        gx_halt(cc, w, oldpc);
        return 1;
    case 0x01:
        w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        gx_ret(cc, w, oldpc);
        return 1;
    case 0x02:
        w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        gx_zero0(cc, w, oldpc);
        return 1;
    case 0x03:
        w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        gx_zero1(cc, w, oldpc);
        return 1;
    case 0x04:
        w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        gx_zero2(cc, w, oldpc);
        return 1;
    case 0x05:
        w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        gx_zero3(cc, w, oldpc);
        return 1;
    case 0x06:
        w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        gx_zero4(cc, w, oldpc);
        return 1;
    case 0x07:
        w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        gx_zero5(cc, w, oldpc);
        return 1;
    case 0x08:
        w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        gx_zero6(cc, w, oldpc);
        return 1;
    case 0x09:
        w = gen_fetch(oldpc, 1); cc->pc = (uint16_t)(oldpc + 1);
        gx_zero7(cc, w, oldpc);
        return 1;
    case 0x10:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        switch (((w >> 15) & 0x1u)) {
        case 0x0: gx_addli(cc, w, oldpc); break;
        case 0x1: gx_subli(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        return 3;
    case 0x11:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        switch (((w >> 15) & 0x1u)) {
        case 0x0: gx_mulli(cc, w, oldpc); break;
        case 0x1: gx_divli(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        return 3;
    case 0x12:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        switch (((w >> 15) & 0x1u)) {
        case 0x0: gx_modli(cc, w, oldpc); break;
        case 0x1: gx_shlli(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        return 3;
    case 0x13:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        switch (((w >> 15) & 0x1u)) {
        case 0x0: gx_shrli(cc, w, oldpc); break;
        case 0x1: gx_leli(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        return 3;
    case 0x14:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        switch (((w >> 15) & 0x1u)) {
        case 0x0: gx_gtli(cc, w, oldpc); break;
        case 0x1: gx_eqli(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        return 3;
    case 0x15:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        switch (((w >> 15) & 0x1u)) {
        case 0x0: gx_neli(cc, w, oldpc); break;
        case 0x1: gx_andli(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        return 3;
    case 0x16:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        switch (((w >> 15) & 0x1u)) {
        case 0x0: gx_orli(cc, w, oldpc); break;
        case 0x1: gx_xorli(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        return 3;
    case 0x17:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        switch (((w >> 15) & 0x1u)) {
        case 0x0: gx_lesli(cc, w, oldpc); break;
        case 0x1: gx_gtsli(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        return 3;
    case 0x18:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        switch (((w >> 15) & 0x1u)) {
        case 0x0: gx_divsli(cc, w, oldpc); break;
        case 0x1: gx_modsli(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        return 3;
    case 0x19:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        switch (((w >> 15) & 0x1u)) {
        case 0x0: gx_shrsli(cc, w, oldpc); break;
        case 0x1: gx_bitex(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        return 3;
    case 0x1a:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        switch (((w >> 15) & 0x1u)) {
        case 0x0: gx_rsubli(cc, w, oldpc); break;
        case 0x1: gx_rdivli(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        return 3;
    case 0x1b:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        switch (((w >> 15) & 0x1u)) {
        case 0x0: gx_rmodli(cc, w, oldpc); break;
        case 0x1: gx_rdivsli(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        return 3;
    case 0x20: case 0x21: case 0x22: case 0x23: case 0x24: case 0x25: case 0x26: case 0x27: case 0x28: case 0x29: case 0x2a: case 0x2b: case 0x2c: case 0x2d: case 0x2e: case 0x2f:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_cbeq(cc, w, oldpc);
        return 3;
    case 0x30: case 0x31: case 0x32: case 0x33: case 0x34: case 0x35: case 0x36: case 0x37: case 0x38: case 0x39: case 0x3a: case 0x3b: case 0x3c: case 0x3d: case 0x3e: case 0x3f:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_cbne(cc, w, oldpc);
        return 3;
    case 0x40: case 0x41:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_add(cc, w, oldpc);
        return 2;
    case 0x42: case 0x43:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_sub(cc, w, oldpc);
        return 2;
    case 0x44: case 0x45:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_mul(cc, w, oldpc);
        return 2;
    case 0x46: case 0x47:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_div(cc, w, oldpc);
        return 2;
    case 0x48: case 0x49:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_mod(cc, w, oldpc);
        return 2;
    case 0x4a: case 0x4b:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_shl(cc, w, oldpc);
        return 2;
    case 0x4c: case 0x4d:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_shr(cc, w, oldpc);
        return 2;
    case 0x4e: case 0x4f:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_lt(cc, w, oldpc);
        return 2;
    case 0x50: case 0x51:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_le(cc, w, oldpc);
        return 2;
    case 0x52: case 0x53:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_eq(cc, w, oldpc);
        return 2;
    case 0x54: case 0x55:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_ne(cc, w, oldpc);
        return 2;
    case 0x56: case 0x57:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_and(cc, w, oldpc);
        return 2;
    case 0x58: case 0x59:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_or(cc, w, oldpc);
        return 2;
    case 0x5a: case 0x5b:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_xor(cc, w, oldpc);
        return 2;
    case 0x5c: case 0x5d:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_lts(cc, w, oldpc);
        return 2;
    case 0x5e: case 0x5f:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_les(cc, w, oldpc);
        return 2;
    case 0x60: case 0x61:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_divs(cc, w, oldpc);
        return 2;
    case 0x62: case 0x63:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_mods(cc, w, oldpc);
        return 2;
    case 0x64: case 0x65:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_shrs(cc, w, oldpc);
        return 2;
    case 0x66: case 0x67:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_fadd(cc, w, oldpc);
        return 2;
    case 0x68: case 0x69:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_fsub(cc, w, oldpc);
        return 2;
    case 0x6a: case 0x6b:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_fmul(cc, w, oldpc);
        return 2;
    case 0x6c: case 0x6d:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_fdiv(cc, w, oldpc);
        return 2;
    case 0x6e: case 0x6f:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_flt(cc, w, oldpc);
        return 2;
    case 0x70: case 0x71:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_fle(cc, w, oldpc);
        return 2;
    case 0x72: case 0x73:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_zxwor(cc, w, oldpc);
        return 2;
    case 0x74: case 0x75:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_sxwor(cc, w, oldpc);
        return 2;
    case 0x7e: case 0x7f:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        switch (((w >> 0) & 0x3fu)) {
        case 0x0: gx_sxb(cc, w, oldpc); break;
        case 0x1: gx_sxw(cc, w, oldpc); break;
        case 0x2: gx_inc(cc, w, oldpc); break;
        case 0x3: gx_dec(cc, w, oldpc); break;
        case 0x4: gx_pushr(cc, w, oldpc); break;
        case 0x5: gx_popr(cc, w, oldpc); break;
        case 0x6: gx_zxb(cc, w, oldpc); break;
        case 0x7: gx_zxw(cc, w, oldpc); break;
        case 0x8: gx_itof(cc, w, oldpc); break;
        case 0x9: gx_ftoi(cc, w, oldpc); break;
        case 0xa: gx_jlr(cc, w, oldpc); break;
        case 0xb: gx_jr(cc, w, oldpc); break;
        case 0xc: gx_ssp(cc, w, oldpc); break;
        case 0xd: gx_neg(cc, w, oldpc); break;
        case 0xe: gx_frecip(cc, w, oldpc); break;
        case 0xf: gx_frsqrt(cc, w, oldpc); break;
        case 0x3f: gx_putchar(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        return 2;
    case 0x80: case 0x81: case 0x82: case 0x83:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_lb(cc, w, oldpc);
        return 2;
    case 0x84: case 0x85: case 0x86: case 0x87:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_lw(cc, w, oldpc);
        return 2;
    case 0x88: case 0x89: case 0x8a: case 0x8b:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_ll(cc, w, oldpc);
        return 2;
    case 0x8c: case 0x8d: case 0x8e: case 0x8f:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_sb(cc, w, oldpc);
        return 2;
    case 0x90: case 0x91: case 0x92: case 0x93:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_sw(cc, w, oldpc);
        return 2;
    case 0x94: case 0x95: case 0x96: case 0x97:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_sl(cc, w, oldpc);
        return 2;
    case 0x98: case 0x99: case 0x9a: case 0x9b:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_lbx(cc, w, oldpc);
        return 2;
    case 0x9c: case 0x9d: case 0x9e: case 0x9f:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_lwx(cc, w, oldpc);
        return 2;
    case 0xa0: case 0xa1: case 0xa2: case 0xa3:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_addi(cc, w, oldpc);
        return 2;
    case 0xa4: case 0xa5: case 0xa6: case 0xa7:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_shli(cc, w, oldpc);
        return 2;
    case 0xa8: case 0xa9: case 0xaa: case 0xab:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_andi(cc, w, oldpc);
        return 2;
    case 0xac: case 0xad: case 0xae: case 0xaf:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_shrsi(cc, w, oldpc);
        return 2;
    case 0xb0: case 0xb1: case 0xb2: case 0xb3:
        w = gen_fetch(oldpc, 2); cc->pc = (uint16_t)(oldpc + 2);
        gx_imms(cc, w, oldpc);
        return 2;
    case 0xc0:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_j(cc, w, oldpc);
        return 3;
    case 0xc1:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_jl(cc, w, oldpc);
        return 3;
    case 0xc2:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_enter(cc, w, oldpc);
        return 3;
    case 0xc4: case 0xc5:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_adjw(cc, w, oldpc);
        return 3;
    case 0xc6: case 0xc7:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_lea(cc, w, oldpc);
        return 3;
    case 0xd0:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_llb(cc, w, oldpc);
        return 3;
    case 0xd1:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_llw(cc, w, oldpc);
        return 3;
    case 0xd2:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_lll(cc, w, oldpc);
        return 3;
    case 0xd3:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_slb(cc, w, oldpc);
        return 3;
    case 0xd4:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_slw(cc, w, oldpc);
        return 3;
    case 0xd5:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_sll(cc, w, oldpc);
        return 3;
    case 0xd6:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_llbx(cc, w, oldpc);
        return 3;
    case 0xd7:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_llwx(cc, w, oldpc);
        return 3;
    case 0xd8:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_beq(cc, w, oldpc);
        return 3;
    case 0xd9:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_bne(cc, w, oldpc);
        return 3;
    case 0xda:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_blt(cc, w, oldpc);
        return 3;
    case 0xdb:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_ble(cc, w, oldpc);
        return 3;
    case 0xdc:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_blts(cc, w, oldpc);
        return 3;
    case 0xdd:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_bles(cc, w, oldpc);
        return 3;
    case 0xdf:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        switch (((w >> 10) & 0x7u)) {
        case 0x0: gx_beqz(cc, w, oldpc); break;
        case 0x1: gx_bnez(cc, w, oldpc); break;
        case 0x2: gx_dbnz(cc, w, oldpc); break;
        case 0x3: gx_bltz(cc, w, oldpc); break;
        case 0x4: gx_bgez(cc, w, oldpc); break;
        case 0x5: gx_bgtz(cc, w, oldpc); break;
        case 0x6: gx_blez(cc, w, oldpc); break;
        default: gen_unknown(cc, w, oldpc); break;
        }
        return 3;
    case 0xe0: case 0xe1: case 0xe2: case 0xe3: case 0xe4: case 0xe5: case 0xe6: case 0xe7:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_immw(cc, w, oldpc);
        return 3;
    case 0xe8: case 0xe9: case 0xea: case 0xeb: case 0xec: case 0xed: case 0xee: case 0xef:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_immwh(cc, w, oldpc);
        return 3;
    case 0xf0: case 0xf1: case 0xf2: case 0xf3: case 0xf4: case 0xf5: case 0xf6: case 0xf7:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_jz(cc, w, oldpc);
        return 3;
    case 0xf8: case 0xf9: case 0xfa: case 0xfb: case 0xfc: case 0xfd: case 0xfe: case 0xff:
        w = gen_fetch(oldpc, 3); cc->pc = (uint16_t)(oldpc + 3);
        gx_jnz(cc, w, oldpc);
        return 3;
    default:
        gen_unknown(cc, read8(oldpc), oldpc);
        cc->pc = (uint16_t)(oldpc + 1);
        return 1;
    }
}
#endif
