#!/usr/bin/env python3
"""Generate the CPU4 FPU seed ROMs (the spec for frecip and frsqrt).

Writes, next to this script:
  frecip_rom.hex   1024 x 16-bit  reciprocal seed        (RTL $readmemh)
  frsqrt_rom.hex   1024 x 16-bit  reciprocal-sqrt seed   (RTL $readmemh)
  fpu_roms.h       both tables as C arrays for sim_c

frecip: index i = mantissa[22:13]; rom[i] = round((2/(1 + i/1024) - 1) * 65536), rom[0] = 0.
        Result exponent 254 - e for i == 0 else 253 - e; {sign, exp, rom[i], 7'b0}.
frsqrt: p = ~e[0] (unbiased exponent odd); index i = {p, mantissa[22:14]};
        arg = (1 + ((i & 511) + 0.5)/512) * (2 if p else 1)   (interval midpoint)
        rom[i] = round((2/sqrt(arg) - 1) * 65536)
        Result exponent (379 - e)/2 if e odd else (380 - e)/2; {0, exp, rom[i], 7'b0}.
See processor docs/proposals/0003-cpu4-accelerators.md.
"""
import math, os
here = os.path.dirname(os.path.abspath(__file__))

recip = []
for i in range(1024):
    if i == 0: recip.append(0); continue
    n = 2.0 / (1.0 + i / 1024.0)
    recip.append(int(round((n - 1.0) * 65536)) & 0xffff)

rsqrt = []
for i in range(1024):
    p = i >> 9
    arg = (1.0 + ((i & 511) + 0.5) / 512.0) * (2.0 if p else 1.0)
    n = 2.0 / math.sqrt(arg)
    v = int(round((n - 1.0) * 65536))
    assert 0 < v < 65536, (i, v)
    rsqrt.append(v)

for name, tab in (("frecip_rom.hex", recip), ("frsqrt_rom.hex", rsqrt)):
    with open(os.path.join(here, name), "w") as f:
        for v in tab: f.write(f"{v:04x}\n")

with open(os.path.join(here, "fpu_roms.h"), "w") as f:
    f.write("/* Generated by cpu4/gen_fpu_roms.py -- do not edit. CPU4 FPU seed ROMs (see the ISA doc). */\n")
    for name, tab in (("FRECIP_ROM", recip), ("FRSQRT_ROM", rsqrt)):
        f.write(f"static const uint16_t {name}[1024] = {{\n")
        for k in range(0, 1024, 16):
            f.write("    " + ", ".join(f"0x{v:04x}" for v in tab[k:k+16]) + ",\n")
        f.write("};\n")
print("wrote frecip_rom.hex frsqrt_rom.hex fpu_roms.h")
