#!/usr/bin/env python3
"""Generate every derived copy of the CPU4 encoding from cpu4/isa.py.

  gen_isa.py                 write cpu4/isa_table_c.h, cpu4/isa_table.py,
                             docs/isa/cpu4-encoding.md
  gen_isa.py --check         exit 1 if any of those is stale
  gen_isa.py --check-decode PATH   compare hw decode.v case labels with the table
"""
import os, re, sys
here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, here)
import isa

ROOT = os.path.dirname(here)
OUT_C  = os.path.join(here, 'isa_table_c.h')
OUT_PY = os.path.join(here, 'isa_table.py')
OUT_MD = os.path.join(ROOT, 'docs', 'isa', 'cpu4-encoding.md')
HDR = "Generated by cpu4/gen_isa.py from cpu4/isa.py -- do not edit; edit isa.py and run `make isa`."


def gen_c():
    L = [f"/* {HDR} */", "static const Instr4 itab4[] = {"]
    cur = None
    for d in isa.INSTRUCTIONS:
        f = isa.FORMATS[d['fmt']]
        if d['fmt'] != cur:
            cur = d['fmt']; L.append(f"    /* {cur}: {f['bytes']} byte(s); extra={f['c'][0]} subfmt={f['c'][1]} */")
        L.append(f'    {{"{d["name"]}",{" " * max(1, 8 - len(d["name"]))}0x{d["op"]:02x},{f["c"][0]},{f["c"][1]},0x{d["subop"]:02x}}},')
    L.append("    {NULL,0,0,0,0}")
    L.append("};")
    return "\n".join(L) + "\n"


def gen_py():
    L = [f"# {HDR}", "PTABLE = {"]
    cur = None
    for d in isa.INSTRUCTIONS:
        f = isa.FORMATS[d['fmt']]
        if d['fmt'] != cur:
            cur = d['fmt']; L.append(f"    # {cur}: extra={f['py'][0]} subfmt={f['py'][1]}")
        L.append(f"    {d['name']!r:10}: (0x{d['op']:02x}, {f['py'][0]}, {f['py'][1]}, 0x{d['subop']:02x}),")
    L.append("}")
    L.append("# pseudo-op -> (real mnemonic, operand permutation: new operand k is source operand perm[k])")
    L.append("PSEUDOS = {")
    for n, (real, perm) in isa.PSEUDOS.items():
        L.append(f"    {n!r:8}: ({real!r}, {perm!r}),")
    L.append("}")
    pcrel = sorted(d['name'] for d in isa.INSTRUCTIONS if d['imm'] and d['imm'][0] == 'pcrel')
    L.append(f"PCREL_BRANCHES = frozenset({pcrel!r})")   # sorted list: deterministic output
    return "\n".join(L) + "\n"


def gen_md():
    L = ["# CPU4 encoding tables", "", f"<!-- {HDR} -->", "",
         "The semantics of each instruction are in [cpu4.md](cpu4.md); this file is the",
         "encoding as `cpu4/isa.py` defines it. Immediate kinds: `simm`/`uimm` signed/",
         "unsigned value, `index` element index scaled by the access width, `bytes4` byte",
         "offset encoded ÷4, `raw16` 16-bit pattern, `pcrel` PC-relative displacement",
         "(label), `abs16` absolute address (label).", ""]
    cur = None
    for d in isa.INSTRUCTIONS:
        f = isa.FORMATS[d['fmt']]
        if d['fmt'] != cur:
            cur = d['fmt']
            L += ["", f"## {cur} — {f['bytes']} byte{'s' if f['bytes'] > 1 else ''}", "",
                  "| Mnemonic | First byte | Sub-op | Operands | Immediate | Range (source units) |",
                  "|---|---|---|---|---|---|"]
        imm = d['imm']
        immtxt = "—" if not imm else (f"{imm[0]}{imm[1]}" + (f" ×{imm[2]}" if len(imm) > 2 else ""))
        r = isa.imm_range(d)
        rtxt = "label" if imm and imm[0] in ('pcrel', 'abs16') else ("—" if not r else f"{r[1]}..{r[2]}")
        sub = f"0x{d['subop']:02x}" if d['fmt'] in ('F1b', 'F3d') else (str(d['subop']) if d['fmt'] == 'F0b' else "—")
        L.append(f"| `{d['name']}` | `0x{d['op']:02x}` | {sub} | `{isa.operand_syntax(d)}` | {immtxt} | {rtxt} |")
    L += ["", "## Pseudo-ops (assembler only)", "", "| Pseudo | Expands to | Operand order |", "|---|---|---|"]
    for n, (real, perm) in isa.PSEUDOS.items():
        L.append(f"| `{n}` | `{real}` | source operands {perm} |")
    return "\n".join(L) + "\n"


def expected_label(d):
    """The case-label value decode.v uses for this instruction, per format."""
    op, sub, f = d['op'], d['subop'], d['fmt']
    return {'F0a': op & 0xf, 'F0b': (op - 0x10) * 2 + sub, 'F0c': (op >> 4) & 1, 'F1a': (op - 0x40) >> 1,
            'F1b': sub, 'F2': (op >> 2) & 0xf, 'F3a': op & 3, 'F3b': (op >> 1) & 1, 'F3c': op & 0xf,
            'F3d': sub, 'F3e': (op >> 3) & 3}[f]


def check_decode(path):
    src = open(path).read().splitlines()
    lab = re.compile(r"(\d+)'([dhb])([0-9a-fA-F_]+)\s*:")
    ok = bad = unchecked = 0
    for d in isa.INSTRUCTIONS:
        exp = expected_label(d)
        found = None
        for line in src:
            if '//' not in line: continue
            code, _, comment = line.partition('//')
            if not re.match(r'\s*' + re.escape(d['name']) + r'\b', comment): continue
            m = lab.search(code)
            if not m: continue
            base = {'d': 10, 'h': 16, 'b': 2}[m.group(2)]
            found = int(m.group(3).replace('_', ''), base)
            break
        if found is None: unchecked += 1; continue
        if found == exp: ok += 1
        else:
            bad += 1; print(f"decode.v: {d['name']} ({d['fmt']}) case label {found} but the ISA table says {exp}")
    print(f"decode.v vs isa.py: {ok} match, {bad} mismatch, {unchecked} not found by comment")
    return bad == 0


def main():
    if '--check-decode' in sys.argv:
        sys.exit(0 if check_decode(sys.argv[sys.argv.index('--check-decode') + 1]) else 1)
    outs = {OUT_C: gen_c(), OUT_PY: gen_py(), OUT_MD: gen_md()}
    if '--check' in sys.argv:
        stale = [p for p, t in outs.items() if not os.path.exists(p) or open(p).read() != t]
        for p in stale: print("stale:", os.path.relpath(p, ROOT))
        if stale: print("run `make isa` (cpu4/gen_isa.py) and commit the result"); sys.exit(1)
        print("isa tables up to date"); return
    for p, t in outs.items():
        os.makedirs(os.path.dirname(p), exist_ok=True); open(p, 'w').write(t); print("wrote", os.path.relpath(p, ROOT))


if __name__ == '__main__':
    main()
