#!/usr/bin/env python3
"""The CPU4 semantics notation: parser and generators.

isa.SEMANTICS gives every instruction one line of register-transfer notation;
isa.SEMANTICS_PREAMBLE defines it. This module parses those lines against the
instruction's operands and format template and generates:

  gen_c()   cpu4/exec_gen.h   the fetch/decode/execute step sim_c runs (`gen_step`)
  gen_py()  cpu4/exec_gen.py  the same step for cpu4/cpu.py

Both are derived only from the templates, opcode values and semantics, from
the same syntax tree, but through different back ends and different float
implementations (fpu_model.h and its Python port fpu_model.py), so running
them in lockstep checks each against the other.

The AST is small and target-neutral, so other back ends (a Python executor,
SMT constraints for formal checks) are further functions over the same tree.
"""
import os, re, sys
here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, here)
import isa

HDR = "Generated by cpu4/gen_isa.py from cpu4/isa.py (SEMANTICS) -- do not edit; edit isa.py and run `make isa`."

# ---------------------------------------------------------------- tokens
OPS = ['<=u', '<=s', '>=u', '>=s', '>>s', '/u', '%u', '/s', '%s', '<u', '<s', '>u', '>s',
       '==', '!=', '<<', '>>', '+', '-', '*', '&', '|', '^', '~', '!', '?', ':', '(', ')',
       '[', ']', ',', ';', '=']
TOK = re.compile(r'\s*(?:(0x[0-9a-fA-F]+|\d+)|([A-Za-z_][A-Za-z0-9_]*)|(' +
                 '|'.join(re.escape(o) for o in OPS) + '))')


class SemError(Exception):
    pass


def tokenize(src):
    out, i, src = [], 0, src.rstrip()
    while i < len(src):
        m = TOK.match(src, i)
        if not m or m.end() == i:
            raise SemError(f"cannot read {src[i:]!r}")
        num, name, op = m.groups()
        out.append(('num', int(num, 0)) if num else ('name', name) if name else ('op', op))
        i = m.end()
    return out + [('end', None)]


# ---------------------------------------------------------------- parser
SPECIAL = {'PC': 16, 'SP': 16, 'BP': 16, 'LR': 16, 'H': 1}
MEM = {'M8': 8, 'M16': 16, 'M32': 32}
PRIM1 = {'itof', 'ftoi', 'frecip', 'frsqrt'}
PRIM2 = {'fadd', 'fsub', 'fmul', 'fdiv', 'flt', 'fle'}
LEVELS = [['|'], ['^'], ['&'], ['==', '!='], ['<u', '<=u', '>u', '>=u', '<s', '<=s', '>s', '>=s'],
          ['<<', '>>', '>>s'], ['+', '-'], ['*', '/u', '%u', '/s', '%s']]


class Parser:
    def __init__(self, src, operands):
        self.t, self.k, self.operands = tokenize(src), 0, operands

    def peek(self, v=None):
        kind, val = self.t[self.k]
        return (kind, val) if v is None else (val == v and kind in ('op', 'name'))

    def take(self, v=None):
        tok = self.t[self.k]
        if v is not None and tok[1] != v:
            raise SemError(f"expected {v!r}, found {tok[1]!r}")
        self.k += 1
        return tok

    def program(self):
        stmts = [self.stmt()]
        while self.peek(';'):
            self.take(';'); stmts.append(self.stmt())
        if self.peek()[0] != 'end':
            raise SemError(f"unexpected {self.peek()[1]!r}")
        return stmts

    def stmt(self):
        if self.peek('if'):
            self.take('if'); c = self.expr(); self.take('then')
            return ('if', c, self.stmt())
        kind, val = self.peek()
        if kind == 'name' and val == 'putchar':
            e = self.primary(); return ('do', e)
        lv = self.lvalue(); self.take('='); return ('assign', lv, self.expr())

    def lvalue(self):
        kind, val = self.take()
        if val == 'R':
            self.take('['); e = self.expr(); self.take(']'); return ('reg', e)
        if val in SPECIAL:
            return ('spec', val)
        if val in MEM:
            self.take('['); e = self.expr(); self.take(']'); return ('mem', MEM[val], e)
        raise SemError(f"cannot assign to {val!r}")

    def expr(self):
        c = self.binary(0)
        if self.peek('?'):
            self.take('?'); a = self.expr(); self.take(':'); b = self.expr()
            return ('cond', c, a, b)
        return c

    def binary(self, lvl):
        if lvl == len(LEVELS):
            return self.unary()
        a = self.binary(lvl + 1)
        while self.peek()[0] == 'op' and self.peek()[1] in LEVELS[lvl]:
            op = self.take()[1]; a = ('bin', op, a, self.binary(lvl + 1))
        return a

    def unary(self):
        if self.peek()[0] == 'op' and self.peek()[1] in ('-', '~', '!'):
            op = self.take()[1]; return ('un', op, self.unary())
        return self.primary()

    def primary(self):
        kind, val = self.take()
        if kind == 'num':
            return ('num', val)
        if kind == 'op' and val == '(':
            e = self.expr(); self.take(')'); return e
        if kind != 'name':
            raise SemError(f"unexpected {val!r}")
        if val == 'R':
            self.take('['); e = self.expr(); self.take(']'); return ('reg', e)
        if val in MEM:
            self.take('['); e = self.expr(); self.take(']'); return ('mem', MEM[val], e)
        if val in SPECIAL:
            return ('spec', val)
        if self.peek('('):
            self.take('('); args = [self.expr()]
            while self.peek(','):
                self.take(','); args.append(self.expr())
            self.take(')')
            want = {'sext': 1, 'sx': 2, 'zx': 2, 'lo16': 1, 'putchar': 1, **{p: 1 for p in PRIM1}, **{p: 2 for p in PRIM2}}
            if val not in want:
                raise SemError(f"unknown function {val!r}")
            if len(args) != want[val]:
                raise SemError(f"{val} takes {want[val]} argument(s)")
            if val == 'sext' and args[0][0] != 'operand':
                raise SemError("sext() takes an immediate operand name")
            return ('call', val, args)
        if val in self.operands:
            return ('operand', val)
        raise SemError(f"unknown name {val!r}")


# ---------------------------------------------------------------- operands and fields
def fields(d):
    """Bind the instruction's operands to template letters: register operands to the
    register letters in order of first appearance, immediate operands likewise."""
    tpl = isa.FORMATS[d['fmt']]['tpl'].replace(' ', '')
    letters = []
    for c in tpl:
        if c not in '01o' and c not in letters:
            letters.append(c)
    regl = [c for c in letters if c in 'dxyzr']
    imml = [c for c in letters if c in 'ijk']
    rops = [o for o in d['ops'] if o in ('rd', 'rx', 'ry')]
    iops = [o for o in d['ops'] if o not in ('rd', 'rx', 'ry')]
    if len(rops) > len(regl) or len(iops) > len(imml):
        raise SemError(f"{d['name']}: operands {d['ops']} do not fit template {tpl}")
    out = {}
    for op, c in list(zip(rops, regl)) + list(zip(iops, imml)):
        out[op] = [p for p, ch in enumerate(tpl) if ch == c]
    return tpl, out


def pattern(d):
    """The instruction's full fixed-bit pattern: {bit position: 0/1}, position 0 = MSB of byte 0."""
    tpl = isa.FORMATS[d['fmt']]['tpl'].replace(' ', '')
    later_o = [p for p, c in enumerate(tpl) if c == 'o' and p >= 8]
    pat = {}
    for p, c in enumerate(tpl):
        if c in '01':
            pat[p] = int(c)
            if p < 8 and ((d['op'] >> (7 - p)) & 1) != int(c):
                raise SemError(f"{d['name']}: first byte 0x{d['op']:02x} disagrees with template {tpl} at bit {p}")
        elif c == 'o':
            pat[p] = (d['op'] >> (7 - p)) & 1 if p < 8 else (d['subop'] >> (len(later_o) - 1 - later_o.index(p))) & 1
    return tpl, pat


def parse(d):
    tpl, fl = fields(d)
    try:
        return Parser(isa.SEMANTICS[d['name']], set(fl)).program()
    except SemError as e:
        raise SemError(f"{d['name']}: {e} in {isa.SEMANTICS[d['name']]!r}") from None


# ---------------------------------------------------------------- C back end
def c_extract(positions, L):
    """C expression extracting the (possibly split) field at `positions` from w (L bits)."""
    runs, cur = [], [positions[0]]
    for p in positions[1:]:
        if p == cur[-1] + 1:
            cur.append(p)
        else:
            runs.append(cur); cur = [p]
    runs.append(cur)
    expr, width = None, 0
    for r in runs:
        n = len(r); part = f"((w >> {L - 1 - r[-1]}) & 0x{(1 << n) - 1:x}u)"
        expr = part if expr is None else f"(({expr}) << {n}) | {part}"
        width += n
    return expr


class CGen:
    def __init__(self, d):
        self.d = d
        self.tpl, self.fl = fields(d)

    def e(self, n):
        k = n[0]
        if k == 'num':
            return f"0x{n[1]:x}u"
        if k == 'operand':
            if n[1] in ('rd', 'rx', 'ry'):
                raise SemError(f"{self.d['name']}: register field {n[1]} used as a value; write R[{n[1]}]")
            return f"f_{n[1]}"
        if k == 'reg':
            idx = n[1]
            if idx[0] == 'operand' and idx[1] in ('rd', 'rx', 'ry'):
                return f"cc->r[f_{idx[1]}]"
            if idx[0] == 'num':
                return f"cc->r[{idx[1]}]"
            raise SemError(f"{self.d['name']}: R[] takes a register field or a constant")
        if k == 'spec':
            return f"(uint32_t)cc->{n[1].lower()}" if n[1] != 'H' else "(uint32_t)cc->H"
        if k == 'mem':
            return f"gen_rd{n[1]}({self.e(n[2])}, oldpc)"
        if k == 'un':
            a = self.e(n[2])
            return {'-': f"(uint32_t)(0u - {a})", '~': f"(uint32_t)~{a}", '!': f"(uint32_t)!{a}"}[n[1]]
        if k == 'cond':
            return f"({self.e(n[1])} ? {self.e(n[2])} : {self.e(n[3])})"
        if k == 'call':
            f, a = n[1], n[2]
            if f == 'sext':
                return f"sx32(f_{a[0][1]}, {len(self.fl[a[0][1]])})"
            if f == 'sx':
                return f"sx32({self.e(a[0])}, {self.const(a[1])})"
            if f == 'zx':
                return f"({self.e(a[0])} & 0x{(1 << self.const(a[1])) - 1:x}u)"
            if f == 'lo16':
                return f"({self.e(a[0])} & 0xffffu)"
            if f in PRIM1:
                return f"cpu4_{f}({self.e(a[0])})"
            if f in PRIM2:
                return f"cpu4_{f}({self.e(a[0])}, {self.e(a[1])})"
            raise SemError(f"{f}() is a statement, not a value")
        if k == 'bin':
            op, a, b = n[1], self.e(n[2]), self.e(n[3])
            if op in ('+', '-', '*', '&', '|', '^'):
                return f"(uint32_t)({a} {op} {b})"
            if op in ('==', '!='):
                return f"(uint32_t)({a} {op} {b})"
            if op[-1] in 'us' and op[:-1] in ('<', '<=', '>', '>='):
                c = op[:-1]
                return f"(uint32_t)({a} {c} {b})" if op[-1] == 'u' else f"(uint32_t)((int32_t){a} {c} (int32_t){b})"
            fn = {'<<': 'shl32', '>>': 'shr32', '>>s': 'sar32', '/u': 'divu32', '%u': 'modu32',
                  '/s': 'divs32', '%s': 'mods32'}[op]
            return f"{fn}({a}, {b})"
        raise SemError(f"cannot generate {k}")

    def const(self, n):
        if n[0] != 'num':
            raise SemError(f"{self.d['name']}: width must be a constant")
        return n[1]

    def s(self, st, ind="    "):
        k = st[0]
        if k == 'if':
            return f"{ind}if ({self.e(st[1])}) {{\n{self.s(st[2], ind + '    ')}{ind}}}\n"
        if k == 'do':
            return f"{ind}gen_putchar({self.e(st[1][2][0])});\n"
        lv, v = st[1], self.e(st[2])
        if lv[0] == 'reg':
            return f"{ind}{self.e(lv)} = {v};\n"
        if lv[0] == 'spec':
            return f"{ind}cc->H = ({v}) & 1u;\n" if lv[1] == 'H' else f"{ind}cc->{lv[1].lower()} = (uint16_t)({v});\n"
        if lv[0] == 'mem':
            return f"{ind}gen_wr{lv[1]}({self.e(lv[2])}, {v}, oldpc);\n"
        raise SemError("bad assignment")

    def function(self):
        d, L = self.d, len(self.tpl)
        body = [f"/* {d['name']}: {isa.SEMANTICS[d['name']]} */",
                f"static void gx_{d['name']}(Core *cc, uint32_t w, uint16_t oldpc) {{"]
        for op, pos in self.fl.items():
            body.append(f"    const uint32_t f_{op} = {c_extract(pos, L)}; (void)f_{op};")
        body.append("    (void)w; (void)oldpc;")
        for st in parse(d):
            body.append(self.s(st).rstrip("\n"))
        body.append("}")
        return "\n".join(body)


def gen_c():
    L = [f"/* {HDR} */",
         "/* A complete fetch/decode/execute step for CPU4, generated from the",
         " * format templates, opcode values and semantics lines in cpu4/isa.py.",
         " * Included by sim_c.c after its memory helpers: this is the executor sim_c runs. */",
         "#ifndef CPU4_EXEC_GEN_H", "#define CPU4_EXEC_GEN_H",
         "static uint32_t sx32(uint32_t v, int n) { uint32_t m = 1u << (n - 1); v &= (n == 32) ? 0xffffffffu : ((1u << n) - 1); return (v ^ m) - m; }",
         "static uint32_t shl32(uint32_t a, uint32_t b) { return b >= 32 ? 0 : a << b; }",
         "static uint32_t shr32(uint32_t a, uint32_t b) { return b >= 32 ? 0 : a >> b; }",
         "static uint32_t sar32(uint32_t a, uint32_t b) { return b >= 32 ? ((int32_t)a < 0 ? 0xffffffffu : 0) : (uint32_t)((int32_t)a >> b); }",
         "static uint32_t divu32(uint32_t a, uint32_t b) { return b ? a / b : 0; }",
         "static uint32_t modu32(uint32_t a, uint32_t b) { return b ? a % b : 0; }",
         "static uint32_t divs32(uint32_t a, uint32_t b) { if (!b) return 0; if (a == 0x80000000u && b == 0xffffffffu) return a; return (uint32_t)((int32_t)a / (int32_t)b); }",
         "static uint32_t mods32(uint32_t a, uint32_t b) { if (!b) return 0; if (a == 0x80000000u && b == 0xffffffffu) return 0; return (uint32_t)((int32_t)a % (int32_t)b); }",
         "static uint32_t gen_rd8 (uint32_t a, uint16_t pc) { (void)pc; return read8(a); }",
         "static uint32_t gen_rd16(uint32_t a, uint16_t pc) { check_align16(a, pc); return read16(a); }",
         "static uint32_t gen_rd32(uint32_t a, uint16_t pc) { check_align32(a, pc); return read32(a); }",
         "static void gen_wr8 (uint32_t a, uint32_t v, uint16_t pc) { (void)pc; write8(a, (uint8_t)v); }",
         "static void gen_wr16(uint32_t a, uint32_t v, uint16_t pc) { check_align16(a, pc); write16(a, (uint16_t)v); }",
         "static void gen_wr32(uint32_t a, uint32_t v, uint16_t pc) { check_align32(a, pc); write32(a, v); }",
         "static void gen_putchar(uint32_t v) { fputc((int)(v & 0xff), stderr); fflush(stderr); }",
         "static uint32_t gen_fetch(uint16_t a, int n) { uint32_t w = 0; for (int i = 0; i < n; i++) w = (w << 8) | read8((uint16_t)(a + i)); return w; }",
         ""]
    for d in isa.INSTRUCTIONS:
        L.append(CGen(d).function()); L.append("")
    # decoder: one case per first byte, a nested switch where later bits decide
    pats = {d['name']: pattern(d) for d in isa.INSTRUCTIONS}
    blocks = {}
    for v in range(256):
        cands = []
        for d in isa.INSTRUCTIONS:
            tpl, pat = pats[d['name']]
            if all(((v >> (7 - p)) & 1) == b for p, b in pat.items() if p < 8):
                cands.append(d)
        if not cands:
            continue
        lens = {len(pats[d['name']][0]) for d in cands}
        if len(lens) != 1:
            raise SemError(f"first byte 0x{v:02x} starts instructions of different lengths")
        n = lens.pop() // 8
        keypos = sorted({p for d in cands for p in pats[d['name']][1] if p >= 8})
        if len(cands) == 1 and not keypos:
            code = f"gx_{cands[0]['name']}(cc, w, oldpc);"
        else:
            for d in cands:
                if not all(p in pats[d['name']][1] for p in keypos):
                    raise SemError(f"0x{v:02x}: {d['name']} leaves a distinguishing bit free")
            key = c_extract(keypos, n * 8)
            arms = []
            for d in cands:
                kv = 0
                for p in keypos:
                    kv = (kv << 1) | pats[d['name']][1][p]
                arms.append(f"        case 0x{kv:x}: gx_{d['name']}(cc, w, oldpc); break;")
            code = f"switch ({key}) {{\n" + "\n".join(arms) + "\n        default: gen_unknown(cc, w, oldpc); break;\n        }"
        blocks.setdefault((n, code), []).append(v)
    L += ["static void gen_unknown(Core *cc, uint32_t w, uint16_t oldpc) {",
          "    fprintf(stderr, \"cpu4: unknown instruction 0x%x at pc=%04x\\n\", (unsigned)w, oldpc);",
          "    g_gen_bad = 1;",
          "    cc->H = 1;", "}", "",
          "/* Execute one instruction for core cc; returns its length in bytes. */",
          "static int gen_step(Core *cc) {",
          "    const uint16_t oldpc = cc->pc;",
          "    uint32_t w;",
          "    switch (read8(oldpc)) {"]
    for (n, code), vals in sorted(blocks.items(), key=lambda kv: kv[1][0]):
        labels = " ".join(f"case 0x{v:02x}:" for v in vals)
        L.append(f"    {labels}")
        L.append(f"        w = gen_fetch(oldpc, {n}); cc->pc = (uint16_t)(oldpc + {n});")
        L.append(f"        {code}")
        L.append(f"        return {n};")
    L += ["    default:",
          "        gen_unknown(cc, read8(oldpc), oldpc);",
          "        cc->pc = (uint16_t)(oldpc + 1);",
          "        return 1;",
          "    }", "}", "#endif", ""]
    return "\n".join(L)


# ---------------------------------------------------------------- Python back end
M32 = "0xffffffff"


class PyGen(CGen):
    """Same tree, Python output. Every value is a non-negative int below 2**32."""

    def e(self, n):
        k = n[0]
        if k == 'num':
            return str(n[1])
        if k == 'operand':
            if n[1] in ('rd', 'rx', 'ry'):
                raise SemError(f"{self.d['name']}: register field {n[1]} used as a value; write R[{n[1]}]")
            return f"f_{n[1]}"
        if k == 'reg':
            idx = n[1]
            if idx[0] == 'operand' and idx[1] in ('rd', 'rx', 'ry'):
                return f"s.r[f_{idx[1]}]"
            if idx[0] == 'num':
                return f"s.r[{idx[1]}]"
            raise SemError(f"{self.d['name']}: R[] takes a register field or a constant")
        if k == 'spec':
            return f"s.{n[1] if n[1] == 'H' else n[1].lower()}"
        if k == 'mem':
            return f"rd{n[1]}(m, {self.e(n[2])}, oldpc)"
        if k == 'un':
            a = self.e(n[2])
            return {'-': f"((-{a}) & {M32})", '~': f"((~{a}) & {M32})", '!': f"(0 if {a} else 1)"}[n[1]]
        if k == 'cond':
            return f"({self.e(n[2])} if {self.e(n[1])} else {self.e(n[3])})"
        if k == 'call':
            f, a = n[1], n[2]
            if f == 'sext':
                return f"sx32(f_{a[0][1]}, {len(self.fl[a[0][1]])})"
            if f == 'sx':
                return f"sx32({self.e(a[0])}, {self.const(a[1])})"
            if f == 'zx':
                return f"({self.e(a[0])} & {(1 << self.const(a[1])) - 1})"
            if f == 'lo16':
                return f"({self.e(a[0])} & 0xffff)"
            if f in PRIM1:
                return f"cpu4_{f}({self.e(a[0])})"
            if f in PRIM2:
                return f"cpu4_{f}({self.e(a[0])}, {self.e(a[1])})"
            raise SemError(f"{f}() is a statement, not a value")
        if k == 'bin':
            op, a, b = n[1], self.e(n[2]), self.e(n[3])
            if op in ('+', '-', '*'):
                return f"(({a} {op} {b}) & {M32})"
            if op in ('&', '|', '^'):
                return f"({a} {op} {b})"
            if op in ('==', '!='):
                return f"int({a} {op} {b})"
            if op[-1] in 'us' and op[:-1] in ('<', '<=', '>', '>='):
                c = op[:-1]
                return f"int({a} {c} {b})" if op[-1] == 'u' else f"int(s32({a}) {c} s32({b}))"
            fn = {'<<': 'shl32', '>>': 'shr32', '>>s': 'sar32', '/u': 'divu32', '%u': 'modu32',
                  '/s': 'divs32', '%s': 'mods32'}[op]
            return f"{fn}({a}, {b})"
        raise SemError(f"cannot generate {k}")

    def s(self, st, ind="    "):
        k = st[0]
        if k == 'if':
            return f"{ind}if {self.e(st[1])}:\n{self.s(st[2], ind + '    ')}"
        if k == 'do':
            return f"{ind}putc({self.e(st[1][2][0])})\n"
        lv, v = st[1], self.e(st[2])
        if lv[0] == 'reg':
            return f"{ind}{self.e(lv)} = {v}\n"
        if lv[0] == 'spec':
            return f"{ind}s.H = {v} & 1\n" if lv[1] == 'H' else f"{ind}s.{lv[1].lower()} = {v} & 0xffff\n"
        if lv[0] == 'mem':
            return f"{ind}wr{lv[1]}(m, {self.e(lv[2])}, {v}, oldpc)\n"
        raise SemError("bad assignment")

    def function(self):
        d, L = self.d, len(self.tpl)
        body = [f"def gx_{d['name']}(s, m, w, oldpc):", f"    # {isa.SEMANTICS[d['name']]}"]
        for op, pos in self.fl.items():
            body.append(f"    f_{op} = {c_extract(pos, L).replace('u)', ')')}")
        for st in parse(d):
            body.append(self.s(st).rstrip("\n"))
        return "\n".join(body)


def gen_py():
    L = [f"# {HDR}",
         '"""A complete fetch/decode/execute step for CPU4, generated from the format',
         'templates, opcode values and semantics lines in cpu4/isa.py. cpu4/cpu.py runs it."""',
         "import sys",
         "from fpu_model import (cpu4_fadd, cpu4_fsub, cpu4_fmul, cpu4_fdiv, cpu4_flt, cpu4_fle,",
         "                       cpu4_itof, cpu4_ftoi, cpu4_frecip, cpu4_frsqrt)",
         "",
         "M = 0xffffffff",
         "MW = None   # when a list, every store is appended as (address, value, bytes) for the retirement trace",
         "",
         "def s32(v): return v - 0x100000000 if v & 0x80000000 else v",
         "def sx32(v, n): v &= (1 << n) - 1; return (v - (1 << n)) & M if v >> (n - 1) else v",
         "def shl32(a, b): return 0 if b >= 32 else (a << b) & M",
         "def shr32(a, b): return 0 if b >= 32 else a >> b",
         "def sar32(a, b): return (M if a & 0x80000000 else 0) if b >= 32 else (s32(a) >> b) & M",
         "def divu32(a, b): return a // b if b else 0",
         "def modu32(a, b): return a % b if b else 0",
         "def divs32(a, b):",
         "    if not b: return 0",
         "    if a == 0x80000000 and b == M: return a",
         "    q = abs(s32(a)) // abs(s32(b))",
         "    return (q if (s32(a) < 0) == (s32(b) < 0) else -q) & M",
         "def mods32(a, b):",
         "    if not b: return 0",
         "    if a == 0x80000000 and b == M: return 0",
         "    r = abs(s32(a)) % abs(s32(b))",
         "    return (-r if s32(a) < 0 else r) & M",
         "def _fault(bits, a, pc):",
         "    sys.stderr.write('CPU4 alignment error: %d-bit access to unaligned address 0x%08x at pc=0x%04x\\n' % (bits, a, pc))",
         "    sys.exit(1)",
         "def rd8(m, a, pc): return m.read8(a, False)",
         "def rd16(m, a, pc):",
         "    if a & 1: _fault(16, a, pc)",
         "    return m.read16(a, False)",
         "def rd32(m, a, pc):",
         "    if a & 3: _fault(32, a, pc)",
         "    return m.read32(a, False)",
         "def wr8(m, a, v, pc):",
         "    if MW is not None: MW.append((a, v & 0xff, 1))",
         "    m.write8(a, v & 0xff)",
         "def wr16(m, a, v, pc):",
         "    if a & 1: _fault(16, a, pc)",
         "    if MW is not None: MW.append((a, v & 0xffff, 2))",
         "    m.write16(a, v & 0xffff)",
         "def wr32(m, a, v, pc):",
         "    if a & 3: _fault(32, a, pc)",
         "    if MW is not None: MW.append((a, v, 4))",
         "    m.write32(a, v)",
         "def putc(v):",
         "    sys.stderr.write(chr(v & 0xff)); sys.stderr.flush()",
         ""]
    for d in isa.INSTRUCTIONS:
        L.append(PyGen(d).function()); L.append("")
    pats = {d['name']: pattern(d) for d in isa.INSTRUCTIONS}
    entries, keyfns = [], {}
    for v in range(256):
        cands = [d for d in isa.INSTRUCTIONS
                 if all(((v >> (7 - p)) & 1) == b for p, b in pats[d['name']][1].items() if p < 8)]
        if not cands:
            continue
        n = len(pats[cands[0]['name']][0]) // 8
        keypos = sorted({p for d in cands for p in pats[d['name']][1] if p >= 8})
        if len(cands) == 1 and not keypos:
            entries.append(f"    0x{v:02x}: ({n}, gx_{cands[0]['name']}, None, None),")
            continue
        kexpr = c_extract(keypos, n * 8).replace('u)', ')')
        kname = keyfns.setdefault(kexpr, f"_key{len(keyfns)}")
        arms = []
        for d in cands:
            kv = 0
            for p in keypos:
                kv = (kv << 1) | pats[d['name']][1][p]
            arms.append(f"0x{kv:x}: gx_{d['name']}")
        entries.append(f"    0x{v:02x}: ({n}, None, {kname}, {{{', '.join(arms)}}}),")
    for kexpr, kname in keyfns.items():
        L.append(f"def {kname}(w): return {kexpr}")
    L += ["", "DECODE = {"] + entries + ["}", "",
          "def unknown(s, w, pc):",
          "    sys.stderr.write('cpu4: unknown instruction 0x%x at pc=%04x\\n' % (w, pc))",
          "    s.H = 1",
          "",
          "def step(s, m):",
          '    """Execute one instruction; returns its length in bytes."""',
          "    oldpc = s.pc",
          "    e = DECODE.get(m.read8(oldpc, False))",
          "    if e is None:",
          "        unknown(s, m.read8(oldpc, False), oldpc); s.pc = (oldpc + 1) & 0xffff",
          "        return 1",
          "    n, fn, key, table = e",
          "    w = 0",
          "    for i in range(n):",
          "        w = (w << 8) | m.read8((oldpc + i) & 0xffff, False)",
          "    s.pc = (oldpc + n) & 0xffff",
          "    if fn is None:",
          "        fn = table.get(key(w))",
          "        if fn is None:",
          "            unknown(s, w, oldpc)",
          "            return n",
          "    fn(s, m, w, oldpc)",
          "    return n",
          ""]
    return "\n".join(L)


def check_all():
    """Parse every line and build every pattern; raise on the first problem."""
    for d in isa.INSTRUCTIONS:
        parse(d); pattern(d); CGen(d).function(); PyGen(d).function()


if __name__ == '__main__':
    check_all()
    print(gen_c()[:2000])
